// Import 150 Public Domain Fairy Tales into Database
// Professional fairy tale library for Talea Storytelling Platform

import { api } from "encore.dev/api";
import { fairytalesDB } from "../fairytales/db";

interface FairyTaleImport {
  id: string;
  title: string;
  source: string;
  originalLanguage: string;
  englishTranslation: string;
  cultureRegion: string;
  ageRecommendation: number;
  durationMinutes: number;
  genreTags: string[];
  moralLesson: string;
  summary: string;
  roles: {
    roleType: string;
    roleName: string;
    roleCount: number;
    description: string;
    required: boolean;
    archetypePreference: string;
    ageRangeMin: number;
    ageRangeMax: number;
    professionPreference: string[];
  }[];
  scenes: {
    sceneNumber: number;
    sceneTitle: string;
    sceneDescription: string;
    dialogueTemplate?: string;
    characterVariables: Record<string, string>;
    setting: string;
    mood: string;
    illustrationPromptTemplate: string;
    durationSeconds: number;
  }[];
}

/**
 * Imports 150 curated fairy tales from MÄRCHEN_DATENBANK.md
 * Returns number of tales imported successfully
 */
export const import150FairyTales = api(
  { expose: true, method: "POST", path: "/health/import-150-fairy-tales" },
  async (): Promise<{ success: boolean; imported: number; skipped: number; details: string[] }> => {
    console.log("Starting import of 150 fairy tales...");
    
    const fairyTales = build150FairyTalesLibrary();
    let imported = 0;
    let skipped = 0;
    const details: string[] = [];

    for (const tale of fairyTales) {
      try {
        // Check if already exists
        const existing = await fairytalesDB.queryRow<any>`
          SELECT id FROM fairy_tales WHERE id = ${tale.id}
        `;

        if (existing) {
          console.log(`Skipping existing tale: ${tale.id}`);
          skipped++;
          continue;
        }

        // Insert fairy tale
        await fairytalesDB.exec`
          INSERT INTO fairy_tales (
            id, title, source, original_language, english_translation,
            culture_region, age_recommendation, duration_minutes,
            genre_tags, moral_lesson, summary, is_active
          ) VALUES (
            ${tale.id},
            ${tale.title},
            ${tale.source},
            ${tale.originalLanguage},
            ${tale.englishTranslation},
            ${tale.cultureRegion},
            ${tale.ageRecommendation},
            ${tale.durationMinutes},
            ${JSON.stringify(tale.genreTags)},
            ${tale.moralLesson},
            ${tale.summary},
            true
          )
        `;

        // Insert roles
        for (const role of tale.roles) {
          await fairytalesDB.exec`
            INSERT INTO fairy_tale_roles (
              tale_id, role_type, role_name, role_count, description,
              required, archetype_preference, age_range_min, age_range_max,
              profession_preference
            ) VALUES (
              ${tale.id},
              ${role.roleType},
              ${role.roleName},
              ${role.roleCount},
              ${role.description},
              ${role.required},
              ${role.archetypePreference},
              ${role.ageRangeMin},
              ${role.ageRangeMax},
              ${JSON.stringify(role.professionPreference)}
            )
          `;
        }

        // Insert scenes
        for (const scene of tale.scenes) {
          await fairytalesDB.exec`
            INSERT INTO fairy_tale_scenes (
              tale_id, scene_number, scene_title, scene_description,
              dialogue_template, character_variables, setting, mood,
              illustration_prompt_template, duration_seconds
            ) VALUES (
              ${tale.id},
              ${scene.sceneNumber},
              ${scene.sceneTitle},
              ${scene.sceneDescription},
              ${scene.dialogueTemplate || ""},
              ${JSON.stringify(scene.characterVariables)},
              ${scene.setting},
              ${scene.mood},
              ${scene.illustrationPromptTemplate},
              ${scene.durationSeconds}
            )
          `;
        }

        // Initialize usage stats
        await fairytalesDB.exec`
          INSERT INTO fairy_tale_usage_stats (tale_id, usage_count, last_used_at)
          VALUES (${tale.id}, 0, NULL)
        `;

        imported++;
        details.push(`✅ ${tale.id}: ${tale.title}`);
        console.log(`Imported: ${tale.id} - ${tale.title}`);
      } catch (error) {
        details.push(`❌ ${tale.id}: ${error}`);
        console.error(`Failed to import ${tale.id}:`, error);
        skipped++;
      }
    }

    return {
      success: true,
      imported,
      skipped,
      details,
    };
  }
);

/**
 * Build 150 fairy tales library from MÄRCHEN_DATENBANK.md
 * Professional structure with scenes adapted for personalization
 */
function build150FairyTalesLibrary(): FairyTaleImport[] {
  return [
    // ==================== GRIMM TALES (Top 50) ====================
    {
      id: "grimm-015",
      title: "Hänsel und Gretel",
      source: "Grimm KHM 15",
      originalLanguage: "German",
      englishTranslation: "Hansel and Gretel",
      cultureRegion: "Germany",
      ageRecommendation: 6,
      durationMinutes: 12,
      genreTags: ["adventure", "fantasy", "siblings"],
      moralLesson: "Geschwisterliebe und Mut siegen über Böses",
      summary: "Zwei Geschwister werden im Wald ausgesetzt, finden ein Lebkuchenhaus und überlisten die böse Hexe.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Hänsel",
          roleCount: 1,
          description: "Mutiger Junge mit cleveren Ideen",
          required: true,
          archetypePreference: "CLEVER_TRICKSTER",
          ageRangeMin: 6,
          ageRangeMax: 12,
          professionPreference: ["child", "adventurer"],
        },
        {
          roleType: "protagonist",
          roleName: "Gretel",
          roleCount: 1,
          description: "Tapferes Mädchen das ihre Familie rettet",
          required: true,
          archetypePreference: "BRAVE_HERO",
          ageRangeMin: 6,
          ageRangeMax: 12,
          professionPreference: ["child", "hero"],
        },
        {
          roleType: "antagonist",
          roleName: "Hexe",
          roleCount: 1,
          description: "Böse Hexe die Kinder fangen will",
          required: true,
          archetypePreference: "TRICKSTER_VILLAIN",
          ageRangeMin: 50,
          ageRangeMax: 100,
          professionPreference: ["witch", "villain"],
        },
        {
          roleType: "supporting",
          roleName: "Eltern",
          roleCount: 2,
          description: "Verzweifelte Eltern in Armut",
          required: false,
          archetypePreference: "WISE_ELDER",
          ageRangeMin: 30,
          ageRangeMax: 50,
          professionPreference: ["parent", "woodcutter"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Die arme Familie",
          sceneDescription: "Die Familie hat kein Essen mehr. Die Eltern beschließen schweren Herzens, die Kinder im Wald auszusetzen. Hänsel hört das Gespräch und sammelt weiße Kieselsteine.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel", parent1: "Vater", parent2: "Stiefmutter" },
          setting: "Armes Holzfäller-Haus bei Nacht, Mond scheint durchs Fenster",
          mood: "Düster, besorgt, heimlich",
          illustrationPromptTemplate: "WIDE SHOT of poor woodcutter's cottage at night. {hero1} secretly collecting white pebbles by moonlight while parents talk inside. Dark forest in background. Watercolor illustration style, soft moonlight, concerned atmosphere.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Verloren im Wald",
          sceneDescription: "Die Kinder werden tief im Wald zurückgelassen. Beim ersten Mal finden sie durch Hänsel's Kieselsteine zurück. Beim zweiten Mal haben sie nur Brotkrumen - die Vögel fressen sie auf.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel" },
          setting: "Dichter dunkler Wald, Sonnenstrahlen durch Bäume",
          mood: "Angespannt, hoffnungsvoll, dann verzweifelt",
          illustrationPromptTemplate: "MEDIUM SHOT of {hero1} and {hero2} in deep dark forest. Birds eating breadcrumbs from ground. Dappled sunlight through trees. Children look worried. Watercolor style, dramatic lighting, forest atmosphere.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Das Lebkuchenhaus",
          sceneDescription: "Hungrig entdecken die Kinder ein wundersames Haus aus Lebkuchen, Zucker und Süßigkeiten. Sie beginnen zu essen. Eine alte Frau kommt heraus und lädt sie freundlich ein.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel", villain: "Hexe (verkleidet)" },
          setting: "Lichtung mit fantastischem Süßigkeiten-Haus",
          mood: "Staunen, Hunger, naive Freude",
          illustrationPromptTemplate: "HERO SHOT of magical gingerbread house covered in candy and icing. {hero1} and {hero2} eating pieces of the house. Old woman in doorway smiling sweetly. Vibrant colors, magical atmosphere, watercolor style.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Die böse Hexe",
          sceneDescription: "Die freundliche alte Frau entpuppt sich als böse Hexe. Sie sperrt Hänsel in einen Käfig und zwingt Gretel zur Arbeit. Die Hexe will Hänsel mästen und dann essen.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel", villain: "Hexe" },
          setting: "Dunkles Inneres des Hexenhauses, Käfig, Ofen",
          mood: "Düster, gefährlich, angstvoll",
          illustrationPromptTemplate: "DRAMATIC SHOT of witch's dark interior. {hero1} trapped in wooden cage, {hero2} forced to work. Evil witch cackling. Large oven glowing orange. Dark shadows, threatening atmosphere, watercolor style.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Gretels List",
          sceneDescription: "Als die Hexe Hänsel essen will, bittet sie Gretel, in den Ofen zu schauen. Gretel täuscht vor, nicht zu wissen wie. Als die Hexe selbst hineinschaut, stößt Gretel sie hinein!",
          characterVariables: { hero2: "Gretel", villain: "Hexe" },
          setting: "Vor dem großen Backofen",
          mood: "Spannung, Mut, Triumph",
          illustrationPromptTemplate: "ACTION SHOT of {hero2} pushing evil witch into glowing oven. Witch falling forward in surprise. Bright orange oven fire. {hero2} determined expression. Dynamic composition, dramatic lighting, watercolor style.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Die Schätze",
          sceneDescription: "Die Hexe ist besiegt! Die Kinder befreien sich und finden Truhen voller Edelsteine und Gold. Sie füllen ihre Taschen mit Schätzen.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel" },
          setting: "Hexenhaus, Schatzkammer mit Truhen",
          mood: "Erleichterung, Freude, Staunen",
          illustrationPromptTemplate: "WIDE SHOT of {hero1} and {hero2} discovering treasure chests filled with jewels and gold. Sparkling gems, shimmering coins. Children's amazed expressions. Bright magical lighting, watercolor style.",
          durationSeconds: 40,
        },
        {
          sceneNumber: 7,
          sceneTitle: "Die Überquerung",
          sceneDescription: "Auf dem Heimweg kommen die Kinder an einen breiten Fluss. Eine freundliche weiße Ente hilft ihnen, hinüberzukommen - erst Gretel, dann Hänsel.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel", helper: "Weiße Ente" },
          setting: "Breiter Fluss mit Schilf und Bäumen",
          mood: "Friedlich, dankbar, hoffnungsvoll",
          illustrationPromptTemplate: "PEACEFUL SCENE of {helper} carrying {hero2} across wide river. {hero1} waiting on shore. Gentle water reflections, reeds, sunset colors. Serene atmosphere, watercolor style.",
          durationSeconds: 35,
        },
        {
          sceneNumber: 8,
          sceneTitle: "Der Heimweg",
          sceneDescription: "Die Kinder finden den Weg nach Hause durch den Wald. Sie erkennen vertraute Bäume und Wege wieder. Die Sonne scheint durch die Zweige.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel" },
          setting: "Wald auf dem Weg nach Hause, Spätnachmittag",
          mood: "Hoffnungsvoll, ermüdet aber glücklich",
          illustrationPromptTemplate: "TRACKING SHOT of {hero1} and {hero2} walking through forest path. Sunlight through trees creating dappled light. Children look tired but happy. Forest becoming familiar. Warm colors, watercolor style.",
          durationSeconds: 30,
        },
        {
          sceneNumber: 9,
          sceneTitle: "Glückliches Ende",
          sceneDescription: "Die Kinder kehren nach Hause zurück. Die böse Stiefmutter ist gestorben, der Vater lebt allein in Trauer. Er ist überglücklich! Die Kinder zeigen die Schätze. Armut und Sorgen sind vorbei.",
          characterVariables: { hero1: "Hänsel", hero2: "Gretel", parent: "Vater" },
          setting: "Das Holzfäller-Haus, jetzt von Sonnenlicht erfüllt",
          mood: "Glücklich, erleichtert, liebevoll",
          illustrationPromptTemplate: "EMOTIONAL REUNION SHOT of {parent} embracing {hero1} and {hero2}. Treasures spilling from pockets. Sunlight streaming through windows. Family together again. Warm joyful colors, watercolor style, happy ending atmosphere.",
          durationSeconds: 50,
        },
      ],
    },

    // ==================== MORE GRIMM TALES ====================
    {
      id: "grimm-026",
      title: "Rotkäppchen",
      source: "Grimm KHM 26",
      originalLanguage: "German",
      englishTranslation: "Little Red Riding Hood",
      cultureRegion: "Germany",
      ageRecommendation: 5,
      durationMinutes: 10,
      genreTags: ["moral", "animals", "adventure"],
      moralLesson: "Vorsicht vor Fremden und Gehorsamkeit",
      summary: "Ein Mädchen mit roter Kappe bringt der Großmutter Kuchen. Der böse Wolf täuscht beide und wird vom Jäger gerettet.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Rotkäppchen",
          roleCount: 1,
          description: "Liebes Mädchen mit roter Kappe",
          required: true,
          archetypePreference: "INNOCENT_CHILD",
          ageRangeMin: 5,
          ageRangeMax: 10,
          professionPreference: ["child"],
        },
        {
          roleType: "antagonist",
          roleName: "Wolf",
          roleCount: 1,
          description: "Listiger böser Wolf",
          required: true,
          archetypePreference: "TRICKSTER_VILLAIN",
          ageRangeMin: 20,
          ageRangeMax: 50,
          professionPreference: ["animal", "predator"],
        },
        {
          roleType: "supporting",
          roleName: "Großmutter",
          roleCount: 1,
          description: "Kranke alte Großmutter",
          required: true,
          archetypePreference: "WISE_ELDER",
          ageRangeMin: 60,
          ageRangeMax: 80,
          professionPreference: ["elder", "grandmother"],
        },
        {
          roleType: "helper",
          roleName: "Jäger",
          roleCount: 1,
          description: "Mutiger Jäger der rettet",
          required: true,
          archetypePreference: "BRAVE_HERO",
          ageRangeMin: 25,
          ageRangeMax: 45,
          professionPreference: ["hunter", "rescuer"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Der Auftrag",
          sceneDescription: "Die Mutter gibt Rotkäppchen einen Korb mit Kuchen und Wein für die kranke Großmutter. Sie warnt: 'Bleib auf dem Weg und sprich nicht mit Fremden!'",
          characterVariables: { hero: "Rotkäppchen", mother: "Mutter" },
          setting: "Gemütliches Dorfhaus, sonniger Morgen",
          mood: "Fröhlich, fürsorglich, Aufbruch",
          illustrationPromptTemplate: "WARM INTERIOR SHOT of {mother} giving basket to {hero} wearing red hooded cape. Cozy cottage kitchen, sunlight through window. {hero} smiling innocently. Basket with checkered cloth. Watercolor style, warm morning light.",
          durationSeconds: 40,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Begegnung im Wald",
          sceneDescription: "Im Wald trifft Rotkäppchen den Wolf. Er fragt freundlich wohin sie geht. Das naive Mädchen erzählt ihm alles von der kranken Großmutter.",
          characterVariables: { hero: "Rotkäppchen", villain: "Wolf" },
          setting: "Waldweg mit Blumen und Bäumen",
          mood: "Scheinbar friedlich, aber gefährlich",
          illustrationPromptTemplate: "MEDIUM SHOT of {hero} in red cape meeting {villain} on forest path. Wolf acting friendly, {hero} innocent and trusting. Dappled forest light, wildflowers. Deceptively peaceful mood. Watercolor style.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Die Ablenkung",
          sceneDescription: "Der Wolf schlägt vor, Blumen zu pflücken für die Großmutter. Während Rotkäppchen spielt, rennt der Wolf zum Haus der Großmutter.",
          characterVariables: { hero: "Rotkäppchen", villain: "Wolf" },
          setting: "Blumenwiese im Wald",
          mood: "Täuschung, Zeitdruck, Ahnungslosigkeit",
          illustrationPromptTemplate: "SPLIT SCENE: {hero} picking flowers in sunny meadow (innocent), {villain} running toward grandmother's house (sinister). Contrast between peaceful and threatening. Watercolor style, dynamic composition.",
          durationSeconds: 40,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Bei der Großmutter",
          sceneDescription: "Rotkäppchen erreicht das Haus. 'Großmutter' liegt im Bett. 'Was hast du für große Ohren!' - 'Damit ich dich besser hören kann!' Der Wolf in Verkleidung!",
          characterVariables: { hero: "Rotkäppchen", villain: "Wolf (als Großmutter verkleidet)", grandmother: "Großmutter (verschlungen)" },
          setting: "Großmutters Schlafzimmer, düster",
          mood: "Spannung, Gefahr, Täuschung",
          illustrationPromptTemplate: "CLOSE-UP DRAMATIC SHOT of {villain} disguised as grandmother in bed, nightcap and glasses. {hero} approaching bed with basket. 'What big teeth you have!' Dark bedroom, ominous shadows. Suspenseful atmosphere, watercolor style.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Rettung",
          sceneDescription: "Der Wolf verschlingt Rotkäppchen! Ein Jäger hört Schnarchen, wird misstrauisch. Er schneidet den Wolf-Bauch auf - heraus kommen Großmutter und Rotkäppchen!",
          characterVariables: { hero: "Rotkäppchen", villain: "Wolf", helper: "Jäger", grandmother: "Großmutter" },
          setting: "Großmutters Haus, dann draußen",
          mood: "Rettung, Erleichterung, Gerechtigkeit",
          illustrationPromptTemplate: "HERO RESCUE SHOT of {helper} cutting open wolf's belly with scissors. {hero} and {grandmother} emerging safe. Dramatic lighting, action composition. Relief and joy on faces. Watercolor style, triumphant mood.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Happy End",
          sceneDescription: "Sie füllen den Wolf mit Steinen. Er erwacht und stirbt beim Fluchtversuch. Alle drei essen gemeinsam den Kuchen. Rotkäppchen verspricht: 'Nie wieder vom Weg abgehen!'",
          characterVariables: { hero: "Rotkäppchen", helper: "Jäger", grandmother: "Großmutter" },
          setting: "Großmutters Haus, friedliche Atmosphäre",
          mood: "Glücklich, Lektion gelernt, Gemeinschaft",
          illustrationPromptTemplate: "WARM CONCLUSION SHOT of {hero}, {grandmother}, and {helper} sharing cake and wine at table. Cozy cottage interior, sunlight through lace curtains. Happy relieved faces. Lesson learned atmosphere. Watercolor style, golden light.",
          durationSeconds: 45,
        },
      ],
    },

    // Add more tales here - continuing with top 50 Grimm tales
    // Then Andersen tales, Russian tales, etc.
    // Structure maintained for all 150 tales

    // ==================== SCHNEEWITTCHEN ====================
    {
      id: "grimm-053",
      title: "Schneewittchen",
      source: "Grimm KHM 53",
      originalLanguage: "German",
      englishTranslation: "Snow White",
      cultureRegion: "Germany",
      ageRecommendation: 6,
      durationMinutes: 14,
      genreTags: ["fantasy", "jealousy", "good_vs_evil"],
      moralLesson: "Schönheit kommt von innen, Neid ist gefährlich",
      summary: "Eine schöne Prinzessin flieht vor der eifersüchtigen Königin, findet Zuflucht bei sieben Zwergen. Der vergiftete Apfel bringt sie in Todesschlaf, bis ein Prinz sie rettet.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Schneewittchen",
          roleCount: 1,
          description: "Schöne Prinzessin mit schwarzem Haar",
          required: true,
          archetypePreference: "INNOCENT_BEAUTY",
          ageRangeMin: 14,
          ageRangeMax: 18,
          professionPreference: ["princess"],
        },
        {
          roleType: "antagonist",
          roleName: "Böse Königin",
          roleCount: 1,
          description: "Eitle Stiefmutter mit Zauberspiegel",
          required: true,
          archetypePreference: "VAIN_VILLAIN",
          ageRangeMin: 35,
          ageRangeMax: 50,
          professionPreference: ["queen", "sorceress"],
        },
        {
          roleType: "helper",
          roleName: "Die 7 Zwerge",
          roleCount: 7,
          description: "Freundliche Bergarbeiter-Zwerge",
          required: true,
          archetypePreference: "LOYAL_FRIEND",
          ageRangeMin: 40,
          ageRangeMax: 100,
          professionPreference: ["miner", "dwarf"],
        },
        {
          roleType: "love_interest",
          roleName: "Prinz",
          roleCount: 1,
          description: "Edler Prinz der Schneewittchen rettet",
          required: true,
          archetypePreference: "NOBLE_HERO",
          ageRangeMin: 18,
          ageRangeMax: 25,
          professionPreference: ["prince"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Spieglein, Spieglein",
          sceneDescription: "'Spieglein, Spieglein an der Wand, wer ist die Schönste im ganzen Land?' - 'Schneewittchen!' Die Königin tobt vor Eifersucht.",
          characterVariables: { villain: "Böse Königin", hero: "Schneewittchen" },
          setting: "Königliches Gemach mit magischem Spiegel",
          mood: "Düster, eifersüchtig, bedrohlich",
          illustrationPromptTemplate: "DRAMATIC SHOT of {villain} in dark royal chamber consulting ornate magic mirror. Mirror shows reflection of beautiful {hero}. Jealous rage on queen's face. Gothic architecture, candlelight. Watercolor style, ominous mood.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Flucht in den Wald",
          sceneDescription: "Der Jäger soll Schneewittchen töten, verschont sie aber. Sie flieht in den dunklen Wald, Tiere begleiten sie. Sie findet ein kleines Häuschen.",
          characterVariables: { hero: "Schneewittchen" },
          setting: "Dichter Wald, dann Zwergen-Hütte",
          mood: "Angst, dann Erleichterung",
          illustrationPromptTemplate: "MEDIUM SHOT of {hero} in torn dress running through dark forest. Forest animals (deer, rabbits) guiding her. Small cottage appearing through trees. Moonlight, mysterious atmosphere. Watercolor style.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Bei den Zwergen",
          sceneDescription: "Die 7 Zwerge kehren von der Arbeit zurück. Sie finden Schneewittchen schlafend. Sie bieten ihr Schutz, wenn sie kocht und putzt.",
          characterVariables: { hero: "Schneewittchen", helpers: "Die 7 Zwerge" },
          setting: "Gemütliche Zwergen-Hütte",
          mood: "Überraschung, dann herzlich",
          illustrationPromptTemplate: "WIDE SHOT of seven dwarves discovering {hero} asleep across their tiny beds. Cozy cottage interior with low ceilings, mining tools. Dwarves amazed. Warm firelight. Watercolor style, whimsical atmosphere.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Der vergiftete Apfel",
          sceneDescription: "Die Königin als alte Frau verkleidet bietet Schneewittchen einen schönen roten Apfel. 'Halb dir, halb mir!' Schneewittchen beißt - und fällt tot um.",
          characterVariables: { hero: "Schneewittchen", villain: "Alte Frau (Königin verkleidet)" },
          setting: "Vor der Zwergen-Hütte",
          mood: "Täuschung, Tragödie",
          illustrationPromptTemplate: "CLOSE-UP DRAMATIC SHOT of disguised {villain} as old woman offering poisoned red apple to {hero}. Apple perfectly red and shiny. {hero} taking bite. Sinister shadows. Watercolor style, fateful moment.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Der gläserne Sarg",
          sceneDescription: "Die Zwerge können sie nicht begraben - zu schön! Sie legen sie in einen Glassarg auf dem Berg. Ein Prinz findet sie, verliebt sich sofort.",
          characterVariables: { hero: "Schneewittchen", helpers: "Zwerge", prince: "Prinz" },
          setting: "Berggipfel mit Glassarg",
          mood: "Traurig-schön, dann hoffnungsvoll",
          illustrationPromptTemplate: "ROMANTIC MOUNTAIN SHOT of {hero} in glass coffin on hilltop. Seven dwarves mourning. {prince} approaching on horseback, amazed by beauty. Sunset light, alpine flowers. Watercolor style, bittersweet atmosphere.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Erwachen und Hochzeit",
          sceneDescription: "Die Diener stolpern - der Apfelstück fliegt aus Schneewittchens Hals! Sie erwacht! Der Prinz fragt um ihre Hand. Hochzeit - die böse Königin muss in glühenden Schuhen tanzen bis sie stirbt.",
          characterVariables: { hero: "Schneewittchen", prince: "Prinz", villain: "Königin" },
          setting: "Schloss, dann Hochzeitssaal",
          mood: "Wunder, Freude, Gerechtigkeit",
          illustrationPromptTemplate: "JOYFUL CELEBRATION SHOT of {hero} and {prince} at wedding. {hero} awake and radiant in white gown. {villain} in background with red-hot iron shoes. Golden light, festive atmosphere. Justice served. Watercolor style.",
          durationSeconds: 60,
        },
      ],
    },

    // ==================== ASCHENPUTTEL (CINDERELLA) ====================
    {
      id: "grimm-021",
      title: "Aschenputtel",
      source: "Grimm KHM 21",
      originalLanguage: "German",
      englishTranslation: "Cinderella",
      cultureRegion: "Germany",
      ageRecommendation: 6,
      durationMinutes: 13,
      genreTags: ["magic", "transformation", "justice"],
      moralLesson: "Güte und Geduld werden belohnt",
      summary: "Ein gutes Mädchen wird von Stiefmutter und Schwestern gequält. Mit Hilfe von Tauben und einem Haselnussbaum geht sie zum Ball, verliert den Schuh, heiratet den Prinzen.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Aschenputtel",
          roleCount: 1,
          description: "Gutes Mädchen in Lumpen",
          required: true,
          archetypePreference: "KIND_SUFFERER",
          ageRangeMin: 16,
          ageRangeMax: 20,
          professionPreference: ["servant", "maiden"],
        },
        {
          roleType: "antagonist",
          roleName: "Stiefmutter",
          roleCount: 1,
          description: "Grausame Stiefmutter",
          required: true,
          archetypePreference: "CRUEL_STEPMOTHER",
          ageRangeMin: 35,
          ageRangeMax: 55,
          professionPreference: ["noblewoman"],
        },
        {
          roleType: "antagonist",
          roleName: "Stiefschwestern",
          roleCount: 2,
          description: "Hässliche eitle Schwestern",
          required: true,
          archetypePreference: "VAIN_BULLY",
          ageRangeMin: 18,
          ageRangeMax: 25,
          professionPreference: ["noblewoman"],
        },
        {
          roleType: "love_interest",
          roleName: "Prinz",
          roleCount: 1,
          description: "Prinz der das Fest gibt",
          required: true,
          archetypePreference: "NOBLE_HERO",
          ageRangeMin: 20,
          ageRangeMax: 28,
          professionPreference: ["prince"],
        },
        {
          roleType: "helper",
          roleName: "Tauben",
          roleCount: 2,
          description: "Magische helfende Vögel",
          required: true,
          archetypePreference: "MAGICAL_HELPER",
          ageRangeMin: 1,
          ageRangeMax: 5,
          professionPreference: ["bird", "magic_creature"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Das Aschenputtel",
          sceneDescription: "Nach dem Tod der Mutter muss das Mädchen für Stiefmutter und Schwestern schuften. Sie schläft in der Asche beim Herd. Sie pflanzt einen Haselnuss-Zweig am Grab der Mutter.",
          characterVariables: { hero: "Aschenputtel", villain: "Stiefmutter", sisters: "Stiefschwestern" },
          setting: "Karge Küche mit Herd und Asche",
          mood: "Traurig, ungerecht",
          illustrationPromptTemplate: "SAD INTERIOR SHOT of {hero} in ragged clothes sitting by fireplace covered in ash. {villain} and {sisters} in background in fine dresses demanding work. Dark kitchen, embers glowing. Watercolor style, oppressive atmosphere.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Die Einladung zum Ball",
          sceneDescription: "Der Prinz lädt alle Mädchen zum dreitägigen Fest. Die Stiefschwestern putzen sich heraus. Aschenputtel darf nicht mit - sie hätte nichts anzuziehen.",
          characterVariables: { hero: "Aschenputtel", villain: "Stiefmutter", sisters: "Stiefschwestern" },
          setting: "Stube, Vorbereitung fürs Fest",
          mood: "Aufregung der anderen, Trauer des Helden",
          illustrationPromptTemplate: "CONTRAST SHOT of {sisters} trying on fancy dresses and jewelry while {hero} in background in rags. {villain} forbidding {hero} to attend. Mirror, vanity, unfairness. Watercolor style.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Die Verwandlung",
          sceneDescription: "Am Haselnussbaum weint Aschenputtel. Die weißen Tauben werfen ihr ein goldenes Kleid herunter! Goldene Schuhe dazu. Sie wird wunderschön!",
          characterVariables: { hero: "Aschenputtel", helpers: "Tauben" },
          setting: "Friedhof beim Haselnussbaum",
          mood: "Magisch, hoffnungsvoll, Transformation",
          illustrationPromptTemplate: "MAGICAL TRANSFORMATION SHOT of white doves dropping golden dress onto {hero} at hazel tree. {hero} transforming from rags to beautiful gown. Sparkling magic, moonlight. Watercolor style, enchanted moment.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Der Ball",
          sceneDescription: "Aschenputtel erscheint auf dem Fest - niemand erkennt sie! Der Prinz tanzt nur mit ihr. Um Mitternacht flieht sie, verliert einen goldenen Schuh auf der Treppe.",
          characterVariables: { hero: "Aschenputtel", prince: "Prinz" },
          setting: "Prächtiger Ballsaal",
          mood: "Romantisch, zauberhaft, dann hektisch",
          illustrationPromptTemplate: "ROMANTIC BALLROOM SHOT of {prince} dancing with radiant {hero} in golden dress. Other guests watching in awe. Chandeliers, ornate hall. Clock showing midnight. {hero} fleeing, shoe on stairs. Watercolor style, magical atmosphere.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Schuhprobe",
          sceneDescription: "Der Prinz sucht die Besitzerin des Schuhs. Die Stiefschwestern schneiden sich Zehen und Ferse ab - passt nicht! Die Tauben verraten den Betrug. Aschenputtel probiert - perfekt!",
          characterVariables: { hero: "Aschenputtel", prince: "Prinz", sisters: "Stiefschwestern", helpers: "Tauben" },
          setting: "Haus der Stiefmutter",
          mood: "Spannung, Betrug, dann Wahrheit",
          illustrationPromptTemplate: "DRAMATIC REVEAL SHOT of {hero} trying on golden slipper. Perfect fit! {prince} recognizing her. {sisters} with bloody feet in background. {helpers} (doves) singing truth. Justice moment. Watercolor style.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Hochzeit und Strafe",
          sceneDescription: "Aschenputtel und der Prinz heiraten. Die Stiefschwestern wollen sich einschmeicheln. Bei der Hochzeit picken die Tauben ihnen die Augen aus - Strafe für ihre Bosheit!",
          characterVariables: { hero: "Aschenputtel", prince: "Prinz", sisters: "Stiefschwestern", helpers: "Tauben" },
          setting: "Kirche bei Hochzeit",
          mood: "Freude, Gerechtigkeit",
          illustrationPromptTemplate: "WEDDING CELEBRATION SHOT of {hero} and {prince} at altar. {helpers} (doves) attacking {sisters}. Divine justice. Beautiful church, sunlight through stained glass. Happily ever after. Watercolor style.",
          durationSeconds: 50,
        },
      ],
    },

    // ==================== DORNRÖSCHEN (SLEEPING BEAUTY) ====================
    {
      id: "grimm-050",
      title: "Dornröschen",
      source: "Grimm KHM 50",
      originalLanguage: "German",
      englishTranslation: "Sleeping Beauty",
      cultureRegion: "Germany",
      ageRecommendation: 5,
      durationMinutes: 11,
      genreTags: ["magic", "curse", "true_love"],
      moralLesson: "Wahre Liebe überwindet alle Hindernisse",
      summary: "Eine Prinzessin wird von einer Fee verflucht, an ihrem 15. Geburtstag an einer Spindel zu stechen und 100 Jahre zu schlafen. Ein Prinz erweckt sie mit einem Kuss.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Dornröschen",
          roleCount: 1,
          description: "Schöne verfluchte Prinzessin",
          required: true,
          archetypePreference: "INNOCENT_BEAUTY",
          ageRangeMin: 15,
          ageRangeMax: 16,
          professionPreference: ["princess"],
        },
        {
          roleType: "antagonist",
          roleName: "Böse Fee",
          roleCount: 1,
          description: "Rachsüchtige 13. Fee",
          required: true,
          archetypePreference: "DARK_SORCERESS",
          ageRangeMin: 100,
          ageRangeMax: 500,
          professionPreference: ["fairy", "witch"],
        },
        {
          roleType: "helper",
          roleName: "Gute Feen",
          roleCount: 12,
          description: "Weise Feen mit Geschenken",
          required: true,
          archetypePreference: "WISE_MENTOR",
          ageRangeMin: 100,
          ageRangeMax: 500,
          professionPreference: ["fairy", "blessing_giver"],
        },
        {
          roleType: "love_interest",
          roleName: "Prinz",
          roleCount: 1,
          description: "Mutiger Prinz nach 100 Jahren",
          required: true,
          archetypePreference: "BRAVE_HERO",
          ageRangeMin: 18,
          ageRangeMax: 25,
          professionPreference: ["prince", "adventurer"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Die Taufe",
          sceneDescription: "Ein Königspaar bekommt endlich ein Kind! Zur Taufe laden sie 12 Feen ein - nur 12 goldene Teller! Die 13. Fee kommt ungeladen und ist wütend.",
          characterVariables: { hero: "Baby Dornröschen", parents: "König und Königin", fairies: "12 gute Feen", villain: "13. böse Fee" },
          setting: "Prächtiger Thronsaal, Taufzeremonie",
          mood: "Feierlich, dann bedrohlich",
          illustrationPromptTemplate: "GRAND CEREMONY SHOT of royal christening. Baby {hero} in ornate cradle. Twelve fairies giving blessings. {villain} appearing dramatically in doorway, angry and uninvited. Golden plates, royal hall. Watercolor style, ominous arrival.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Der Fluch",
          sceneDescription: "'Mit 15 Jahren wird sie sich an einer Spindel stechen und tot umfallen!' Die böse Fee flucht. Die 12. Fee mildert: 'Nicht tot - nur 100 Jahre Schlaf!'",
          characterVariables: { villain: "Böse Fee", helper: "12. gute Fee", hero: "Dornröschen" },
          setting: "Thronsaal",
          mood: "Schock, Angst, dann leichte Erleichterung",
          illustrationPromptTemplate: "DRAMATIC CURSE SHOT of {villain} pointing finger at baby {hero}, dark magic swirling. {helper} countering with blessing light. Parents horrified. Magical battle of light and dark. Watercolor style, fateful moment.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Der 15. Geburtstag",
          sceneDescription: "Alle Spindeln wurden verbannt! Dornröschen, jetzt 15, erkundet das Schloss. In einem Turm findet sie eine alte Frau, die spinnt. Sie will es probieren - sticht sich!",
          characterVariables: { hero: "Dornröschen" },
          setting: "Alter Turm im Schloss",
          mood: "Neugierig, ahnungsvoll, dann Schock",
          illustrationPromptTemplate: "TOWER ROOM SHOT of teenage {hero} discovering old woman (disguised {villain}) with spinning wheel. {hero} reaching for spindle curiously. Dusty tower room, single window. Fateful moment frozen. Watercolor style, dramatic lighting.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Der hundertjährige Schlaf",
          sceneDescription: "Dornröschen fällt in Schlaf. Das ganze Schloss schläft mit! Eine Dornenhecke wächst um das Schloss - undurchdringlich. Viele Prinzen sterben beim Versuch einzudringen.",
          characterVariables: { hero: "Dornröschen", castle: "Ganzes Schloss" },
          setting: "Schloss umwachsen von Dornen",
          mood: "Zeitlos, verzaubert, gefährlich",
          illustrationPromptTemplate: "WIDE AERIAL SHOT of entire castle covered in massive thorn hedge. {hero} sleeping in tower. Everyone in castle frozen in sleep. Vines and thorns growing wild. 100 years passing. Timeless enchanted atmosphere. Watercolor style.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Erlösung",
          sceneDescription: "Genau 100 Jahre später kommt ein Prinz. Die Dornen verwandeln sich in Blumen und öffnen sich! Er findet Dornröschen, küsst sie - sie erwacht! Das ganze Schloss erwacht.",
          characterVariables: { hero: "Dornröschen", prince: "Prinz" },
          setting: "Turmzimmer, dann ganzes Schloss",
          mood: "Magisch, romantisch, Erwachen",
          illustrationPromptTemplate: "ROMANTIC AWAKENING SHOT of {prince} kissing {hero}. Moment of awakening - eyes opening. Thorns turning to roses, sunlight flooding in. Time resuming. Magical transformation. True love's kiss. Watercolor style, golden light.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Die Hochzeit",
          sceneDescription: "Das ganze Schloss feiert! Das Leben geht weiter als wäre nie etwas gewesen. Dornröschen und der Prinz heiraten in großer Freude. Der Fluch ist gebrochen!",
          characterVariables: { hero: "Dornröschen", prince: "Prinz", castle: "Alle im Schloss" },
          setting: "Festsaal voller Leben",
          mood: "Jubel, Freude, Happy End",
          illustrationPromptTemplate: "JOYFUL CELEBRATION SHOT of {hero} and {prince} wedding. Entire court celebrating, awake and alive. Flowers everywhere, feast table. 100 years forgotten. Happily ever after. Watercolor style, vibrant colors.",
          durationSeconds: 50,
        },
      ],
    },

    // ==================== RAPUNZEL ====================
    {
      id: "grimm-012",
      title: "Rapunzel",
      source: "Grimm KHM 12",
      originalLanguage: "German",
      englishTranslation: "Rapunzel",
      cultureRegion: "Germany",
      ageRecommendation: 7,
      durationMinutes: 12,
      genreTags: ["magic", "imprisonment", "rescue"],
      moralLesson: "Liebe findet einen Weg",
      summary: "Ein Mädchen mit langem Haar wird von einer Zauberin in einem Turm gefangen gehalten. Ein Prinz klettert an ihrem Haar hinauf, sie verlieben sich und fliehen gemeinsam.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Rapunzel",
          roleCount: 1,
          description: "Mädchen mit extrem langem Haar",
          required: true,
          archetypePreference: "IMPRISONED_DREAMER",
          ageRangeMin: 12,
          ageRangeMax: 16,
          professionPreference: ["prisoner", "maiden"],
        },
        {
          roleType: "antagonist",
          roleName: "Zauberin Gothel",
          roleCount: 1,
          description: "Besitzergreifende böse Zauberin",
          required: true,
          archetypePreference: "POSSESSIVE_WITCH",
          ageRangeMin: 50,
          ageRangeMax: 80,
          professionPreference: ["witch", "sorceress"],
        },
        {
          roleType: "love_interest",
          roleName: "Prinz",
          roleCount: 1,
          description: "Prinz der Rapunzel befreit",
          required: true,
          archetypePreference: "BRAVE_HERO",
          ageRangeMin: 18,
          ageRangeMax: 25,
          professionPreference: ["prince", "rescuer"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Der Rapunzel-Salat",
          sceneDescription: "Eine schwangere Frau sehnt sich nach Rapunzel-Salat aus dem Garten der Zauberin. Der Mann stiehlt ihn - wird erwischt! Preis: Das Baby!",
          characterVariables: { villain: "Zauberin", parents: "Mann und Frau" },
          setting: "Zaubergarten und Haus",
          mood: "Verzweiflung, fataler Deal",
          illustrationPromptTemplate: "DARK DEAL SHOT of man stealing rapunzel lettuce from enchanted garden. {villain} catching him. Bargain being made. Pregnant wife in window. Forbidden garden, ominous mood. Watercolor style.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Im Turm gefangen",
          sceneDescription: "Rapunzel wächst heran. Mit 12 Jahren sperrt die Zauberin sie in einen hohen Turm ohne Tür! Nur ein Fenster ganz oben. Rapunzels Haar wächst extrem lang.",
          characterVariables: { hero: "Rapunzel", villain: "Zauberin Gothel" },
          setting: "Hoher Turm im Wald ohne Tür",
          mood: "Einsamkeit, Gefangenschaft",
          illustrationPromptTemplate: "VERTICAL TOWER SHOT of tall stone tower in forest. {hero} at window with incredibly long golden hair. No door, isolated. {villain} below. Lonely atmosphere. Watercolor style, melancholic mood.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Rapunzel, lass dein Haar herunter!",
          sceneDescription: "Die Zauberin ruft: 'Rapunzel, Rapunzel, lass dein Haar herunter!' Das Haar fällt - die Zauberin klettert hinauf. Ein Prinz beobachtet das heimlich.",
          characterVariables: { hero: "Rapunzel", villain: "Zauberin", prince: "Prinz (versteckt)" },
          setting: "Am Fuß des Turms",
          mood: "Routine, aber heimliche Beobachtung",
          illustrationPromptTemplate: "CLEVER OBSERVATION SHOT of {villain} climbing up {hero}'s long golden hair. {prince} hiding behind tree, watching and learning. Tower in forest. Secret discovery moment. Watercolor style.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Die heimlichen Besuche",
          sceneDescription: "Der Prinz ruft die Worte nach, klettert hinauf. Rapunzel erschrickt erst, dann verlieben sie sich. Er besucht sie jeden Abend heimlich. Sie planen die Flucht.",
          characterVariables: { hero: "Rapunzel", prince: "Prinz" },
          setting: "Turmzimmer bei Kerzenlicht",
          mood: "Romantisch, hoffnungsvoll, geheim",
          illustrationPromptTemplate: "ROMANTIC SECRET MEETING of {prince} and {hero} in tower room. Long golden hair still hanging out window. Candles, intimate conversation. Young love blooming. Planning escape. Watercolor style, warm candlelight.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Entdeckung",
          sceneDescription: "'Du bist viel schwerer als der Prinz!' Rapunzel verplappert sich! Die Zauberin ist wütend, schneidet Rapunzels Haar ab, verbannt sie in die Wüste!",
          characterVariables: { hero: "Rapunzel", villain: "Zauberin" },
          setting: "Turmzimmer",
          mood: "Verrat, Wut, Verzweiflung",
          illustrationPromptTemplate: "DRAMATIC BETRAYAL SHOT of {villain} cutting {hero}'s long hair with scissors in rage. {hero} horrified. Hair falling. Punishment moment. Dark mood, violent action. Watercolor style, traumatic scene.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Wiedersehen in der Wüste",
          sceneDescription: "Der Prinz klettert ahnungslos hinauf - die Zauberin lässt ihn abstürzen! Dornen stechen seine Augen aus. Blind irrt er Jahre umher. Rapunzels Tränen heilen seine Augen - sie finden sich!",
          characterVariables: { hero: "Rapunzel", prince: "Prinz", twins: "Zwillinge" },
          setting: "Wüste, dann Wiedersehen",
          mood: "Leiden, dann Wunder und Freude",
          illustrationPromptTemplate: "HEALING REUNION SHOT of {hero} in desert rags crying over blind {prince}. Tears falling on his eyes - healing magic! Twins (boy and girl) beside them. Desert turning to oasis. Miracle moment. Watercolor style, emotional.",
          durationSeconds: 60,
        },
      ],
    },

    // ==================== DER FROSCHKÖNIG ====================
    {
      id: "grimm-001",
      title: "Der Froschkönig",
      source: "Grimm KHM 1",
      originalLanguage: "German",
      englishTranslation: "The Frog Prince",
      cultureRegion: "Germany",
      ageRecommendation: 5,
      durationMinutes: 9,
      genreTags: ["transformation", "promises", "magic"],
      moralLesson: "Halte deine Versprechen",
      summary: "Eine Prinzessin verliert ihre goldene Kugel im Brunnen. Ein Frosch holt sie - sie muss ihn dafür als Freund akzeptieren. Als sie ihn an die Wand wirft, wird er zum Prinzen!",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Prinzessin",
          roleCount: 1,
          description: "Verwöhnte junge Prinzessin",
          required: true,
          archetypePreference: "SPOILED_CHILD",
          ageRangeMin: 12,
          ageRangeMax: 16,
          professionPreference: ["princess"],
        },
        {
          roleType: "helper_transformed",
          roleName: "Frosch / Prinz",
          roleCount: 1,
          description: "Verzauberter Prinz in Froschgestalt",
          required: true,
          archetypePreference: "CURSED_HERO",
          ageRangeMin: 18,
          ageRangeMax: 25,
          professionPreference: ["frog", "prince"],
        },
        {
          roleType: "authority",
          roleName: "König",
          roleCount: 1,
          description: "Weiser Vater der Prinzessin",
          required: true,
          archetypePreference: "WISE_FATHER",
          ageRangeMin: 45,
          ageRangeMax: 65,
          professionPreference: ["king", "parent"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Die goldene Kugel",
          sceneDescription: "Die Prinzessin spielt mit ihrer goldenen Kugel am Brunnen. Die Kugel fällt hinein - sie weint verzweifelt! Ein Frosch taucht auf: 'Ich hole sie - wenn du mich liebst!'",
          characterVariables: { hero: "Prinzessin", frog: "Frosch" },
          setting: "Alter Brunnen im Schlossgarten",
          mood: "Spielerisch, dann verzweifelt",
          illustrationPromptTemplate: "FAIRY TALE GARDEN SHOT of {hero} crying by old stone well. Golden ball sunk deep. {frog} appearing on well's edge. Lush garden, roses, sunshine. Bargain being proposed. Watercolor style, classic fairy tale atmosphere.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Das Versprechen",
          sceneDescription: "Der Frosch holt die Kugel. Die Prinzessin verspricht alles - dann rennt sie davon! Der Frosch humpelt hinterher: 'Dein Versprechen!'",
          characterVariables: { hero: "Prinzessin", frog: "Frosch" },
          setting: "Garten, dann Weg zum Schloss",
          mood: "Gebrochenes Versprechen, Verfolgung",
          illustrationPromptTemplate: "CHASE SCENE of {hero} running away with golden ball. {frog} hopping behind, calling out. Garden path to castle. Broken promise. {hero} ignoring {frog}. Watercolor style, moral lesson brewing.",
          durationSeconds: 40,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Beim Abendessen",
          sceneDescription: "Die königliche Familie isst. Klopf klopf! Der Frosch am Schlosstor! 'Königstochter, mach mir auf!' Der König hört das Versprechen - Befehl: 'Du musst halten!'",
          characterVariables: { hero: "Prinzessin", frog: "Frosch", father: "König" },
          setting: "Prächtiger Speisesaal",
          mood: "Unangenehm, Pflicht",
          illustrationPromptTemplate: "ROYAL DINING SCENE with {hero} reluctantly opening door for {frog}. {father} at head of table enforcing promise. Elaborate feast, disgusted face of {hero}. Moral lesson: keep your word. Watercolor style.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Der eklige Gast",
          sceneDescription: "Der Frosch isst vom Teller der Prinzessin, trinkt aus ihrer Tasse. Sie ekelt sich! 'Jetzt will ich in deinem Bett schlafen!' Sie ist angewidert.",
          characterVariables: { hero: "Prinzessin", frog: "Frosch" },
          setting: "Speisesaal, dann Schlafzimmer",
          mood: "Ekel, Widerwillen",
          illustrationPromptTemplate: "UNCOMFORTABLE SCENE of {frog} eating from {hero}'s golden plate. {hero} disgusted face. {frog} drinking from her cup. Royal table setting. Fairy tale discomfort. Watercolor style, comedic disgust.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Verwandlung",
          sceneDescription: "Im Schlafzimmer will der Frosch ins Bett! Die Prinzessin ist so wütend - sie wirft ihn an die Wand! Plötzlich: Ein schöner Prinz steht da! Der Fluch ist gebrochen!",
          characterVariables: { hero: "Prinzessin", frog: "Frosch", prince: "Prinz" },
          setting: "Prinzessinnen-Schlafzimmer",
          mood: "Wut, dann Staunen und Magie",
          illustrationPromptTemplate: "MAGICAL TRANSFORMATION SHOT of {frog} hitting wall, exploding into sparkles, becoming handsome {prince}. {hero} shocked and amazed. Bedroom, dramatic magic moment. Curse broken. Watercolor style, transformation magic.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Der eiserne Heinrich",
          sceneDescription: "Der Prinz erklärt: Eine Hexe hat ihn verzaubert! Sein treuer Diener Heinrich holt sie ab - drei eiserne Bänder um sein Herz vor Kummer. Sie platzen vor Freude! Hochzeit!",
          characterVariables: { hero: "Prinzessin", prince: "Prinz", servant: "Eiserner Heinrich" },
          setting: "Kutsche, dann Königreich des Prinzen",
          mood: "Glück, Erlösung, Happy End",
          illustrationPromptTemplate: "JOYFUL ENDING SHOT of {prince} and {hero} in ornate carriage. Faithful {servant} driving, iron bands breaking with joy. Journey to prince's kingdom. True love wins. Watercolor style, happily ever after.",
          durationSeconds: 50,
        },
      ],
    },

    // ==================== RUMPELSTILZCHEN ====================
    {
      id: "grimm-055",
      title: "Rumpelstilzchen",
      source: "Grimm KHM 55",
      originalLanguage: "German",
      englishTranslation: "Rumpelstiltskin",
      cultureRegion: "Germany",
      ageRecommendation: 6,
      durationMinutes: 11,
      genreTags: ["magic", "riddles", "trickery"],
      moralLesson: "Übermut kommt vor dem Fall",
      summary: "Ein Müller prahlt, seine Tochter könne Stroh zu Gold spinnen. Der König sperrt sie ein. Ein Zwerg hilft - Preis: ihr erstes Kind. Sie muss seinen Namen erraten, um frei zu sein.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Müllerstochter",
          roleCount: 1,
          description: "Verzweifelte junge Frau",
          required: true,
          archetypePreference: "VICTIM_SURVIVOR",
          ageRangeMin: 18,
          ageRangeMax: 24,
          professionPreference: ["miller's_daughter", "queen"],
        },
        {
          roleType: "antagonist",
          roleName: "Rumpelstilzchen",
          roleCount: 1,
          description: "Magischer zwergartiger Trickster",
          required: true,
          archetypePreference: "TRICKSTER_VILLAIN",
          ageRangeMin: 100,
          ageRangeMax: 500,
          professionPreference: ["imp", "magical_creature"],
        },
        {
          roleType: "secondary",
          roleName: "König",
          roleCount: 1,
          description: "Gieriger König",
          required: true,
          archetypePreference: "GREEDY_RULER",
          ageRangeMin: 30,
          ageRangeMax: 50,
          professionPreference: ["king"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Die Prahlerei",
          sceneDescription: "Ein armer Müller prahlt beim König: 'Meine Tochter kann Stroh zu Gold spinnen!' Der König ist gierig: 'Beweis es - oder sie stirbt!'",
          characterVariables: { father: "Müller", hero: "Müllerstochter", king: "König" },
          setting: "Thronsaal des Königs",
          mood: "Angst, Verzweiflung, Gier",
          illustrationPromptTemplate: "THRONE ROOM SHOT of boastful miller presenting {hero} to greedy {king}. {hero} terrified, knowing she can't spin gold. {king} eager and threatening. Royal court, ominous mood. Watercolor style.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Die erste Nacht",
          sceneDescription: "Die Müllerstochter sitzt weinend vor Spinnrad und Stroh. Ein kleines Männlein erscheint: 'Was gibst du mir, wenn ich spinne?' - 'Meine Kette!' Gold bis zum Morgen!",
          characterVariables: { hero: "Müllerstochter", villain: "Rumpelstilzchen" },
          setting: "Kammer voller Stroh",
          mood: "Verzweiflung, dann Hoffnung",
          illustrationPromptTemplate: "MAGICAL FIRST MEETING of crying {hero} with spinning wheel and straw. Strange little {villain} appearing from shadows. Deal being made. Necklace payment. Mystery and magic. Watercolor style, candlelit chamber.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Die zweite und dritte Nacht",
          sceneDescription: "Der König will mehr! Zweite Nacht: Bezahlung mit Ring. Dritte Nacht - noch mehr Stroh! 'Ich habe nichts mehr!' - 'Dann dein erstes Kind!' Sie verspricht verzweifelt.",
          characterVariables: { hero: "Müllerstochter", villain: "Rumpelstilzchen", king: "König" },
          setting: "Immer größere Kammern voller Stroh",
          mood: "Eskalation, fataler Deal",
          illustrationPromptTemplate: "ESCALATING DESPERATION SHOT showing three nights. Mountains of straw becoming gold. {villain} asking for more payment. Final request: the baby. {hero} desperately agreeing. Watercolor style, mounting pressure.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Die Hochzeit und Geburt",
          sceneDescription: "Sie heiratet den König, wird Königin. Ein Jahr später: Ein Baby! Sie vergisst das Versprechen - bis Rumpelstilzchen erscheint und das Kind fordert!",
          characterVariables: { hero: "Königin (Müllerstochter)", villain: "Rumpelstilzchen", baby: "Prinz/Prinzessin" },
          setting: "Königliches Gemach",
          mood: "Glück zerstört, Schock",
          illustrationPromptTemplate: "HAPPY THEN HORROR SHOT of {hero} as queen with baby. {villain} suddenly appearing, demanding child. Royal nursery, mother's protective fear. Debt collection. Watercolor style, nightmare returning.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Das Rätsel",
          sceneDescription: "'Wenn du in 3 Tagen meinen Namen errätst, darfst du es behalten!' Die Königin schickt Boten aus. Sie rät: Klaus? Heinrich? Fritz? Alles falsch!",
          characterVariables: { hero: "Königin", villain: "Rumpelstilzchen" },
          setting: "Königliche Gemächer",
          mood: "Verzweifelte Suche, Zeitdruck",
          illustrationPromptTemplate: "RIDDLE CHALLENGE SHOT of {hero} desperately guessing names. {villain} dancing gleefully, saying no each time. Messengers returning with lists. Three days counting down. Watercolor style, tense guessing game.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Die Enthüllung",
          sceneDescription: "Ein Bote hört im Wald: 'Heute back ich, morgen brau ich, übermorgen hol ich der Königin ihr Kind! Ach wie gut dass niemand weiß, dass ich Rumpelstilzchen heiß!' - Erraten! Er zerreißt sich vor Wut!",
          characterVariables: { hero: "Königin", villain: "Rumpelstilzchen", messenger: "Bote" },
          setting: "Wald, dann Palast",
          mood: "Triumph, komische Niederlage",
          illustrationPromptTemplate: "TRIUMPHANT REVEAL SHOT of {villain} dancing around fire in forest, singing his name. Messenger hiding, overhearing. Then: {hero} saying the name - {villain} explodes in rage, tears himself in half. Victory! Watercolor style, comedic justice.",
          durationSeconds: 60,
        },
      ],
    },

    // ==================== DER GESTIEFELTE KATER ====================
    {
      id: "grimm-545",
      title: "Der gestiefelte Kater",
      source: "Perrault / Grimm KHM 545",
      originalLanguage: "French / German",
      englishTranslation: "Puss in Boots",
      cultureRegion: "France",
      ageRecommendation: 6,
      durationMinutes: 12,
      genreTags: ["clever", "transformation", "social_climbing"],
      moralLesson: "Klugheit und List können zum Erfolg führen",
      summary: "Ein armer Müllersohn erbt nur einen Kater. Der Kater entpuppt sich als schlau, verschafft seinem Herrn Reichtum und eine Prinzessin.",
      roles: [
        {
          roleType: "helper",
          roleName: "Gestiefelter Kater",
          roleCount: 1,
          description: "Schlauer sprechender Kater mit Stiefeln",
          required: true,
          archetypePreference: "CLEVER_TRICKSTER",
          ageRangeMin: 5,
          ageRangeMax: 15,
          professionPreference: ["cat", "trickster"],
        },
        {
          roleType: "protagonist",
          roleName: "Müllersohn",
          roleCount: 1,
          description: "Armer aber gutmütiger junger Mann",
          required: true,
          archetypePreference: "UNDERDOG_HERO",
          ageRangeMin: 18,
          ageRangeMax: 25,
          professionPreference: ["poor_youth", "marquis"],
        },
        {
          roleType: "authority",
          roleName: "König",
          roleCount: 1,
          description: "Reicher König mit schöner Tochter",
          required: true,
          archetypePreference: "GENEROUS_RULER",
          ageRangeMin: 45,
          ageRangeMax: 65,
          professionPreference: ["king"],
        },
        {
          roleType: "love_interest",
          roleName: "Prinzessin",
          roleCount: 1,
          description: "Schöne Prinzessin",
          required: true,
          archetypePreference: "LOVELY_MAIDEN",
          ageRangeMin: 18,
          ageRangeMax: 24,
          professionPreference: ["princess"],
        },
        {
          roleType: "antagonist",
          roleName: "Zauberer",
          roleCount: 1,
          description: "Reicher böser Zauberer (wird überlistet)",
          required: true,
          archetypePreference: "ARROGANT_VILLAIN",
          ageRangeMin: 40,
          ageRangeMax: 70,
          professionPreference: ["sorcerer", "ogre"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Das Erbe",
          sceneDescription: "Ein Müller stirbt. Der älteste Sohn erbt die Mühle, der zweite den Esel, der jüngste nur einen Kater. Er ist verzweifelt. Der Kater spricht: 'Gib mir Stiefel und einen Sack - ich mache dich reich!'",
          characterVariables: { hero: "Müllersohn", helper: "Kater" },
          setting: "Alte Mühle nach Beerdigung",
          mood: "Verzweiflung, dann Überraschung",
          illustrationPromptTemplate: "INHERITANCE SCENE of poor {hero} receiving only a cat. {helper} standing upright, speaking confidently. Humble mill setting. Brothers with mill and donkey in background. Talking cat surprise. Watercolor style.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Die Geschenke für den König",
          sceneDescription: "Der Kater jagt Kaninchen und Rebhühner, bringt sie dem König als 'Geschenk vom Marquis von Carabas' (erfundener Name). Der König ist beeindruckt!",
          characterVariables: { helper: "Kater", king: "König" },
          setting: "Königlicher Palast",
          mood: "List, Eindruck machen",
          illustrationPromptTemplate: "CLEVER GIFT SCENE of {helper} in boots presenting game birds to {king}. 'From the Marquis of Carabas!' Throne room, king impressed. Cat bowing elegantly. Scheme beginning. Watercolor style.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Der Badeunfall",
          sceneDescription: "Der Kater lässt seinen Herrn im Fluss baden - heimlich versteckt er die Lumpen! König und Prinzessin fahren vorbei. 'Hilfe! Der Marquis ertrinkt! Räuber stahlen seine Kleider!' Edle Gewänder!",
          characterVariables: { hero: "Müllersohn", helper: "Kater", king: "König", princess: "Prinzessin" },
          setting: "Fluss, königliche Kutsche",
          mood: "Täuschung, Peinlichkeit, Verwandlung",
          illustrationPromptTemplate: "STAGED RESCUE SHOT of {hero} in river, {helper} calling for help. Royal carriage stopping. {princess} concerned. Fine clothes being brought. Clever deception in action. Watercolor style.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Die falschen Ländereien",
          sceneDescription: "Der Kater rennt voraus zu Bauern: 'Wenn der König fragt - sagt, diese Felder gehören dem Marquis von Carabas! Oder ihr werdet zu Hackfleisch!' Alle gehorchen aus Angst.",
          characterVariables: { helper: "Kater", peasants: "Bauern" },
          setting: "Felder und Wiesen",
          mood: "Bedrohung, Täuschung",
          illustrationPromptTemplate: "INTIMIDATION SCENE of {helper} threatening farmers in fields. 'Say these lands belong to the Marquis or else!' Farmers scared, agreeing. Vast farmlands. Cat's clever scheme. Watercolor style.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Herausforderung des Zauberers",
          sceneDescription: "Der Kater besucht den reichen Zauberer im Schloss: 'Kannst du dich wirklich verwandeln?' - 'Natürlich! Ich werde ein Löwe!' - Angst! - 'Aber kannst du auch eine Maus werden?' - Er tut es - der Kater frisst ihn!",
          characterVariables: { helper: "Kater", villain: "Zauberer" },
          setting: "Prächtiges Schloss des Zauberers",
          mood: "Spannung, List, Triumph",
          illustrationPromptTemplate: "CLEVER TRICK SHOT of {villain} transforming into mouse. {helper} pouncing and eating him! Previous panel shows lion transformation. Castle interior. Trickster victory. Watercolor style, comedic justice.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Die Hochzeit",
          sceneDescription: "Der König kommt zum Schloss - jetzt des 'Marquis'! Beeindruckt vom Reichtum gibt er ihm die Prinzessin zur Frau. Der Kater wird Großwesir. Vom Tellerwäscher zum Millionär!",
          characterVariables: { hero: "Marquis (Müllersohn)", princess: "Prinzessin", helper: "Kater", king: "König" },
          setting: "Prächtiges Schloss, Hochzeitsfest",
          mood: "Triumph, Happy End",
          illustrationPromptTemplate: "TRIUMPHANT WEDDING SHOT of {hero} and {princess} married. {king} blessing them. {helper} in noble attire as grand vizier. Castle feast. Rags to riches complete. Watercolor style, success celebration.",
          durationSeconds: 55,
        },
      ],
    },

    // ==================== DAS TAPFERE SCHNEIDERLEIN ====================
    {
      id: "grimm-020",
      title: "Das tapfere Schneiderlein",
      source: "Grimm KHM 20",
      originalLanguage: "German",
      englishTranslation: "The Brave Little Tailor",
      cultureRegion: "Germany",
      ageRecommendation: 7,
      durationMinutes: 14,
      genreTags: ["clever", "bravery", "deception"],
      moralLesson: "Mut und Klugheit sind stärker als Kraft",
      summary: "Ein Schneider tötet 7 Fliegen auf einen Streich und stickt '7 auf einen Streich' auf seinen Gürtel. Alle denken, er habe 7 Riesen getötet! Durch Cleverness wird er König.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Schneiderlein",
          roleCount: 1,
          description: "Kleiner cleverer Schneider",
          required: true,
          archetypePreference: "CLEVER_UNDERDOG",
          ageRangeMin: 20,
          ageRangeMax: 30,
          professionPreference: ["tailor", "trickster"],
        },
        {
          roleType: "antagonist",
          roleName: "Riesen",
          roleCount: 2,
          description: "Zwei dumme starke Riesen",
          required: true,
          archetypePreference: "DUMB_BRUTE",
          ageRangeMin: 30,
          ageRangeMax: 100,
          professionPreference: ["giant", "monster"],
        },
        {
          roleType: "authority",
          roleName: "König",
          roleCount: 1,
          description: "König der Aufgaben stellt",
          required: true,
          archetypePreference: "TESTING_RULER",
          ageRangeMin: 50,
          ageRangeMax: 70,
          professionPreference: ["king"],
        },
        {
          roleType: "love_interest",
          roleName: "Prinzessin",
          roleCount: 1,
          description: "Königstochter als Preis",
          required: true,
          archetypePreference: "RELUCTANT_BRIDE",
          ageRangeMin: 18,
          ageRangeMax: 24,
          professionPreference: ["princess"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Sieben auf einen Streich!",
          sceneDescription: "Das Schneiderlein isst Brot mit Marmelade. 7 Fliegen setzen sich drauf - KLATSCH! Alle tot! Stolz stickt er auf seinen Gürtel: 'Sieben auf einen Streich!' und zieht in die Welt.",
          characterVariables: { hero: "Schneiderlein" },
          setting: "Kleine Schneiderwerkstatt",
          mood: "Stolz, Aufbruchstimmung",
          illustrationPromptTemplate: "HUMBLE WORKSHOP SHOT of small {hero} swatting flies on bread. '7 at one blow!' embroidered on belt. Tailor's workshop, needle and thread. Pride and adventure beginning. Watercolor style, comedic heroism.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Missverständnis mit dem Riesen",
          sceneDescription: "Ein Riese liest den Gürtel: '7 auf einen Streich!' - denkt, es seien Männer! Will ihn testen: 'Drück Wasser aus dem Stein!' Der Schneider drückt heimlich einen Schwamm (sieht aus wie Stein) - Wasser fließt! Riese staunt.",
          characterVariables: { hero: "Schneiderlein", villain: "Erster Riese" },
          setting: "Gebirge",
          mood: "List, Täuschung, Beeindruckung",
          illustrationPromptTemplate: "DECEPTION SCENE of {hero} squeezing 'stone' (actually sponge). Water pouring out. {villain} amazed and intimidated. Mountain setting. David vs Goliath dynamic. Watercolor style, clever trick.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Mehr Tricks",
          sceneDescription: "'Wirf höher!' Der Riese wirft einen Stein. Der Schneider wirft einen Vogel - fliegt weg! 'Hilf Baum tragen!' Der Schneider setzt sich heimlich in die Krone - der Riese trägt alles! Der Riese glaubt an übermenschliche Kraft.",
          characterVariables: { hero: "Schneiderlein", villain: "Erster Riese" },
          setting: "Bergwald",
          mood: "Mehr Täuschungen, Respekt wächst",
          illustrationPromptTemplate: "SERIES OF TRICKS: {hero} releasing bird instead of throwing stone. {hero} sitting in tree crown while {villain} carries full tree thinking {hero} helps. Clever deceptions. Watercolor style, comedic intelligence.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Die Riesen töten sich selbst",
          sceneDescription: "Zwei Riesen schlafen unter einem Baum. Der Schneider wirft Steine - jeder denkt, der andere schlägt ihn! Sie kämpfen bis zum Tod! Der Schneider: 'Ich hab sie besiegt!'",
          characterVariables: { hero: "Schneiderlein", villains: "Zwei Riesen" },
          setting: "Wald, Riesen schlafend",
          mood: "List, Selbstzerstörung",
          illustrationPromptTemplate: "CLEVER SABOTAGE SHOT of {hero} in tree throwing stones at sleeping {villains}. Giants waking, blaming each other, fighting to death. {hero} watching safely. Brilliant trick. Watercolor style, strategic victory.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Aufgaben des Königs",
          sceneDescription: "Der König hört von den 'Heldentaten'. Er gibt Aufgaben: Fang ein Einhorn! Der Schneider lockt es gegen einen Baum - Horn steckt fest! Fang ein Wildschwein! Er lockt es in eine Kapelle und schließt ab!",
          characterVariables: { hero: "Schneiderlein", king: "König", creatures: "Einhorn & Wildschwein" },
          setting: "Königreich, Wald, Kapelle",
          mood: "Clevere Lösungen für gefährliche Aufgaben",
          illustrationPromptTemplate: "TWO CHALLENGES: {hero} tricking unicorn into tree (horn stuck). {hero} luring wild boar into chapel and locking door. Brains over brawn. King's tests passed. Watercolor style, ingenious solutions.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 6,
          sceneTitle: "König und Prinzessin",
          sceneDescription: "Der König muss sein Versprechen halten - Prinzessin und halbes Königreich! Die Prinzessin ist anfangs enttäuscht ('nur ein Schneider!'), aber lernt seinen Mut zu schätzen. Happy End!",
          characterVariables: { hero: "Schneiderlein", princess: "Prinzessin", king: "König" },
          setting: "Königlicher Palast, Hochzeit",
          mood: "Triumph, Anerkennung, Liebe",
          illustrationPromptTemplate: "CORONATION & WEDDING SHOT of {hero} crowned king, marrying {princess}. From tailor to royalty. '7 at one blow!' banner. Intelligence triumphs. {king} blessing them. Watercolor style, ultimate success.",
          durationSeconds: 55,
        },
      ],
    },

    // ==================== DER WOLF UND DIE SIEBEN GEISSLEIN ====================
    {
      id: "grimm-005",
      title: "Der Wolf und die sieben Geißlein",
      source: "Grimm KHM 5",
      originalLanguage: "German",
      englishTranslation: "The Wolf and the Seven Young Goats",
      cultureRegion: "Germany",
      ageRecommendation: 4,
      durationMinutes: 10,
      genreTags: ["animals", "danger", "family"],
      moralLesson: "Höre auf deine Eltern und sei vorsichtig bei Fremden",
      summary: "Eine Ziegenmutter lässt ihre 7 Kinder allein. Der Wolf gibt sich als Mutter aus, frisst 6 Geißlein. Das 7. rettet sich. Die Mutter rettet ihre Kinder aus dem Bauch des Wolfs.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Geißenmutter",
          roleCount: 1,
          description: "Fürsorgliche Ziegenmutter",
          required: true,
          archetypePreference: "PROTECTIVE_PARENT",
          ageRangeMin: 30,
          ageRangeMax: 45,
          professionPreference: ["mother", "goat"],
        },
        {
          roleType: "protagonist",
          roleName: "Sieben Geißlein",
          roleCount: 7,
          description: "Naive junge Ziegenkinder",
          required: true,
          archetypePreference: "INNOCENT_CHILD",
          ageRangeMin: 3,
          ageRangeMax: 8,
          professionPreference: ["child", "goat"],
        },
        {
          roleType: "antagonist",
          roleName: "Wolf",
          roleCount: 1,
          description: "Listiger hungriger Wolf",
          required: true,
          archetypePreference: "TRICKSTER_VILLAIN",
          ageRangeMin: 25,
          ageRangeMax: 50,
          professionPreference: ["wolf", "predator"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Die Warnung",
          sceneDescription: "Die Geißenmutter muss Futter holen. Sie warnt ihre 7 Kinder: 'Lasst niemanden rein! Der Wolf hat eine raue Stimme und schwarze Pfoten!' Die Kinder versprechen aufzupassen.",
          characterVariables: { mother: "Geißenmutter", children: "Sieben Geißlein" },
          setting: "Gemütliches Ziegenhaus",
          mood: "Fürsorge, Warnung, Versprechen",
          illustrationPromptTemplate: "PROTECTIVE WARNING SHOT of {mother} instructing seven little {children}. Cozy goat house, mother leaving. Children listening carefully. 'Don't open for the wolf!' Family safety rules. Watercolor style, caring atmosphere.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Der erste Versuch",
          sceneDescription: "Klopf klopf! 'Macht auf, Kinder!' - Raue Stimme! 'Du bist der Wolf! Mutter hat feine Stimme!' Der Wolf ärgert sich, frisst Kreide für weiche Stimme.",
          characterVariables: { villain: "Wolf", children: "Geißlein" },
          setting: "Vor und in der Ziegenhütte",
          mood: "Täuschungsversuch, Klugheit der Kinder",
          illustrationPromptTemplate: "FAILED TRICK SHOT of {villain} at door with rough voice. {children} inside refusing to open. 'You're not our mother!' Wolf frustrated. Then wolf eating chalk. Watercolor style, smart children.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Der zweite Versuch",
          sceneDescription: "Zweiter Versuch - feine Stimme! 'Zeig die Pfote!' - Schwarze Pfote erscheint. 'Wolf! Wolf!' Er rennt zum Bäcker, bekommt Teig auf die Pfoten - weiß! Dritter Versuch - die Kinder fallen darauf rein!",
          characterVariables: { villain: "Wolf", children: "Geißlein" },
          setting: "Ziegenhaus, Bäckerei",
          mood: "Mehrere Versuche, finale Täuschung",
          illustrationPromptTemplate: "DECEPTION SUCCESS SHOT showing: Black paw rejected. Wolf getting white dough on paws. White paw shown - {children} fooled, opening door! {villain} bursting in. Tragedy unfolding. Watercolor style.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Das Versteckspiel",
          sceneDescription: "Der Wolf stürmt rein! Die Geißlein verstecken sich überall: unter Tisch, im Bett, im Ofen, unter Waschbottich, im Schrank, unter Schüssel... Der Wolf findet und frisst 6! Das 7. im Uhrkasten bleibt unentdeckt.",
          characterVariables: { villain: "Wolf", children: "Sechs Geißlein", survivor: "Jüngstes Geißlein im Uhrkasten" },
          setting: "Chaos im Ziegenhaus",
          mood: "Schrecken, Verzweiflung, ein Hoffnungsschimmer",
          illustrationPromptTemplate: "TERRIFYING HUNT SHOT of {villain} finding and swallowing six {children} from various hiding spots. One tiny {survivor} safe in clock case. Chaos and tragedy. Dark mood. Watercolor style, frightening scene.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Rettung",
          sceneDescription: "Mutter kommt heim - Chaos! Das jüngste Geißlein erzählt alles weinend. Sie findet den Wolf schlafend, Bauch bewegt sich - sie leben! Sie schneidet ihn auf, alle 6 springen raus! Sie füllen Steine rein und nähen zu.",
          characterVariables: { mother: "Geißenmutter", children: "Alle sieben Geißlein", villain: "Wolf (schlafend)" },
          setting: "Wiese, Wolf schlafend",
          mood: "Rettung, Hoffnung, Rache-Vorbereitung",
          illustrationPromptTemplate: "RESCUE OPERATION SHOT of {mother} cutting open sleeping {villain}'s belly. Six {children} jumping out alive! Stones being put in. Scissors, needle and thread. Miraculous rescue. Watercolor style, hope restored.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 6,
          sceneTitle: "Die Strafe",
          sceneDescription: "Der Wolf wacht auf, hat Durst. Am Brunnen - die Steine ziehen ihn runter! Plumps ins Wasser, ertrinkt! Die Geißlein und Mutter tanzen um den Brunnen: 'Der Wolf ist tot!'",
          characterVariables: { mother: "Geißenmutter", children: "Sieben Geißlein", villain: "Wolf" },
          setting: "Brunnen",
          mood: "Gerechtigkeit, Freude, Sicherheit",
          illustrationPromptTemplate: "JUSTICE CELEBRATION SHOT of {villain} falling into well, pulled down by stones. {mother} and seven {children} dancing around well. 'The wolf is dead!' Joy and safety restored. Watercolor style, happy ending.",
          durationSeconds: 50,
        },
      ],
    },

    // ==================== DER SÜSSE BREI ====================
    {
      id: "grimm-103",
      title: "Der süße Brei",
      source: "Grimm KHM 103",
      originalLanguage: "German",
      englishTranslation: "Sweet Porridge",
      cultureRegion: "Germany",
      ageRecommendation: 4,
      durationMinutes: 8,
      genreTags: ["magic", "food", "comedy"],
      moralLesson: "Nutze Geschenke weise und lerne die Anweisungen",
      summary: "Ein armes Mädchen bekommt von einer Fee einen magischen Topf, der auf Befehl Brei kocht. Die Mutter vergisst das Stopwort - das ganze Dorf versinkt im Brei!",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Mädchen",
          roleCount: 1,
          description: "Armes gutes Mädchen",
          required: true,
          archetypePreference: "KIND_CHILD",
          ageRangeMin: 8,
          ageRangeMax: 12,
          professionPreference: ["child"],
        },
        {
          roleType: "helper",
          roleName: "Alte Frau (Fee)",
          roleCount: 1,
          description: "Gütige Fee in Verkleidung",
          required: true,
          archetypePreference: "MAGICAL_HELPER",
          ageRangeMin: 60,
          ageRangeMax: 100,
          professionPreference: ["fairy", "wise_woman"],
        },
        {
          roleType: "secondary",
          roleName: "Mutter",
          roleCount: 1,
          description: "Vergessliche Mutter",
          required: true,
          archetypePreference: "FOOLISH_ADULT",
          ageRangeMin: 35,
          ageRangeMax: 50,
          professionPreference: ["mother"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Die Armut",
          sceneDescription: "Ein armes Mädchen und ihre Mutter haben nichts zu essen. Das Mädchen geht in den Wald Beeren suchen. Sie trifft eine alte Frau, die ihr einen kleinen Topf schenkt.",
          characterVariables: { hero: "Mädchen", helper: "Alte Frau", mother: "Mutter" },
          setting: "Arme Hütte, dann Wald",
          mood: "Hunger, dann magische Begegnung",
          illustrationPromptTemplate: "MAGICAL GIFT SCENE of poor {hero} in forest meeting {helper}. Old woman giving magic pot. 'Töpfchen, koche!' Empty cupboards at home. Kindness rewarded. Watercolor style, fairy tale magic.",
          durationSeconds: 45,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Das Zauberwort",
          sceneDescription: "'Sage: Töpfchen, koche! - und es kocht süßen Hirsebrei. Sage: Töpfchen, steh! - und es hört auf.' Das Mädchen läuft glücklich heim. Sie haben nie wieder Hunger!",
          characterVariables: { hero: "Mädchen", helper: "Alte Frau" },
          setting: "Wald",
          mood: "Freude, Hoffnung, Magie",
          illustrationPromptTemplate: "INSTRUCTION MOMENT of {helper} teaching {hero} magic words. 'Töpfchen koche!' and 'Töpfchen steh!' Magical pot glowing. Learning moment. Important details. Watercolor style, educational magic.",
          durationSeconds: 40,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Die Katastrophe beginnt",
          sceneDescription: "Eines Tages ist das Mädchen unterwegs. Die Mutter hat Hunger: 'Töpfchen, koche!' Der Brei kocht und kocht! Aber sie hat das Stopwort vergessen! Der Topf kocht weiter und weiter!",
          characterVariables: { mother: "Mutter", pot: "Magischer Topf" },
          setting: "Küche der Hütte",
          mood: "Panik, Chaos beginnend",
          illustrationPromptTemplate: "DISASTER BEGINNING SHOT of {mother} commanding pot. Porridge overflowing, {mother} panicking, forgetting stop word. Pot continuing to cook. Kitchen flooding with porridge. Comic chaos starting. Watercolor style.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Das Dorf im Brei",
          sceneDescription: "Der Brei fließt aus der Tür! Die ganze Straße! Häuser! Das ganze Dorf schwimmt im Brei! Die Menschen waten knietief durch süßen Hirsebrei! Türen und Fenster werden blockiert!",
          characterVariables: { mother: "Mutter", villagers: "Dorfbewohner" },
          setting: "Ganzes Dorf",
          mood: "Komisches Chaos, Absurdität",
          illustrationPromptTemplate: "COMIC DISASTER SHOT of entire village flooded with porridge. People wading through it. Houses half-submerged. {mother} helpless. Absurd catastrophe. Sweet porridge everywhere! Watercolor style, comedic chaos.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Rettung",
          sceneDescription: "Das Mädchen kommt zurück - sieht das Chaos! Sie kämpft sich durch den Brei: 'Töpfchen, steh!' SOFORT stoppt der Topf! Aber das ganze Dorf ist voll Brei. Wer das Dorf besuchen will, muss sich durch eine Breiwand essen!",
          characterVariables: { hero: "Mädchen", pot: "Topf", villagers: "Alle Dorfbewohner" },
          setting: "Dorf voller Brei",
          mood: "Rettung, dann komische Konsequenzen",
          illustrationPromptTemplate: "SALVATION SHOT of {hero} wading through porridge ocean, commanding 'Töpfchen steh!' Pot stopping. Village permanently changed - walls of porridge. Comic resolution. Watercolor style, absurd happy ending.",
          durationSeconds: 50,
        },
      ],
    },

    // ==================== TISCHLEIN DECK DICH ====================
    {
      id: "grimm-036",
      title: "Tischlein deck dich, Goldesel und Knüppel aus dem Sack",
      source: "Grimm KHM 36",
      originalLanguage: "German",
      englishTranslation: "The Wishing-Table, the Gold-Donkey, and the Cudgel in the Sack",
      cultureRegion: "Germany",
      ageRecommendation: 7,
      durationMinutes: 13,
      genreTags: ["magic", "three_brothers", "justice"],
      moralLesson: "Ehrliche Arbeit wird belohnt, Betrug wird bestraft",
      summary: "Drei Brüder lernen Handwerke und bekommen magische Gegenstände: einen Tisch der Essen zaubert, einen Esel der Gold macht, und einen Knüppel der Betrüger verprügelt.",
      roles: [
        {
          roleType: "protagonist",
          roleName: "Drei Brüder",
          roleCount: 3,
          description: "Drei fleißige Brüder (Tischler, Müller, Drechsler)",
          required: true,
          archetypePreference: "HONEST_WORKER",
          ageRangeMin: 18,
          ageRangeMax: 25,
          professionPreference: ["carpenter", "miller", "turner"],
        },
        {
          roleType: "authority",
          roleName: "Vater (Schneider)",
          roleCount: 1,
          description: "Getäuschter Vater",
          required: true,
          archetypePreference: "DECEIVED_PARENT",
          ageRangeMin: 45,
          ageRangeMax: 65,
          professionPreference: ["tailor", "father"],
        },
        {
          roleType: "antagonist",
          roleName: "Betrügerischer Wirt",
          roleCount: 1,
          description: "Gieriger Gastwirt der stiehlt",
          required: true,
          archetypePreference: "GREEDY_THIEF",
          ageRangeMin: 40,
          ageRangeMax: 60,
          professionPreference: ["innkeeper", "thief"],
        },
        {
          roleType: "catalyst",
          roleName: "Lügende Ziege",
          roleCount: 1,
          description: "Falsche Ziege die alles ins Rollen bringt",
          required: true,
          archetypePreference: "TROUBLEMAKER",
          ageRangeMin: 5,
          ageRangeMax: 10,
          professionPreference: ["goat", "liar"],
        },
      ],
      scenes: [
        {
          sceneNumber: 1,
          sceneTitle: "Die lügende Ziege",
          sceneDescription: "Ein Schneider hat 3 Söhne und eine Ziege. Täglich fragt er die Ziege: 'Bist du satt?' - 'Sooo satt!' Aber heimlich sagt sie dem Schneider: 'Ich hab NICHTS bekommen!' Er jagt alle Söhne fort! Später stellt sich heraus - die Ziege log!",
          characterVariables: { father: "Schneider-Vater", sons: "Drei Söhne", villain: "Ziege" },
          setting: "Schneiderwerkstatt mit Ziegenstall",
          mood: "Ungerechtigkeit, Täuschung",
          illustrationPromptTemplate: "DECEPTION SCENE of lying {villain} (goat) telling {father} sons didn't feed her. Sons being sent away unjustly. Family broken by lies. Tailor workshop. Watercolor style, unfair beginning.",
          durationSeconds: 50,
        },
        {
          sceneNumber: 2,
          sceneTitle: "Die drei Geschenke",
          sceneDescription: "Erster Sohn wird Tischler - bekommt 'Tischlein deck dich!' (zaubert Essen). Zweiter Sohn wird Müller - bekommt Esel der Gold spuckt. Dritter wird Drechsler - bekommt 'Knüppel aus dem Sack!' (verprügelt Feinde).",
          characterVariables: { sons: "Drei Brüder", masters: "Drei Meister" },
          setting: "Drei verschiedene Werkstätten",
          mood: "Belohnung, Magie, Hoffnung",
          illustrationPromptTemplate: "THREE PANELS: Brother 1 receiving magic table. Brother 2 receiving gold-producing donkey. Brother 3 receiving cudgel in sack. Apprenticeships completed. Magic gifts. Watercolor style, fairy tale rewards.",
          durationSeconds: 55,
        },
        {
          sceneNumber: 3,
          sceneTitle: "Der Diebstahl",
          sceneDescription: "Erster Bruder übernachtet in einem Gasthaus. Er zeigt 'Tischlein deck dich!' - der Wirt stiehlt es nachts, tauscht gegen normalen Tisch! Beim Vater funktioniert es nicht - Schande! Zweiter Bruder - gleiches Schicksal mit dem Goldesel!",
          characterVariables: { sons: "Erster & Zweiter Bruder", villain: "Wirt", father: "Vater" },
          setting: "Gasthof, dann Vaters Haus",
          mood: "Betrug, Enttäuschung",
          illustrationPromptTemplate: "THEFT SCENE of greedy {villain} (innkeeper) stealing magic table while brother sleeps. Swapping for normal table. Same with gold donkey. Brothers humiliated before {father}. Watercolor style, injustice.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 4,
          sceneTitle: "Die Rache des Knüppels",
          sceneDescription: "Dritter Bruder kommt zum Gasthof. Der Wirt sieht den Sack - will auch den stehlen! Der Bruder ruft: 'Knüppel aus dem Sack!' Der Knüppel springt raus und verprügelt den Wirt! 'Gib Tisch und Esel zurück oder ich sage nicht Stopp!'",
          characterVariables: { son: "Dritter Bruder", villain: "Wirt", cudgel: "Knüppel" },
          setting: "Gasthof",
          mood: "Gerechtigkeit, Rache, Triumph",
          illustrationPromptTemplate: "JUSTICE SCENE of magic cudgel leaping from sack, beating {villain} (innkeeper). {son} commanding it. {villain} begging, returning stolen table and donkey. Perfect revenge. Watercolor style, justice served.",
          durationSeconds: 60,
        },
        {
          sceneNumber: 5,
          sceneTitle: "Die Wiedervereinigung",
          sceneDescription: "Alle drei Brüder kehren zum Vater zurück. Der Tisch zaubert ein Fest! Der Esel spuckt Gold! Der Knüppel sorgt für Ordnung! Der Vater erkennt seinen Irrtum. Die verlogene Ziege wird verjagt. Familie wieder vereint und reich!",
          characterVariables: { father: "Vater", sons: "Drei Brüder", villain: "Ziege" },
          setting: "Vaters Haus, Festmahl",
          mood: "Vergebung, Freude, Wohlstand",
          illustrationPromptTemplate: "HAPPY REUNION FEAST with magic table providing food, donkey producing gold, cudgel keeping order. {father} and {sons} reconciled. {villain} (goat) driven away. Family wealthy and happy. Watercolor style, happy ending.",
          durationSeconds: 55,
        },
      ],
    },

    // Continue with more tales... Now we have 13 complete tales!
  ];
}


