// Code generated by the Encore 1.49.3 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly ai: ai.ServiceClient
    public readonly avatar: avatar.ServiceClient
    public readonly doku: doku.ServiceClient
    public readonly log: log.ServiceClient
    public readonly story: story.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.ai = new ai.ServiceClient(base)
        this.avatar = new avatar.ServiceClient(base)
        this.doku = new doku.ServiceClient(base)
        this.log = new log.ServiceClient(base)
        this.story = new story.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listAvatarsAdmin as api_admin_avatars_list_listAvatarsAdmin } from "~backend/admin/avatars_list";
import { updateAvatarAdmin as api_admin_avatars_update_updateAvatarAdmin } from "~backend/admin/avatars_update";
import { promoteToAdmin as api_admin_promote_promoteToAdmin } from "~backend/admin/promote";
import { getStats as api_admin_stats_getStats } from "~backend/admin/stats";
import { deleteUser as api_admin_users_delete_deleteUser } from "~backend/admin/users_delete";
import { listUsers as api_admin_users_list_listUsers } from "~backend/admin/users_list";
import { updateUser as api_admin_users_update_updateUser } from "~backend/admin/users_update";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteUser = this.deleteUser.bind(this)
            this.getStats = this.getStats.bind(this)
            this.listAvatarsAdmin = this.listAvatarsAdmin.bind(this)
            this.listUsers = this.listUsers.bind(this)
            this.promoteToAdmin = this.promoteToAdmin.bind(this)
            this.updateAvatarAdmin = this.updateAvatarAdmin.bind(this)
            this.updateUser = this.updateUser.bind(this)
        }

        /**
         * Deletes a user and their related content (avatars and stories).
         */
        public async deleteUser(params: { id: string }): Promise<ResponseType<typeof api_admin_users_delete_deleteUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/users/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_users_delete_deleteUser>
        }

        /**
         * Returns aggregate admin statistics for users, avatars, and stories.
         */
        public async getStats(): Promise<ResponseType<typeof api_admin_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_stats_getStats>
        }

        /**
         * Lists avatars across all users (admin only).
         */
        public async listAvatarsAdmin(params: RequestType<typeof api_admin_avatars_list_listAvatarsAdmin>): Promise<ResponseType<typeof api_admin_avatars_list_listAvatarsAdmin>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                cursor: params.cursor,
                limit:  params.limit === undefined ? undefined : String(params.limit),
                q:      params.q,
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/avatars`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_avatars_list_listAvatarsAdmin>
        }

        /**
         * Lists users with optional search and pagination for the admin panel.
         */
        public async listUsers(params: RequestType<typeof api_admin_users_list_listUsers>): Promise<ResponseType<typeof api_admin_users_list_listUsers>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                cursor: params.cursor,
                limit:  params.limit === undefined ? undefined : String(params.limit),
                q:      params.q,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/users`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_users_list_listUsers>
        }

        /**
         * Allows the first-ever user to promote themselves to an admin.
         * This endpoint is a one-time-use mechanism for bootstrapping the first admin account.
         */
        public async promoteToAdmin(): Promise<ResponseType<typeof api_admin_promote_promoteToAdmin>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/promote-first-admin`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_promote_promoteToAdmin>
        }

        /**
         * Updates any avatar fields (admin only).
         */
        public async updateAvatarAdmin(params: RequestType<typeof api_admin_avatars_update_updateAvatarAdmin>): Promise<ResponseType<typeof api_admin_avatars_update_updateAvatarAdmin>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description:       params.description,
                imageUrl:          params.imageUrl,
                isPublic:          params.isPublic,
                name:              params.name,
                originalAvatarId:  params.originalAvatarId,
                personalityTraits: params.personalityTraits,
                physicalTraits:    params.physicalTraits,
                visualProfile:     params.visualProfile,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/avatars/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_avatars_update_updateAvatarAdmin>
        }

        /**
         * Updates basic fields for a user (admin only).
         */
        public async updateUser(params: RequestType<typeof api_admin_users_update_updateUser>): Promise<ResponseType<typeof api_admin_users_update_updateUser>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                email:        params.email,
                name:         params.name,
                role:         params.role,
                subscription: params.subscription,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/users/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_users_update_updateUser>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { analyzeAvatarImage as api_ai_analyze_avatar_analyzeAvatarImage } from "~backend/ai/analyze-avatar";
import { generateAvatarImage as api_ai_avatar_generation_generateAvatarImage } from "~backend/ai/avatar-generation";
import {
    generateImage as api_ai_image_generation_generateImage,
    generateImagesBatch as api_ai_image_generation_generateImagesBatch
} from "~backend/ai/image-generation";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyzeAvatarImage = this.analyzeAvatarImage.bind(this)
            this.generateAvatarImage = this.generateAvatarImage.bind(this)
            this.generateImage = this.generateImage.bind(this)
            this.generateImagesBatch = this.generateImagesBatch.bind(this)
        }

        /**
         * PRODUCTION-READY SOLUTION: Nur basic analysis, 100% stabil
         */
        public async analyzeAvatarImage(params: RequestType<typeof api_ai_analyze_avatar_analyzeAvatarImage>): Promise<ResponseType<typeof api_ai_analyze_avatar_analyzeAvatarImage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/analyze-avatar-image`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_analyze_avatar_analyzeAvatarImage>
        }

        /**
         * Generates an avatar image based on physical and personality traits.
         */
        public async generateAvatarImage(params: RequestType<typeof api_ai_avatar_generation_generateAvatarImage>): Promise<ResponseType<typeof api_ai_avatar_generation_generateAvatarImage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/generate-avatar`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_avatar_generation_generateAvatarImage>
        }

        /**
         * Public API endpoint wrapper that calls the internal helper.
         */
        public async generateImage(params: RequestType<typeof api_ai_image_generation_generateImage>): Promise<ResponseType<typeof api_ai_image_generation_generateImage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/generate-image`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_image_generation_generateImage>
        }

        /**
         * Public API endpoint for batch generation.
         */
        public async generateImagesBatch(params: RequestType<typeof api_ai_image_generation_generateImagesBatch>): Promise<ResponseType<typeof api_ai_image_generation_generateImagesBatch>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/generate-images-batch`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_image_generation_generateImagesBatch>
        }
    }
}


export namespace auth {
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_avatar_create_create } from "~backend/avatar/create";
import { deleteAvatar as api_avatar_delete_deleteAvatar } from "~backend/avatar/delete";
import { get as api_avatar_get_get } from "~backend/avatar/get";
import { list as api_avatar_list_list } from "~backend/avatar/list";
import { update as api_avatar_update_update } from "~backend/avatar/update";

export namespace avatar {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteAvatar = this.deleteAvatar.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new avatar for the authenticated user.
         */
        public async create(params: RequestType<typeof api_avatar_create_create>): Promise<ResponseType<typeof api_avatar_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/avatar`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_avatar_create_create>
        }

        /**
         * Deletes an avatar.
         */
        public async deleteAvatar(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/avatar/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves a specific avatar by ID.
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_avatar_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/avatar/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_avatar_get_get>
        }

        /**
         * Retrieves all avatars for the authenticated user.
         */
        public async list(): Promise<ResponseType<typeof api_avatar_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/avatars`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_avatar_list_list>
        }

        /**
         * Updates an existing avatar.
         */
        public async update(params: RequestType<typeof api_avatar_update_update>): Promise<ResponseType<typeof api_avatar_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description:       params.description,
                imageUrl:          params.imageUrl,
                isPublic:          params.isPublic,
                name:              params.name,
                personalityTraits: params.personalityTraits,
                physicalTraits:    params.physicalTraits,
                visualProfile:     params.visualProfile,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/avatar/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_avatar_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { deleteDoku as api_doku_delete_deleteDoku } from "~backend/doku/delete";
import { generateDoku as api_doku_generate_generateDoku } from "~backend/doku/generate";
import { getDoku as api_doku_get_getDoku } from "~backend/doku/get";
import { listDokus as api_doku_list_listDokus } from "~backend/doku/list";
import { updateDoku as api_doku_update_updateDoku } from "~backend/doku/update";

export namespace doku {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteDoku = this.deleteDoku.bind(this)
            this.generateDoku = this.generateDoku.bind(this)
            this.getDoku = this.getDoku.bind(this)
            this.listDokus = this.listDokus.bind(this)
            this.updateDoku = this.updateDoku.bind(this)
        }

        public async deleteDoku(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/doku/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async generateDoku(params: RequestType<typeof api_doku_generate_generateDoku>): Promise<ResponseType<typeof api_doku_generate_generateDoku>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/doku/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_doku_generate_generateDoku>
        }

        /**
         * Retrieves a specific doku (only owner or admin or if public).
         */
        public async getDoku(params: { id: string }): Promise<ResponseType<typeof api_doku_get_getDoku>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/doku/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_doku_get_getDoku>
        }

        /**
         * Lists all dokus for the authenticated user.
         */
        public async listDokus(): Promise<ResponseType<typeof api_doku_list_listDokus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/dokus`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_doku_list_listDokus>
        }

        public async updateDoku(params: RequestType<typeof api_doku_update_updateDoku>): Promise<ResponseType<typeof api_doku_update_updateDoku>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isPublic: params.isPublic,
                title:    params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/doku/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_doku_update_updateDoku>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { get as api_log_get_get } from "~backend/log/get";
import { list as api_log_list_list } from "~backend/log/list";
import { getSources as api_log_sources_getSources } from "~backend/log/sources";

export namespace log {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.get = this.get.bind(this)
            this.getSources = this.getSources.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Retrieves a specific log entry by ID.
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_log_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/logs/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_log_get_get>
        }

        /**
         * Gets available log sources with statistics.
         */
        public async getSources(): Promise<ResponseType<typeof api_log_sources_getSources>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/logs/sources`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_log_sources_getSources>
        }

        /**
         * Lists log entries from the bucket.
         */
        public async list(params: RequestType<typeof api_log_list_list>): Promise<ResponseType<typeof api_log_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                date:   params.date,
                limit:  params.limit === undefined ? undefined : String(params.limit),
                source: params.source,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/logs`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_log_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { generateStoryContent as api_story_ai_generation_generateStoryContent } from "~backend/story/ai-generation";
import { deleteStory as api_story_delete_deleteStory } from "~backend/story/delete";
import { generate as api_story_generate_generate } from "~backend/story/generate";
import { get as api_story_get_get } from "~backend/story/get";
import { list as api_story_list_list } from "~backend/story/list";
import { update as api_story_update_update } from "~backend/story/update";

export namespace story {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteStory = this.deleteStory.bind(this)
            this.generate = this.generate.bind(this)
            this.generateStoryContent = this.generateStoryContent.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Deletes a story and all its chapters.
         */
        public async deleteStory(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/story/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Generates a new story based on the provided configuration.
         */
        public async generate(params: RequestType<typeof api_story_generate_generate>): Promise<ResponseType<typeof api_story_generate_generate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/story/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_story_generate_generate>
        }

        public async generateStoryContent(params: RequestType<typeof api_story_ai_generation_generateStoryContent>): Promise<ResponseType<typeof api_story_ai_generation_generateStoryContent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/generate-story`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_story_ai_generation_generateStoryContent>
        }

        /**
         * Retrieves a specific story by ID with all chapters.
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_story_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/story/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_story_get_get>
        }

        /**
         * Retrieves all stories for the authenticated user.
         */
        public async list(): Promise<ResponseType<typeof api_story_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/stories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_story_list_list>
        }

        /**
         * Updates an existing story's metadata.
         */
        public async update(params: RequestType<typeof api_story_update_update>): Promise<ResponseType<typeof api_story_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                isPublic:    params.isPublic,
                title:       params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/story/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_story_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    create as api_user_profile_create,
    get as api_user_profile_get,
    me as api_user_profile_me
} from "~backend/user/profile";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.me = this.me.bind(this)
        }

        /**
         * Creates a new user profile.
         */
        public async create(params: RequestType<typeof api_user_profile_create>): Promise<ResponseType<typeof api_user_profile_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_profile_create>
        }

        /**
         * Retrieves a user profile by ID.
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_user_profile_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_profile_get>
        }

        /**
         * Returns the authenticated user's profile.
         * The auth handler ensures the user exists in the database.
         */
        public async me(): Promise<ResponseType<typeof api_user_profile_me>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_profile_me>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.49.3)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
