[phases.setup]
nixPkgs = ['nodejs_20', 'bun']

[phases.install]
cmd = 'bun install'

[phases.build]
cmd = '''
cd backend &&
bun install &&
bun run build &&
cd .. &&
bun install
'''

[start]
cmd = 'cd backend && npm install -g encore.dev && encore run --port=$PORT'

[variables]
BUN_INSTALL_CACHE_DIR = '/root/.bun/install/cache'