[phases.setup]
nixPkgs = ['nodejs_20', 'bun']

[phases.install]
cmd = 'rm -f bun.lockb && bun install'

[phases.build]
cmd = '''
cd backend && bun install &&
bun run build &&
cd .. && bun install
'''

[start]
cmd = 'cd backend && encore run --port=$PORT'