[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.mcp-main"
watchPatterns = ["mcp-services/mcp-main/**"]

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
