[build]
# Do not build - use pre-built image from GitHub Container Registry
builder = "NONE"

[deploy]
# The image is built by GitHub Actions and pushed to GHCR
# Railway should pull the latest image on each deployment
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
