# ⚠️ DEPRECATED: Diese Datei wird NICHT mehr verwendet!
# 
# Das Talea Projekt nutzt jetzt GitHub Actions + GHCR für Backend Deployment
# (genau wie das NotePad Projekt)
#
# Backend wird als Docker Image von GHCR deployed, NICHT aus dem Repo gebaut.
# Siehe: GITHUB_ACTIONS_SETUP.md
#
# Diese Datei bleibt nur als REFERENZ für die ursprüngliche Konfiguration.

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[environmentVariables]]
name = "PORT"
value = "8080"

