-- Seed artifact_pool with 100 artifacts for story rewards
-- Each artifact has: German/English names, descriptions, visual keywords, scenarios, and genre affinities

INSERT INTO artifact_pool (id, name_de, name_en, description_de, description_en, category, rarity, story_role, emoji, discovery_scenarios, usage_scenarios, visual_keywords, genre_adventure, genre_fantasy, genre_mystery, genre_nature, genre_friendship, genre_courage, genre_learning) VALUES

-- WEAPONS (1-10)
('artifact_001', 'Kristallschwert', 'Crystal Sword', 'Ein glänzendes Schwert aus reinem Kristall, das im Dunkeln leuchtet', 'A gleaming sword made of pure crystal that glows in the dark', 'weapon', 'legendary', 'Kampf gegen eine dunkle Kreatur', '⚔️✨', ARRAY['In einer versteckten Höhle', 'Eingebettet in einen magischen Felsen', 'Als Geschenk von einem alten Ritter'], ARRAY['Zum Besiegen eines Monsters', 'Zum Durchschneiden magischer Barrieren', 'Zum Beschützen von Freunden'], ARRAY['crystal sword', 'glowing blade', 'magical weapon', 'luminescent', 'fantasy sword'], 0.9, 1.0, 0.6, 0.3, 0.5, 1.0, 0.3),

('artifact_006', 'Donnervorschlag', 'Thunder Hammer', 'Ein massiver Hammer, der Donner ruft', 'A massive hammer that summons thunder', 'weapon', 'legendary', 'Zerstörung von Barrieren', '🔨⚡', ARRAY['In einer Schmiedehöhle', 'Nach einem Gewitter am Boden', 'Im Tempel des Donnergottes'], ARRAY['Zum Zerschmettern von Hindernissen', 'Zum Rufen von Blitzen', 'Zum Öffnen verschlossener Tore'], ARRAY['thunder hammer', 'lightning weapon', 'storm power', 'massive hammer', 'electric glow'], 0.9, 1.0, 0.4, 0.5, 0.3, 1.0, 0.2),

('artifact_007', 'Schattendolch', 'Shadow Dagger', 'Ein dunkler Dolch, der in Schatten verschwindet', 'A dark dagger that vanishes into shadows', 'weapon', 'rare', 'Schleichende Mission', '🗡️🌑', ARRAY['In einem dunklen Versteck', 'Von einem mysteriösen Fremden', 'In den Ruinen eines alten Schlosses'], ARRAY['Zum Öffnen von Schlössern', 'Zum Durchschneiden von Seilen', 'Zum Verstecken in der Dunkelheit'], ARRAY['shadow dagger', 'dark blade', 'stealth weapon', 'mysterious knife', 'shadow magic'], 0.8, 0.9, 1.0, 0.2, 0.3, 0.7, 0.3),

('artifact_021', 'Eis-Lanzen-Spitze', 'Ice Lance Tip', 'Eine gefrorene Lanze, die Kälte ausstrahlt', 'A frozen lance that radiates cold', 'weapon', 'rare', 'Kampf gegen Feuer', '❄️🔱', ARRAY['In einer Eishöhle', 'Am Gipfel eines verschneiten Berges', 'In einem gefrorenen See'], ARRAY['Zum Löschen von Flammen', 'Zum Einfrieren von Wasser', 'Zum Abkühlen heißer Situationen'], ARRAY['ice lance', 'frozen weapon', 'frost magic', 'crystal ice', 'winter power'], 0.8, 0.9, 0.5, 0.7, 0.3, 0.8, 0.3),

('artifact_027', 'Drachenzahn', 'Dragon Tooth', 'Ein Zahn eines Drachen mit magischer Kraft', 'A dragon tooth with magical power', 'weapon', 'legendary', 'Kampf gegen böse Kräfte', '🐉💎', ARRAY['In einer Drachenhöhle', 'Als Erbstück einer Familie', 'Nach dem Besiegen eines Drachen'], ARRAY['Zum Schutz vor Feuer', 'Zum Verstärken von Zaubersprüchen', 'Als Symbol der Macht'], ARRAY['dragon tooth', 'mythical artifact', 'dragon power', 'ancient relic', 'fire resistance'], 1.0, 1.0, 0.6, 0.4, 0.4, 1.0, 0.5),

('artifact_034', 'Nebelschwert', 'Mist Sword', 'Ein Schwert aus magischem Nebel', 'A sword made of magical mist', 'weapon', 'rare', 'Kampf gegen immaterielle Gegner', '🗡️💨', ARRAY['In einem nebligen Tal', 'Am Ufer eines mystischen Sees', 'In den Wolken über einem Berg'], ARRAY['Zum Treffen von Geistern', 'Zum Durchdringen von Illusionen', 'Zum Verschwinden im Nebel'], ARRAY['mist sword', 'ethereal blade', 'fog weapon', 'ghostly sword', 'spirit magic'], 0.8, 1.0, 0.9, 0.6, 0.3, 0.7, 0.3),

('artifact_035', 'Berghammer', 'Mountain Hammer', 'Ein robuster Hammer aus Stein', 'A sturdy hammer made of stone', 'weapon', 'common', 'Zerstörung von Hindernissen', '⛏️', ARRAY['In einer Bergmine', 'Bei einem Steinmetz', 'Unter einem Felsvorsprung'], ARRAY['Zum Zerbrechen von Steinen', 'Zum Bauen von Wegen', 'Zum Öffnen von Höhleneingängen'], ARRAY['stone hammer', 'mining tool', 'mountain pickaxe', 'rock breaker', 'sturdy tool'], 0.7, 0.5, 0.4, 0.8, 0.4, 0.6, 0.5),

('artifact_058', 'Lichtschwert', 'Light Sword', 'Ein Schwert aus reinem Licht', 'A sword made of pure light', 'weapon', 'legendary', 'Kampf gegen Dunkelheit', '⚔️💡', ARRAY['Im Tempel des Lichts', 'Aus einem Sonnenstrahl geformt', 'Als Geschenk eines Lichtwesens'], ARRAY['Zum Vertreiben von Dunkelheit', 'Zum Besiegen böser Schatten', 'Zum Erleuchten dunkler Orte'], ARRAY['light sword', 'radiant blade', 'holy weapon', 'glowing sword', 'pure light'], 0.9, 1.0, 0.7, 0.4, 0.6, 1.0, 0.4),

('artifact_067', 'Blitz-Stab', 'Lightning Staff', 'Ein Stab, der Blitz beherrscht', 'A staff that commands lightning', 'weapon', 'legendary', 'Kraftvolle Angriffe', '⚡🪄', ARRAY['Während eines Gewitters', 'Im Turm eines Zauberers', 'Von einem Elementargeist'], ARRAY['Zum Rufen von Blitzen', 'Zum Aufladen magischer Geräte', 'Zum Besiegen großer Feinde'], ARRAY['lightning staff', 'storm magic', 'electric power', 'thunder rod', 'elemental weapon'], 0.9, 1.0, 0.5, 0.6, 0.3, 0.9, 0.4),

('artifact_089', 'Gerechtigkeitsklinge', 'Justice Blade', 'Ein Schwert, das Gerechtigkeit bringt', 'A sword that brings justice', 'weapon', 'legendary', 'Kampf gegen Ungerechtigkeit', '⚔️⚖️', ARRAY['Im Gericht eines alten Königs', 'Als Belohnung für eine gute Tat', 'In den Händen einer Statue'], ARRAY['Zum Beschützen der Schwachen', 'Zum Aufdecken von Lügen', 'Zum Wiederherstellen von Fairness'], ARRAY['justice sword', 'balance blade', 'righteous weapon', 'golden sword', 'fairness symbol'], 0.8, 0.9, 0.7, 0.3, 0.7, 1.0, 0.6),

-- MAGIC (11-30)
('artifact_003', 'Zeitkristall', 'Time Crystal', 'Ein funkelnder Kristall, der Zeit verlangsamen kann', 'A sparkling crystal that can slow down time', 'magic', 'legendary', 'Entkommen aus einer Falle', '⏰✨', ARRAY['In einer uralten Ruine', 'Im Herzen eines Berges', 'Bei einer weisen Zauberin'], ARRAY['Zum Verlangsamen der Zeit', 'Zum nochmaligen Versuch bei Fehlern', 'Zum Nachdenken in Gefahrensituationen'], ARRAY['time crystal', 'hourglass gem', 'temporal magic', 'glowing crystal', 'frozen moment'], 0.8, 1.0, 0.9, 0.3, 0.4, 0.7, 0.6),

('artifact_008', 'Kristallkugel', 'Crystal Ball', 'Eine glühende Kugel, die Zukunft zeigt', 'A glowing orb that shows the future', 'magic', 'legendary', 'Vision der Zukunft', '🔮✨', ARRAY['Bei einer Wahrsagerin', 'In einem magischen Laden', 'In einer versteckten Bibliothek'], ARRAY['Zum Sehen der Zukunft', 'Zum Finden verlorener Dinge', 'Zum Verstehen von Rätseln'], ARRAY['crystal ball', 'fortune sphere', 'magical orb', 'mystic vision', 'glowing prophecy'], 0.6, 1.0, 1.0, 0.3, 0.5, 0.5, 0.8),

('artifact_010', 'Heilstein', 'Healing Stone', 'Ein warmer Stein, der Wunden heilt', 'A warm stone that heals wounds', 'magic', 'common', 'Rettung aus kritischer Lage', '💎💚', ARRAY['Am Ufer eines heiligen Flusses', 'In einem alten Tempel', 'Von einem freundlichen Heiler'], ARRAY['Zum Heilen kleiner Verletzungen', 'Zum Lindern von Schmerzen', 'Zum Stärken von Freunden'], ARRAY['healing stone', 'green crystal', 'medical gem', 'warm glow', 'restoration magic'], 0.6, 0.8, 0.4, 0.7, 0.8, 0.5, 0.5),

('artifact_013', 'Zauberstab', 'Magic Wand', 'Ein Stab voller magischer Kraft', 'A wand full of magical power', 'magic', 'rare', 'Ausführung von Zaubersprüchen', '✨🪄', ARRAY['In einem Zauberladen', 'Als Geschenk eines Zauberers', 'In einem hohlen Baum'], ARRAY['Zum Wirken einfacher Zauber', 'Zum Bewegen kleiner Objekte', 'Zum Erzeugen von Funken'], ARRAY['magic wand', 'wizard staff', 'sparkle stick', 'enchanted wood', 'magical tool'], 0.7, 1.0, 0.6, 0.5, 0.5, 0.5, 0.7),

('artifact_014', 'Feuerstein', 'Fire Stone', 'Ein Stein, der Feuer erschafft', 'A stone that creates fire', 'magic', 'common', 'Erzeugen von Wärme oder Licht', '🔥💎', ARRAY['In einem Vulkan', 'Bei einem Schmied', 'In einer heißen Quelle'], ARRAY['Zum Entzünden von Lagerfeuern', 'Zum Wärmen in der Kälte', 'Zum Vertreiben wilder Tiere'], ARRAY['fire stone', 'flame gem', 'ember crystal', 'warm rock', 'burning magic'], 0.8, 0.8, 0.4, 0.6, 0.5, 0.6, 0.4),

('artifact_016', 'Mondstaub', 'Moon Dust', 'Leuchtender Staub vom Mond', 'Glowing dust from the moon', 'magic', 'rare', 'Magische Effekte in der Nacht', '✨🌙', ARRAY['In einer Vollmondnacht', 'Von einem Sternenforscher', 'Auf einem hohen Turm'], ARRAY['Zum Leuchten im Dunkeln', 'Zum Verzaubern von Gegenständen', 'Zum Beruhigen von Alpträumen'], ARRAY['moon dust', 'lunar powder', 'starlight sparkle', 'night magic', 'silver shimmer'], 0.6, 1.0, 0.8, 0.7, 0.6, 0.4, 0.6),

('artifact_018', 'Sprechende Münze', 'Talking Coin', 'Eine Münze, die Ratschläge gibt', 'A coin that gives advice', 'magic', 'rare', 'Hilfreiche Ratschläge', '💰💬', ARRAY['In einer alten Schatzkiste', 'Von einem weisen Händler', 'Am Grund eines Wunschbrunnens'], ARRAY['Zum Treffen schwieriger Entscheidungen', 'Zum Finden des richtigen Weges', 'Zum Verstehen von Problemen'], ARRAY['talking coin', 'wisdom token', 'golden advice', 'magical currency', 'speaking artifact'], 0.6, 0.8, 0.7, 0.3, 0.7, 0.5, 0.9),

('artifact_020', 'Teleportations-Amulett', 'Teleportation Amulet', 'Ein Amulett, das dich überallhin teleportiert', 'An amulet that teleports you anywhere', 'magic', 'legendary', 'Schnelle Flucht oder Bewegung', '💫📿', ARRAY['In einem vergessenen Tempel', 'Als Belohnung einer Quest', 'Von einem mächtigen Magier'], ARRAY['Zum schnellen Reisen', 'Zum Entkommen aus Gefahr', 'Zum Retten von Freunden'], ARRAY['teleport amulet', 'portal pendant', 'travel magic', 'dimensional jewelry', 'instant transport'], 0.9, 1.0, 0.7, 0.3, 0.5, 0.8, 0.4),

('artifact_024', 'Spiegel der Wahrheit', 'Mirror of Truth', 'Ein Spiegel, der Verborgenes zeigt', 'A mirror that reveals what is hidden', 'magic', 'rare', 'Erkennung von Illusionen', '🪞✨', ARRAY['In einem verzauberten Schloss', 'Bei einer alten Hexe', 'In einem magischen Laden'], ARRAY['Zum Sehen durch Verkleidungen', 'Zum Erkennen von Lügen', 'Zum Finden versteckter Türen'], ARRAY['truth mirror', 'revealing glass', 'illusion breaker', 'magical reflection', 'honest surface'], 0.6, 0.9, 1.0, 0.3, 0.6, 0.5, 0.8),

('artifact_026', 'Phönix-Feder', 'Phoenix Feather', 'Eine Feder eines Phönix, die Wiedergeburt bringt', 'A phoenix feather that brings rebirth', 'magic', 'legendary', 'Wiederbelebung oder Heilung', '🔥🪶', ARRAY['Im Nest eines Phönix', 'Nach einem großen Brand', 'Von einem legendären Vogel'], ARRAY['Zum Heilen schwerer Wunden', 'Zum Wiederherstellen von Hoffnung', 'Zum Entfachen neuer Kraft'], ARRAY['phoenix feather', 'rebirth plume', 'fire bird feather', 'golden red feather', 'renewal magic'], 0.8, 1.0, 0.5, 0.6, 0.7, 0.9, 0.5),

('artifact_031', 'Wissens-Stein', 'Knowledge Stone', 'Ein Stein voller altem Wissen', 'A stone full of ancient knowledge', 'magic', 'rare', 'Zugang zu vergessener Information', '📚💎', ARRAY['In einer alten Bibliothek', 'Bei einem Gelehrten', 'In den Ruinen einer Schule'], ARRAY['Zum Lernen neuer Dinge', 'Zum Lösen von Rätseln', 'Zum Verstehen alter Sprachen'], ARRAY['knowledge stone', 'wisdom gem', 'learning crystal', 'ancient memory', 'educational artifact'], 0.5, 0.7, 0.8, 0.3, 0.5, 0.4, 1.0),

('artifact_033', 'Liebesstein', 'Love Stone', 'Ein Stein, der Liebe anzieht', 'A stone that attracts love', 'magic', 'rare', 'Verbindung zu wichtigen Personen', '💕💎', ARRAY['An einem romantischen Ort', 'Von einer freundlichen Fee', 'In einem Blumengarten'], ARRAY['Zum Stärken von Freundschaften', 'Zum Finden verlorener Freunde', 'Zum Heilen gebrochener Herzen'], ARRAY['love stone', 'heart crystal', 'friendship gem', 'pink magic', 'emotional bond'], 0.4, 0.8, 0.4, 0.5, 1.0, 0.4, 0.4),

('artifact_038', 'Magiekompass', 'Magic Compass', 'Ein Kompass, der zu Magie führt', 'A compass that leads to magic', 'magic', 'rare', 'Finden von magischen Orten', '🧭✨', ARRAY['Bei einem alten Zauberer', 'In einem magischen Laden', 'Nach Bestehen einer Prüfung'], ARRAY['Zum Finden magischer Orte', 'Zum Aufspüren von Zauberei', 'Zum Entdecken versteckter Magie'], ARRAY['magic compass', 'enchanted direction', 'mystic navigation', 'spell finder', 'magical guide'], 0.8, 1.0, 0.9, 0.5, 0.4, 0.6, 0.7),

('artifact_042', 'Hoffnungs-Diamant', 'Hope Diamond', 'Ein leuchtender Diamant, der Hoffnung bringt', 'A glowing diamond that brings hope', 'magic', 'legendary', 'Überwindung der Hoffnungslosigkeit', '💎✨', ARRAY['Tief in einer Höhle', 'Als Geschenk eines Engels', 'Im Herzen eines Regenbogens'], ARRAY['Zum Wiedergewinnen von Mut', 'Zum Trösten trauriger Herzen', 'Zum Erleuchten dunkler Zeiten'], ARRAY['hope diamond', 'bright gem', 'courage crystal', 'light bearer', 'inspiration stone'], 0.7, 0.9, 0.5, 0.4, 0.8, 1.0, 0.5),

('artifact_043', 'Seelenfeder', 'Soul Feather', 'Eine Feder, die Seelen berührt', 'A feather that touches souls', 'magic', 'rare', 'Kommunikation mit Geistern', '🪶👻', ARRAY['An einem heiligen Ort', 'Von einem Geistervogel', 'Bei Vollmond'], ARRAY['Zum Sprechen mit Ahnen', 'Zum Verstehen von Gefühlen', 'Zum Beruhigen unruhiger Geister'], ARRAY['soul feather', 'spirit plume', 'ghostly quill', 'ethereal feather', 'emotional connector'], 0.5, 0.9, 0.9, 0.4, 0.7, 0.5, 0.6),

('artifact_045', 'Runenstein', 'Rune Stone', 'Ein Stein voller alter Runen', 'A stone full of ancient runes', 'magic', 'rare', 'Entzifferung von alten Texten', '🪨✨', ARRAY['In einer alten Ruine', 'Bei einem Archäologen', 'Unter einem Steinkreis'], ARRAY['Zum Lesen alter Schriften', 'Zum Aktivieren von Portalen', 'Zum Verstehen von Geheimnissen'], ARRAY['rune stone', 'ancient writing', 'magical symbols', 'norse magic', 'carved rock'], 0.7, 0.9, 0.9, 0.4, 0.3, 0.5, 0.9),

('artifact_048', 'Gedanken-Amulett', 'Mind Amulet', 'Ein Amulett, das Gedanken liest', 'An amulet that reads thoughts', 'magic', 'rare', 'Verstehen versteckter Wahrheiten', '🧠💫', ARRAY['Bei einem Wahrsager', 'In einem Geheimversteck', 'Als Belohnung für Ehrlichkeit'], ARRAY['Zum Verstehen von Absichten', 'Zum Erkennen von Gefühlen', 'Zum Kommunizieren ohne Worte'], ARRAY['mind amulet', 'thought reader', 'telepathy pendant', 'mental magic', 'brain symbol'], 0.5, 0.9, 1.0, 0.2, 0.7, 0.4, 0.7),

('artifact_049', 'Heilkristall', 'Healing Crystal', 'Ein Kristall voller Heilkraft', 'A crystal full of healing power', 'magic', 'rare', 'Heilung schwerer Verletzungen', '💎💚', ARRAY['In einer heiligen Quelle', 'Bei einem Heiler', 'In einem Krankenhaus der Feen'], ARRAY['Zum Heilen von Wunden', 'Zum Stärken des Körpers', 'Zum Lindern von Krankheiten'], ARRAY['healing crystal', 'cure gem', 'medical stone', 'green glow', 'restoration power'], 0.6, 0.8, 0.4, 0.7, 0.7, 0.5, 0.6),

('artifact_050', 'Windeamulett', 'Wind Amulet', 'Ein Amulett, das Wind kontrolliert', 'An amulet that controls wind', 'magic', 'rare', 'Kontrolle über Wetter', '💨📿', ARRAY['Auf einem hohen Berg', 'Von einem Luftgeist', 'Im Auge eines Sturms'], ARRAY['Zum Rufen von Brisen', 'Zum Wegpusten von Nebel', 'Zum schnelleren Reisen'], ARRAY['wind amulet', 'air pendant', 'breeze controller', 'storm magic', 'elemental jewelry'], 0.8, 0.9, 0.5, 0.9, 0.4, 0.6, 0.4),

('artifact_051', 'Drachenauge', 'Dragon Eye', 'Das Auge eines Drachen mit Seherkraft', 'A dragon eye with seer power', 'magic', 'legendary', 'Sicht über große Entfernungen', '🐉👁️', ARRAY['In einer Drachenhöhle', 'Von einem alten Drachen', 'In einem Vulkan'], ARRAY['Zum Sehen weit entfernter Orte', 'Zum Erkennen von Gefahren', 'Zum Finden versteckter Schätze'], ARRAY['dragon eye', 'seer orb', 'mythical vision', 'all-seeing eye', 'ancient magic'], 0.9, 1.0, 0.9, 0.4, 0.3, 0.7, 0.6),

-- Continue with more artifacts...

('artifact_052', 'Fluchbrecher', 'Curse Breaker', 'Ein Artefakt, das jeden Fluch bricht', 'An artifact that breaks any curse', 'magic', 'legendary', 'Befreiung von Flüchen', '🔓✨', ARRAY['In einem verzauberten Turm', 'Bei einer weisen Hexe', 'Am Ende einer langen Suche'], ARRAY['Zum Befreien von Verzauberungen', 'Zum Heilen verfluchter Freunde', 'Zum Öffnen magischer Schlösser'], ARRAY['curse breaker', 'spell ender', 'magic dispeller', 'freedom artifact', 'liberation tool'], 0.7, 1.0, 0.8, 0.3, 0.6, 0.7, 0.5),

('artifact_061', 'Geisterflasche', 'Spirit Bottle', 'Eine Flasche, die Geister enthält', 'A bottle that contains spirits', 'magic', 'rare', 'Kommunikation mit Übernatürlichem', '👻🧴', ARRAY['In einem alten Keller', 'Bei einem Geisterjäger', 'Auf einem Friedhof'], ARRAY['Zum Sprechen mit Geistern', 'Zum Bitten um Hilfe', 'Zum Verstehen der Vergangenheit'], ARRAY['spirit bottle', 'ghost container', 'haunted vessel', 'spectral jar', 'supernatural holder'], 0.6, 0.9, 1.0, 0.3, 0.4, 0.5, 0.6),

('artifact_062', 'Naturstein', 'Nature Stone', 'Ein Stein voller Naturmagie', 'A stone full of nature magic', 'magic', 'common', 'Kommunikation mit Natur', '🌿💎', ARRAY['Im Herzen eines Waldes', 'Bei einer Waldfee', 'An einem heiligen Baum'], ARRAY['Zum Sprechen mit Pflanzen', 'Zum Rufen von Tieren', 'Zum Finden des Weges in der Natur'], ARRAY['nature stone', 'forest gem', 'plant magic', 'green crystal', 'earth power'], 0.6, 0.8, 0.4, 1.0, 0.6, 0.4, 0.6),

('artifact_063', 'Wasserkristall', 'Water Crystal', 'Ein Kristall, der Wasser kontrolliert', 'A crystal that controls water', 'magic', 'rare', 'Kontrolle über Wasser', '💧✨', ARRAY['Am Grund eines Sees', 'Bei einer Wassernixe', 'Nach einem großen Regen'], ARRAY['Zum Formen von Wasser', 'Zum Atmen unter Wasser', 'Zum Löschen von Feuer'], ARRAY['water crystal', 'aqua gem', 'ocean magic', 'blue power', 'liquid control'], 0.7, 0.9, 0.5, 0.9, 0.4, 0.5, 0.5),

('artifact_064', 'Erdenamulett', 'Earth Amulet', 'Ein Amulett der Erde', 'An amulet of the earth', 'magic', 'rare', 'Stabilität und Schutz', '🌍📿', ARRAY['Tief unter der Erde', 'Bei einem Berggeist', 'In einer Höhle'], ARRAY['Zum Stabilisieren des Bodens', 'Zum Schutz vor Erdbeben', 'Zum Finden von Mineralien'], ARRAY['earth amulet', 'ground pendant', 'stability magic', 'rock jewelry', 'solid protection'], 0.7, 0.8, 0.5, 0.9, 0.4, 0.6, 0.5),

('artifact_068', 'Harmonieflöte', 'Harmony Flute', 'Eine Flöte, die Harmonie bringt', 'A flute that brings harmony', 'magic', 'rare', 'Beruhigung von Konflikten', '🎵✨', ARRAY['Bei einem Barden', 'In einem Musiktempel', 'Von einer singenden Fee'], ARRAY['Zum Beruhigen aufgeregter Gemüter', 'Zum Einschläfern wilder Tiere', 'Zum Schaffen von Frieden'], ARRAY['harmony flute', 'peace music', 'calming instrument', 'magical melody', 'soothing sound'], 0.5, 0.8, 0.4, 0.6, 1.0, 0.4, 0.5),

('artifact_070', 'Liebeslicht', 'Love Light', 'Ein Licht voller Liebe', 'A light full of love', 'magic', 'rare', 'Heilung von Herzwunden', '💕💡', ARRAY['An einem romantischen Ort', 'Von Amor persönlich', 'Im Herzenstempel'], ARRAY['Zum Heilen gebrochener Herzen', 'Zum Stärken von Freundschaften', 'Zum Verbreiten von Wärme'], ARRAY['love light', 'heart glow', 'affection beam', 'caring radiance', 'emotional warmth'], 0.4, 0.8, 0.3, 0.4, 1.0, 0.4, 0.4),

('artifact_071', 'Angstbannstab', 'Fear Banisher', 'Ein Stab, der Angst vertreibt', 'A staff that banishes fear', 'magic', 'rare', 'Überwindung von Angst', '😨❌', ARRAY['Bei einem mutigen Helden', 'Im Tempel des Mutes', 'Nach einer Mutprobe'], ARRAY['Zum Vertreiben von Ängsten', 'Zum Stärken des Selbstvertrauens', 'Zum Beruhigen in Schreckensmomenten'], ARRAY['fear banisher', 'courage staff', 'bravery wand', 'anxiety remover', 'confidence boost'], 0.6, 0.8, 0.5, 0.3, 0.6, 1.0, 0.5),

('artifact_072', 'Zornbrecher', 'Anger Breaker', 'Ein Artefakt gegen Wut', 'An artifact against anger', 'magic', 'rare', 'Beruhigung wilder Kräfte', '😠❌', ARRAY['Bei einem Friedensstifter', 'Im Tempel der Ruhe', 'Von einem weisen Mönch'], ARRAY['Zum Beruhigen wütender Wesen', 'Zum Finden innerer Ruhe', 'Zum Schlichten von Streits'], ARRAY['anger breaker', 'calm stone', 'peace maker', 'serenity artifact', 'rage stopper'], 0.4, 0.7, 0.4, 0.4, 0.9, 0.6, 0.5),

('artifact_073', 'Trauertrost', 'Grief Comfort', 'Ein Artefakt zur Überwindung von Trauer', 'An artifact for overcoming grief', 'magic', 'rare', 'Heilung emotionaler Schmerzen', '😢💚', ARRAY['Bei einem Trauerbegleiter', 'An einem heiligen Gedenkort', 'Von einem mitfühlenden Engel'], ARRAY['Zum Trösten bei Verlust', 'Zum Finden von Akzeptanz', 'Zum Erinnern an schöne Momente'], ARRAY['grief comfort', 'sorrow healer', 'mourning aid', 'emotional balm', 'healing heart'], 0.3, 0.7, 0.4, 0.4, 0.9, 0.5, 0.5),

('artifact_074', 'Freudenkern', 'Joy Core', 'Das Herz der Freude', 'The heart of joy', 'magic', 'rare', 'Rückgewinnung von Glück', '😊💛', ARRAY['An einem fröhlichen Fest', 'Von einem lachenden Kind', 'Im Herzen eines Regenbogens'], ARRAY['Zum Verbreiten von Freude', 'Zum Aufheitern trauriger Herzen', 'Zum Feiern kleiner Siege'], ARRAY['joy core', 'happiness heart', 'cheerful center', 'smile stone', 'bright emotion'], 0.5, 0.7, 0.3, 0.5, 0.9, 0.6, 0.4),

('artifact_075', 'Hoffnungsfaden', 'Hope Thread', 'Ein Faden, der Hoffnung spinnt', 'A thread that spins hope', 'magic', 'rare', 'Verbindung zu besserer Zukunft', '🧵✨', ARRAY['Bei einer alten Weberin', 'Im Schicksalstempel', 'Von den Nornen gesponnen'], ARRAY['Zum Verbinden mit der Zukunft', 'Zum Finden neuer Wege', 'Zum Knüpfen von Schicksalen'], ARRAY['hope thread', 'destiny string', 'future fiber', 'optimism line', 'connection cord'], 0.6, 0.9, 0.6, 0.3, 0.7, 0.8, 0.5),

('artifact_081', 'Zauberkreis', 'Magic Circle', 'Ein magischer Kreis zum Zaubern', 'A magical circle for spellcasting', 'magic', 'rare', 'Fokus für Zauberkraft', '⭕✨', ARRAY['In einer Zauberschule', 'Bei einem Meistermagier', 'In einem alten Ritualbuch'], ARRAY['Zum Verstärken von Zaubersprüchen', 'Zum Schützen vor dunkler Magie', 'Zum Konzentrieren magischer Energie'], ARRAY['magic circle', 'spell ring', 'enchantment ring', 'ritual pattern', 'power focus'], 0.6, 1.0, 0.7, 0.3, 0.4, 0.5, 0.8),

('artifact_082', 'Seelenspiegel', 'Soul Mirror', 'Ein Spiegel der Seele', 'A mirror of the soul', 'magic', 'legendary', 'Erkennung von innerem Selbst', '🪞👻', ARRAY['In einem philosophischen Tempel', 'Bei einem weisen Guru', 'Nach tiefer Meditation'], ARRAY['Zum Erkennen der wahren Natur', 'Zum Verstehen eigener Gefühle', 'Zum Finden des inneren Friedens'], ARRAY['soul mirror', 'inner reflection', 'true self glass', 'emotional mirror', 'heart viewer'], 0.4, 0.9, 0.7, 0.3, 0.7, 0.6, 0.8),

('artifact_083', 'Glücksmünze', 'Lucky Coin', 'Eine Münze aus purem Glück', 'A coin made of pure luck', 'magic', 'rare', 'Bringung von Glück', '💰✨', ARRAY['In einem Wunschbrunnen', 'Von einem Kobold', 'Am Ende eines Regenbogens'], ARRAY['Zum Bringen von Glück', 'Zum Gewinnen bei Spielen', 'Zum Abwenden von Pech'], ARRAY['lucky coin', 'fortune token', 'prosperity piece', 'chance charm', 'gambling luck'], 0.7, 0.7, 0.5, 0.3, 0.6, 0.5, 0.4),

('artifact_084', 'Schicksalsfaden', 'Fate Thread', 'Der Faden des Schicksals selbst', 'The thread of fate itself', 'magic', 'legendary', 'Kontrolle über das Schicksal', '🧵📿', ARRAY['Bei den Schicksalsgöttinnen', 'Im Tempel der Zeit', 'Am Ende aller Wege'], ARRAY['Zum Ändern kleiner Schicksale', 'Zum Verbinden von Lebenslinien', 'Zum Verstehen des großen Plans'], ARRAY['fate thread', 'destiny line', 'life string', 'cosmic connection', 'karmic cord'], 0.7, 1.0, 0.8, 0.3, 0.6, 0.7, 0.7),

('artifact_085', 'Wahrheitsstein', 'Truth Stone', 'Ein Stein, der Wahrheit zeigt', 'A stone that shows truth', 'magic', 'rare', 'Enthüllung von Lügen', '🪨✨', ARRAY['Im Gerichtshof der Götter', 'Bei einem Richter', 'An einem heiligen Ort'], ARRAY['Zum Erkennen von Lügen', 'Zum Finden der Wahrheit', 'Zum Lösen von Rätseln'], ARRAY['truth stone', 'honesty rock', 'lie detector', 'verity gem', 'sincere crystal'], 0.5, 0.8, 1.0, 0.3, 0.6, 0.5, 0.7),

('artifact_086', 'Lügenbrecher', 'Lie Breaker', 'Ein Artefakt gegen Täuschung', 'An artifact against deception', 'magic', 'rare', 'Schutz vor Betrug', '🤥❌', ARRAY['Bei einem Detektiv', 'Im Haus der Ehrlichkeit', 'Von einem Wahrheitssucher'], ARRAY['Zum Durchschauen von Tricks', 'Zum Schützen vor Betrügern', 'Zum Finden von Spionen'], ARRAY['lie breaker', 'deception detector', 'honesty shield', 'truth enforcer', 'fraud finder'], 0.5, 0.7, 1.0, 0.2, 0.5, 0.5, 0.6),

('artifact_090', 'Mitgefühlsherz', 'Compassion Heart', 'Ein Herz voller Mitgefühl', 'A heart full of compassion', 'magic', 'rare', 'Verständnis für andere', '❤️✨', ARRAY['Bei einer gütigen Heilerin', 'Im Tempel der Liebe', 'Von einem selbstlosen Helden'], ARRAY['Zum Verstehen anderer Gefühle', 'Zum Helfen in Not', 'Zum Finden von Empathie'], ARRAY['compassion heart', 'empathy core', 'understanding gem', 'feeling center', 'caring stone'], 0.4, 0.7, 0.4, 0.4, 1.0, 0.5, 0.6),

('artifact_091', 'Verständnisohr', 'Understanding Ear', 'Ein Ohr, das alles versteht', 'An ear that understands everything', 'magic', 'rare', 'Verstehen von versteckten Wahrheiten', '👂✨', ARRAY['Bei einem Weisen', 'Im Tempel des Zuhörens', 'Von einem guten Freund'], ARRAY['Zum Verstehen fremder Sprachen', 'Zum Hören versteckter Bedeutungen', 'Zum Lauschen auf die Natur'], ARRAY['understanding ear', 'listening device', 'comprehension tool', 'language helper', 'meaning finder'], 0.4, 0.7, 0.7, 0.5, 0.8, 0.4, 0.9),

('artifact_092', 'Freundschaftskristall', 'Friendship Crystal', 'Ein Kristall der Freundschaft', 'A crystal of friendship', 'magic', 'rare', 'Verbindung mit Freunden', '💎💜', ARRAY['Bei einem treuen Freund', 'Im Haus der Freundschaft', 'Nach einer gemeinsamen Reise'], ARRAY['Zum Stärken von Freundschaften', 'Zum Finden von Freunden in Not', 'Zum Teilen von Gefühlen über Distanz'], ARRAY['friendship crystal', 'buddy gem', 'companion stone', 'bond jewelry', 'trust artifact'], 0.5, 0.7, 0.4, 0.4, 1.0, 0.5, 0.4),

('artifact_095', 'Traumfänger', 'Dream Catcher', 'Ein Netz für schöne Träume', 'A net for beautiful dreams', 'magic', 'rare', 'Schutz guter Träume', '🕸️💭', ARRAY['Bei einem Traumweber', 'In einer Sternennacht', 'Von einem schlafenden Einhorn'], ARRAY['Zum Fangen schöner Träume', 'Zum Erinnern an Träume', 'Zum Reisen in Traumwelten'], ARRAY['dream catcher', 'sleep net', 'vision trap', 'nightmare filter', 'slumber guardian'], 0.5, 0.9, 0.6, 0.5, 0.6, 0.4, 0.5),

('artifact_096', 'Albtraumvertreiber', 'Nightmare Banisher', 'Ein Artefakt gegen Albträume', 'An artifact against nightmares', 'magic', 'rare', 'Schutz vor Alpträumen', '😴❌', ARRAY['Bei einem Traumheiler', 'Im Land der Träume', 'Nach dem Besiegen eines Albtraums'], ARRAY['Zum Vertreiben böser Träume', 'Zum Beruhigen vor dem Schlafen', 'Zum Schützen schlafender Freunde'], ARRAY['nightmare banisher', 'bad dream remover', 'sleep protector', 'peace bringer', 'calm guardian'], 0.4, 0.8, 0.5, 0.4, 0.7, 0.7, 0.4),

('artifact_100', 'Ewigkeitsstein', 'Eternity Stone', 'Ein Stein der Ewigkeit', 'A stone of eternity', 'magic', 'legendary', 'Zeitlose Existenz', '💎⏰', ARRAY['Am Anfang der Zeit', 'Bei einem unsterblichen Wesen', 'Im Zentrum des Universums'], ARRAY['Zum Verstehen der Unendlichkeit', 'Zum Bewahren wichtiger Momente', 'Zum Überdauern schwieriger Zeiten'], ARRAY['eternity stone', 'infinity gem', 'timeless crystal', 'forever rock', 'perpetual magic'], 0.6, 1.0, 0.7, 0.4, 0.5, 0.6, 0.8),

-- TOOLS (30-45)
('artifact_005', 'Kompass der Wahrheit', 'Compass of Truth', 'Ein Kompass, der immer zum Weg der Wahrheit zeigt', 'A compass that always points to the path of truth', 'tool', 'rare', 'Navigation in verwirrender Situation', '🧭✨', ARRAY['Bei einem alten Seefahrer', 'In einer vergessenen Bibliothek', 'Von einem weisen Wanderer'], ARRAY['Zum Finden des richtigen Weges', 'Zum Erkennen von Täuschungen', 'Zum Navigieren in Labyrinthen'], ARRAY['truth compass', 'golden compass', 'navigation tool', 'direction finder', 'path guide'], 0.9, 0.8, 1.0, 0.5, 0.5, 0.7, 0.6),

('artifact_012', 'Rucksack des Unendlichen', 'Bag of Holding', 'Ein Rucksack, der endlos viel Platz hat', 'A backpack with endless space', 'tool', 'rare', 'Transport von wichtigen Dingen', '🎒✨', ARRAY['Bei einem reisenden Händler', 'In einem Zauberladen', 'Als Belohnung für Hilfsbereitschaft'], ARRAY['Zum Tragen vieler Dinge', 'Zum Verstecken von Schätzen', 'Zum Mitbringen von Vorräten'], ARRAY['endless bag', 'magic backpack', 'infinite storage', 'dimension pocket', 'carrying tool'], 0.9, 0.9, 0.5, 0.6, 0.5, 0.5, 0.4),

('artifact_015', 'Eisenkette', 'Iron Chain', 'Eine stabile Kette aus purem Eisen', 'A sturdy chain of pure iron', 'tool', 'common', 'Befestigung oder Klettern', '⛓️', ARRAY['Bei einem Schmied', 'In einer alten Festung', 'An einem Schiffshafen'], ARRAY['Zum Klettern', 'Zum Sichern von Lasten', 'Zum Fesseln von Gefahren'], ARRAY['iron chain', 'metal links', 'sturdy rope', 'climbing tool', 'binding device'], 0.7, 0.4, 0.5, 0.4, 0.4, 0.6, 0.4),

('artifact_022', 'Kompass des Waldes', 'Forest Compass', 'Ein Kompass, der durch Wälder führt', 'A compass that guides through forests', 'tool', 'common', 'Navigation in der Natur', '🧭🌲', ARRAY['Bei einem Förster', 'Im Herzen eines Waldes', 'Von einem Waldgeist'], ARRAY['Zum Finden des Weges im Wald', 'Zum Entdecken von Lichtungen', 'Zum Vermeiden von Gefahren'], ARRAY['forest compass', 'nature guide', 'woodland navigation', 'tree finder', 'path marker'], 0.7, 0.6, 0.5, 1.0, 0.5, 0.5, 0.5),

('artifact_023', 'Universalschlüssel', 'Universal Key', 'Ein Schlüssel, der jede Tür öffnet', 'A key that opens any door', 'tool', 'rare', 'Zugang zu verschlossenen Orten', '🔑✨', ARRAY['Bei einem Meisterdieb', 'In einem Schloss', 'Von einem Schlosser'], ARRAY['Zum Öffnen verschlossener Türen', 'Zum Betreten geheimer Räume', 'Zum Befreien Gefangener'], ARRAY['universal key', 'master key', 'all-access', 'golden key', 'lock opener'], 0.8, 0.7, 1.0, 0.3, 0.4, 0.6, 0.5),

('artifact_025', 'Springseil des Glücks', 'Lucky Jump Rope', 'Ein Seil, mit dem man immer hoch springt', 'A rope that always makes you jump high', 'tool', 'common', 'Überwindung von Hindernissen', '🪢✨', ARRAY['Auf einem Spielplatz', 'Bei einem Zirkusartisten', 'Von einem sportlichen Kind'], ARRAY['Zum Überspringen von Hindernissen', 'Zum Erreichen hoher Orte', 'Zum Spielen und Spaß haben'], ARRAY['jump rope', 'skip cord', 'bouncing tool', 'playground item', 'athletic equipment'], 0.6, 0.5, 0.3, 0.5, 0.7, 0.6, 0.5),

('artifact_030', 'Kristalllinse', 'Crystal Lens', 'Eine Linse, die unsichtbare Dinge zeigt', 'A lens that shows invisible things', 'tool', 'rare', 'Erkennung von Geheimnissen', '🔍✨', ARRAY['Bei einem Erfinder', 'In einem Labor', 'Von einem Forscher'], ARRAY['Zum Sehen versteckter Nachrichten', 'Zum Entdecken unsichtbarer Wege', 'Zum Lesen alter Schriften'], ARRAY['crystal lens', 'magic magnifier', 'revealing glass', 'secret viewer', 'hidden detector'], 0.7, 0.8, 1.0, 0.4, 0.4, 0.5, 0.9),

('artifact_037', 'Leuchtflasche', 'Glow Bottle', 'Eine Flasche, die ewig leuchtet', 'A bottle that glows forever', 'tool', 'common', 'Licht in Dunkelheit', '🔦✨', ARRAY['Bei einem Glasmacher', 'In einer Glühwürmchenhöhle', 'Von einem freundlichen Geist'], ARRAY['Zum Erleuchten dunkler Orte', 'Zum Signalisieren von Freunden', 'Zum Vertreiben der Angst im Dunkeln'], ARRAY['glow bottle', 'light vessel', 'luminous jar', 'bright container', 'eternal lamp'], 0.6, 0.7, 0.6, 0.5, 0.5, 0.5, 0.4),

('artifact_044', 'Alchemiekolben', 'Alchemy Flask', 'Ein Glaskolben für Zauberkunst', 'A glass flask for magic arts', 'tool', 'rare', 'Herstellung von magischen Tränken', '🧪✨', ARRAY['In einem Alchemielabor', 'Bei einem Zaubertränke-Meister', 'In einer Hexenküche'], ARRAY['Zum Mischen von Tränken', 'Zum Aufbewahren magischer Flüssigkeiten', 'Zum Experimentieren mit Zutaten'], ARRAY['alchemy flask', 'potion bottle', 'magic container', 'brew vessel', 'experiment tool'], 0.5, 0.9, 0.6, 0.5, 0.3, 0.4, 0.9),

('artifact_076', 'Verlorenfinder', 'Lost Finder', 'Ein Kompass für Verlorenes', 'A compass for lost things', 'tool', 'rare', 'Finden von verlorenen Dingen', '🔍❤️', ARRAY['Bei einem Sucher', 'Im Fundamt der Feen', 'Von einem hilfsbereiten Geist'], ARRAY['Zum Finden verlorener Gegenstände', 'Zum Aufspüren vermisster Freunde', 'Zum Entdecken vergessener Schätze'], ARRAY['lost finder', 'search compass', 'missing detector', 'recovery tool', 'tracking device'], 0.7, 0.7, 0.9, 0.4, 0.7, 0.5, 0.5),

('artifact_077', 'Nachtbrille', 'Night Glasses', 'Eine Brille für Nachtsicht', 'Glasses for night vision', 'tool', 'rare', 'Sicht in Dunkelheit', '👓🌙', ARRAY['Bei einem Eulenzüchter', 'Im Nachtmarkt', 'Von einem Nachtwächter'], ARRAY['Zum Sehen im Dunkeln', 'Zum Entdecken nachtaktiver Wesen', 'Zum Navigieren bei Nacht'], ARRAY['night glasses', 'dark vision', 'nocturnal eyewear', 'shadow sight', 'moon spectacles'], 0.7, 0.7, 0.8, 0.6, 0.4, 0.6, 0.5),

('artifact_078', 'Tagfackel', 'Day Torch', 'Eine Fackel, die Dunkelheit vertreibt', 'A torch that banishes darkness', 'tool', 'common', 'Erschaffung von Licht', '🔥💡', ARRAY['Bei einem Wächter', 'Am Eingang einer Höhle', 'Von einem freundlichen Schmied'], ARRAY['Zum Erleuchten von Höhlen', 'Zum Vertreiben von Schatten', 'Zum Wärmen in der Kälte'], ARRAY['day torch', 'bright flame', 'light bringer', 'darkness banisher', 'warm fire'], 0.7, 0.6, 0.6, 0.5, 0.4, 0.6, 0.4),

('artifact_097', 'Abenteuerkompass', 'Adventure Compass', 'Ein Kompass zu Abenteuern', 'A compass to adventures', 'tool', 'rare', 'Finden neuer Wege', '🧭⭐', ARRAY['Bei einem erfahrenen Abenteurer', 'Am Start eines Pfades', 'Nach dem ersten Abenteuer'], ARRAY['Zum Finden spannender Orte', 'Zum Entdecken neuer Wege', 'Zum Starten von Abenteuern'], ARRAY['adventure compass', 'quest guide', 'journey finder', 'exploration tool', 'discovery device'], 1.0, 0.8, 0.7, 0.6, 0.5, 0.8, 0.5),

('artifact_098', 'Entdeckungslupe', 'Discovery Magnifier', 'Eine Lupe für Entdeckungen', 'A magnifying glass for discoveries', 'tool', 'common', 'Finden versteckter Details', '🔍', ARRAY['Bei einem Detektiv', 'In einem Wissenschaftslabor', 'Von einem neugierigen Forscher'], ARRAY['Zum Untersuchen kleiner Dinge', 'Zum Finden von Hinweisen', 'Zum Lesen winziger Schrift'], ARRAY['discovery magnifier', 'exploration lens', 'detail finder', 'clue seeker', 'research tool'], 0.6, 0.5, 1.0, 0.5, 0.4, 0.4, 0.9),

('artifact_099', 'Geheimnisschloss', 'Secret Lock', 'Ein Schloss für Geheimnisse', 'A lock for secrets', 'tool', 'rare', 'Schutz von Geheimnissen', '🔐✨', ARRAY['Bei einem Geheimnisbewahrer', 'Im Tresorraum einer Bank', 'Von einem vertrauenswürdigen Freund'], ARRAY['Zum Schützen wichtiger Dinge', 'Zum Verbergen von Schätzen', 'Zum Bewahren von Geheimnissen'], ARRAY['secret lock', 'mystery padlock', 'hidden keeper', 'treasure protector', 'safe guardian'], 0.5, 0.6, 0.9, 0.3, 0.6, 0.5, 0.5),

-- CLOTHING (45-55)
('artifact_002', 'Regenmantel', 'Rain Cloak', 'Ein weicher Mantel, der vor jedem Regen schützt', 'A soft cloak that protects from any rain', 'clothing', 'common', 'Schutz in gefährlichen Situationen', '🧥💧', ARRAY['Bei einem freundlichen Schneider', 'Im Kleidergeschäft eines Dorfes', 'Als Geschenk einer fürsorglichen Person'], ARRAY['Zum Trockenbleiben bei Regen', 'Zum Schutz vor Kälte', 'Zum Überstehen von Stürmen'], ARRAY['rain cloak', 'weather protection', 'waterproof coat', 'storm shield', 'dry keeper'], 0.7, 0.6, 0.4, 0.8, 0.5, 0.5, 0.3),

('artifact_009', 'Unsichtbarer Umhang', 'Invisibility Cloak', 'Ein Umhang, der den Träger unsichtbar macht', 'A cloak that makes the wearer invisible', 'clothing', 'legendary', 'Verstecken vor Feinden', '👻🧥', ARRAY['In einem vergessenen Schrank', 'Bei einem mächtigen Zauberer', 'Als Erbstück einer magischen Familie'], ARRAY['Zum Verstecken vor Gefahren', 'Zum Belauschen von Gesprächen', 'Zum Schleichen an Wachen vorbei'], ARRAY['invisibility cloak', 'stealth cape', 'hidden garment', 'vanishing cloth', 'phantom wear'], 0.8, 1.0, 0.9, 0.3, 0.3, 0.7, 0.4),

('artifact_036', 'Seidenschal', 'Silk Scarf', 'Ein wunderschöner Schal aus Seide', 'A beautiful scarf made of silk', 'clothing', 'common', 'Wärme und Trost in schwierigen Zeiten', '🧣✨', ARRAY['Bei einer Weberin', 'Im Laden eines Stoffhändlers', 'Als Geschenk eines Freundes'], ARRAY['Zum Wärmen bei Kälte', 'Als Verband bei Verletzungen', 'Als Zeichen der Freundschaft'], ARRAY['silk scarf', 'soft fabric', 'warm accessory', 'comfort cloth', 'gentle wrap'], 0.4, 0.5, 0.3, 0.4, 0.8, 0.4, 0.3),

('artifact_041', 'Schattencape', 'Shadow Cape', 'Ein Cape, das in Schatten schmilzt', 'A cape that melts into shadows', 'clothing', 'rare', 'Verstecken in der Dunkelheit', '🦇🧥', ARRAY['In einer dunklen Gasse', 'Bei einem Schattenmeister', 'In der Burg eines Vampirs'], ARRAY['Zum Verstecken im Dunkeln', 'Zum lautlosen Bewegen', 'Zum Entkommen aus Gefangenschaft'], ARRAY['shadow cape', 'dark cloak', 'stealth mantle', 'night garment', 'hidden wear'], 0.7, 0.9, 0.9, 0.3, 0.3, 0.6, 0.3),

('artifact_046', 'Sternenmantel', 'Star Mantle', 'Ein Mantel aus echten Sternen', 'A mantle made of real stars', 'clothing', 'legendary', 'Navigation und Orientierung', '⭐🧥', ARRAY['Am Sternenhimmel', 'Von einer Himmelskönigin', 'Nach dem Sammeln von Sternenlicht'], ARRAY['Zum Navigieren bei Nacht', 'Zum Leuchten im Dunkeln', 'Zum Beeindrucken von Wesen'], ARRAY['star mantle', 'celestial cloak', 'night sky wear', 'cosmic garment', 'stellar robe'], 0.7, 1.0, 0.6, 0.7, 0.4, 0.5, 0.7),

('artifact_056', 'Luftschuhe', 'Air Shoes', 'Schuhe, die über Luft gehen lassen', 'Shoes that let you walk on air', 'clothing', 'rare', 'Flucht oder schnelle Flucht', '👟☁️', ARRAY['Bei einem Wolkenweber', 'Im Himmelskönigreich', 'Von einem fliegenden Wesen'], ARRAY['Zum Schweben über Abgründe', 'Zum schnellen Laufen', 'Zum Erreichen hoher Orte'], ARRAY['air shoes', 'cloud walkers', 'sky boots', 'floating footwear', 'levitation sneakers'], 0.8, 0.9, 0.5, 0.6, 0.4, 0.7, 0.4),

('artifact_059', 'Schattenmaske', 'Shadow Mask', 'Eine Maske, die wahre Natur verbirgt', 'A mask that hides true nature', 'clothing', 'rare', 'Verkleidung für Missionen', '🎭🌑', ARRAY['Bei einem Maskenball', 'Von einem Spion', 'Im Theater der Geheimnisse'], ARRAY['Zum Verkleiden', 'Zum Täuschen von Feinden', 'Zum Schützen der Identität'], ARRAY['shadow mask', 'disguise face', 'hidden identity', 'secret cover', 'mystery mask'], 0.6, 0.7, 1.0, 0.2, 0.3, 0.5, 0.4),

-- BOOKS (55-60)
('artifact_004', 'Magisches Tagebuch', 'Magic Journal', 'Ein Buch, das Geheimnisse selbst aufschreibt', 'A book that writes secrets by itself', 'book', 'rare', 'Enthüllung von versteckten Wahrheiten', '📖✨', ARRAY['In einer alten Bibliothek', 'Bei einem geheimnisvollen Buchhändler', 'In einer versteckten Kammer'], ARRAY['Zum Aufdecken von Geheimnissen', 'Zum Aufschreiben wichtiger Ereignisse', 'Zum Kommunizieren über Distanz'], ARRAY['magic journal', 'enchanted book', 'self-writing diary', 'secret keeper', 'memory book'], 0.6, 0.9, 1.0, 0.3, 0.5, 0.4, 0.8),

('artifact_017', 'Buch der Geheimnisse', 'Book of Secrets', 'Ein Buch mit all den versteckten Wahrheiten', 'A book with all the hidden truths', 'book', 'legendary', 'Enthüllung großer Geheimnisse', '📖🔐', ARRAY['In einer verborgenen Bibliothek', 'Bei einem Wissensbewahrer', 'Am Ende einer langen Suche'], ARRAY['Zum Finden von Antworten', 'Zum Verstehen von Mysterien', 'Zum Lösen uralter Rätsel'], ARRAY['secrets book', 'knowledge tome', 'mystery text', 'hidden wisdom', 'truth pages'], 0.7, 0.9, 1.0, 0.3, 0.4, 0.5, 1.0),

('artifact_055', 'Magie-Notizbuch', 'Magic Notebook', 'Ein Notizbuch, das Zaubersprüche speichert', 'A notebook that stores spells', 'book', 'rare', 'Merken von Zaubersprüchen', '📓✨', ARRAY['In einer Zauberschule', 'Bei einem lernenden Magier', 'Im Arbeitszimmer eines Zauberers'], ARRAY['Zum Notieren von Zaubern', 'Zum schnellen Nachschlagen', 'Zum Teilen von Wissen'], ARRAY['magic notebook', 'spell journal', 'wizard notes', 'enchantment record', 'arcane diary'], 0.5, 0.9, 0.6, 0.3, 0.4, 0.4, 1.0),

('artifact_079', 'Märchenbuch', 'Fairy Tale Book', 'Ein Buch mit allen Märchen', 'A book with all fairy tales', 'book', 'rare', 'Inspiration und Wissen', '📖✨', ARRAY['Bei einer Großmutter', 'In einer Kinderbibliothek', 'Von einem Geschichtenerzähler'], ARRAY['Zum Finden von Inspiration', 'Zum Lernen aus Geschichten', 'Zum Einschlafen mit schönen Träumen'], ARRAY['fairy tale book', 'story collection', 'dream pages', 'imagination source', 'wonder tales'], 0.6, 0.9, 0.5, 0.5, 0.7, 0.5, 0.8),

-- POTIONS (60-65)
('artifact_028', 'Beruhigungstrank', 'Calming Potion', 'Ein Trank, der Angst nimmt', 'A potion that removes fear', 'potion', 'common', 'Überwindung von Angst', '🧪💙', ARRAY['Bei einem Heiler', 'In einer Apotheke', 'Von einer freundlichen Hexe'], ARRAY['Zum Beruhigen bei Angst', 'Zum Schlafen in unruhigen Nächten', 'Zum Fokussieren in Stresssituationen'], ARRAY['calming potion', 'peace elixir', 'soothing drink', 'anxiety remover', 'tranquil liquid'], 0.4, 0.7, 0.4, 0.5, 0.6, 0.7, 0.4),

('artifact_029', 'Kraftelixir', 'Strength Elixir', 'Ein Trank, der übermenschliche Kraft gibt', 'A potion that gives superhuman strength', 'potion', 'rare', 'Kraft für schwierige Aufgaben', '🧪💪', ARRAY['Bei einem Alchemisten', 'Im Versteck eines Helden', 'Nach dem Besiegen einer Prüfung'], ARRAY['Zum Heben schwerer Lasten', 'Zum Überwinden physischer Hindernisse', 'Zum Beschützen von Freunden'], ARRAY['strength elixir', 'power potion', 'muscle boost', 'mighty drink', 'force liquid'], 0.8, 0.8, 0.4, 0.4, 0.4, 0.9, 0.3),

('artifact_054', 'Wahrheitselixir', 'Truth Elixir', 'Ein Trank, der Lügen enthüllt', 'A potion that reveals lies', 'potion', 'rare', 'Erkennung von Betrug', '🧪✨', ARRAY['Bei einem Richter', 'Im Labor eines Detektivs', 'Von einem Wahrheitssucher'], ARRAY['Zum Erkennen von Lügen', 'Zum Aufdecken von Geheimnissen', 'Zum Finden der Wahrheit'], ARRAY['truth elixir', 'honesty potion', 'lie revealer', 'sincere drink', 'veracity liquid'], 0.5, 0.7, 1.0, 0.2, 0.5, 0.5, 0.6),

-- JEWELRY (65-75)
('artifact_032', 'Goldene Kette', 'Golden Chain', 'Eine glänzende goldene Kette', 'A shining golden chain', 'jewelry', 'common', 'Verkauf für Hilfe', '⛓️✨', ARRAY['In einer Schatzkiste', 'Bei einem Juwelier', 'Als Erbstück einer Familie'], ARRAY['Zum Tauschen gegen Hilfe', 'Als Zeichen von Reichtum', 'Zum Verbinden von Gegenständen'], ARRAY['golden chain', 'gold necklace', 'precious metal', 'valuable jewelry', 'shiny links'], 0.5, 0.5, 0.4, 0.3, 0.5, 0.4, 0.3),

('artifact_039', 'Freundschaftsarmband', 'Friendship Bracelet', 'Ein Armband, das Freundschaft symbolisiert', 'A bracelet that symbolizes friendship', 'jewelry', 'common', 'Erinnerung an Freunde', '💜🧿', ARRAY['Von einem Freund', 'Selbst gemacht', 'Bei einem Handwerker'], ARRAY['Zum Stärken von Freundschaften', 'Als Glücksbringer', 'Zum Erinnern an besondere Menschen'], ARRAY['friendship bracelet', 'bond jewelry', 'companion symbol', 'unity band', 'connection piece'], 0.4, 0.5, 0.3, 0.4, 1.0, 0.4, 0.3),

('artifact_065', 'Feuerring', 'Fire Ring', 'Ein Ring, der Feuer kontrolliert', 'A ring that controls fire', 'jewelry', 'rare', 'Kontrolle über Flammen', '💍🔥', ARRAY['Im Vulkan', 'Bei einem Feuerzauberer', 'Von einem Feuergeist'], ARRAY['Zum Entzünden von Flammen', 'Zum Schutz vor Feuer', 'Zum Wärmen in der Kälte'], ARRAY['fire ring', 'flame band', 'burning jewelry', 'heat controller', 'ember circle'], 0.7, 0.9, 0.5, 0.5, 0.3, 0.6, 0.4),

('artifact_066', 'Eiskrone', 'Ice Crown', 'Eine Krone aus Eis mit Zauberkraft', 'A crown made of ice with magic power', 'jewelry', 'legendary', 'Macht über Kälte', '👑❄️', ARRAY['Im Eispalast', 'Von der Schneekönigin', 'Am Nordpol'], ARRAY['Zum Kontrollieren von Eis', 'Zum Abkühlen heißer Situationen', 'Zum Erschaffen von Schneeskulpturen'], ARRAY['ice crown', 'frost tiara', 'winter royalty', 'frozen diadem', 'cold headpiece'], 0.7, 1.0, 0.5, 0.8, 0.3, 0.6, 0.4),

('artifact_087', 'Tapferkeitsring', 'Bravery Ring', 'Ein Ring, der Mut gibt', 'A ring that gives courage', 'jewelry', 'rare', 'Überwindung von Angst', '💍💪', ARRAY['Bei einem Helden', 'Im Tempel des Mutes', 'Nach einer Mutprobe'], ARRAY['Zum Stärken des Mutes', 'Zum Überwinden von Ängsten', 'Zum Inspirieren anderer'], ARRAY['bravery ring', 'courage band', 'valor circle', 'fearless jewelry', 'bold symbol'], 0.7, 0.7, 0.4, 0.3, 0.5, 1.0, 0.4),

('artifact_088', 'Weisheitskrone', 'Wisdom Crown', 'Ein Diadem der Weisheit', 'A diadem of wisdom', 'jewelry', 'legendary', 'Zugang zu großem Wissen', '👑📚', ARRAY['Bei einem weisen König', 'Im Tempel des Wissens', 'Von einer alten Königin'], ARRAY['Zum Erlangen von Weisheit', 'Zum Treffen kluger Entscheidungen', 'Zum Verstehen komplexer Probleme'], ARRAY['wisdom crown', 'knowledge tiara', 'smart diadem', 'intelligence headpiece', 'sage symbol'], 0.5, 0.8, 0.6, 0.3, 0.5, 0.5, 1.0),

('artifact_093', 'Familienmedaillon', 'Family Medallion', 'Ein Medaillon für die Familie', 'A medallion for the family', 'jewelry', 'rare', 'Schutz und Geborgenheit', '🏘️📿', ARRAY['Von einem Familienmitglied', 'Als Erbstück', 'Bei einer Familienfeier'], ARRAY['Zum Erinnern an Familie', 'Zum Finden von Verwandten', 'Zum Fühlen von Geborgenheit'], ARRAY['family medallion', 'home pendant', 'kinship jewelry', 'heritage piece', 'love symbol'], 0.4, 0.6, 0.4, 0.3, 0.9, 0.5, 0.4),

('artifact_094', 'Zuhuuseamulett', 'Home Amulet', 'Ein Amulett zum Weg nach Hause', 'An amulet for the way home', 'jewelry', 'rare', 'Rückkehr nach Hause', '🏠📿', ARRAY['Von einem liebenden Elternteil', 'Bei der Abreise', 'Am Anfang einer Reise'], ARRAY['Zum Finden des Weges nach Hause', 'Zum Fühlen von Heimat', 'Zum Schutz auf Reisen'], ARRAY['home amulet', 'return pendant', 'homeward jewelry', 'safe travel', 'guidance piece'], 0.6, 0.7, 0.5, 0.4, 0.8, 0.5, 0.4),

-- NATURE (75-80)
('artifact_019', 'Heilkraut', 'Healing Herb', 'Ein Kraut, das jede Krankheit heilt', 'An herb that heals any illness', 'nature', 'common', 'Genesung von Verletzungen', '🌿💚', ARRAY['Im tiefen Wald', 'Bei einer Kräuterhexe', 'An einem heiligen Ort'], ARRAY['Zum Heilen von Krankheiten', 'Zum Lindern von Schmerzen', 'Zum Stärken des Körpers'], ARRAY['healing herb', 'medicinal plant', 'cure leaf', 'health greens', 'restoration flora'], 0.5, 0.7, 0.3, 1.0, 0.6, 0.4, 0.6),

-- TECH (80-82)
('artifact_011', 'Quantenbatterie', 'Quantum Battery', 'Eine kleine Batterie mit unendlicher Energie', 'A small battery with infinite energy', 'tech', 'rare', 'Energiequelle für Maschinen', '🔋⚡', ARRAY['In einem futuristischen Labor', 'Bei einem genialen Erfinder', 'In einem Raumschiff'], ARRAY['Zum Betreiben von Maschinen', 'Zum Aufladen von Geräten', 'Zum Erzeugen von Strom'], ARRAY['quantum battery', 'energy cell', 'power source', 'infinite charge', 'tech device'], 0.7, 0.5, 0.7, 0.3, 0.3, 0.5, 0.8),

-- ARMOR (82-85)
('artifact_040', 'Kampfschild', 'Battle Shield', 'Ein metallischer Schild zum Schutz', 'A metal shield for protection', 'armor', 'common', 'Verteidigung gegen Angriffe', '🛡️', ARRAY['Bei einem Ritter', 'In einer Waffenkammer', 'Nach einem Turnier'], ARRAY['Zum Blocken von Angriffen', 'Zum Schützen von Freunden', 'Zum Abwehren von Gefahren'], ARRAY['battle shield', 'metal protection', 'defense plate', 'warrior guard', 'combat blocker'], 0.8, 0.7, 0.4, 0.3, 0.4, 0.9, 0.3),

-- MAPS (85-90)
('artifact_053', 'Orakelkarte', 'Oracle Map', 'Eine Karte, die die Zukunft zeigt', 'A map that shows the future', 'map', 'rare', 'Vorahnung von Ereignissen', '🗺️✨', ARRAY['Bei einem Wahrsager', 'In einem Tempel der Seher', 'Nach einer Vision'], ARRAY['Zum Sehen kommender Ereignisse', 'Zum Planen von Reisen', 'Zum Vermeiden von Gefahren'], ARRAY['oracle map', 'future chart', 'prophecy scroll', 'destiny path', 'vision guide'], 0.7, 0.9, 0.8, 0.4, 0.4, 0.6, 0.7),

('artifact_060', 'Schatzkarte', 'Treasure Map', 'Eine echte Schatzkarte zu verstecktem Gold', 'A real treasure map to hidden gold', 'map', 'rare', 'Finden eines Schatzes', '🗺️💰', ARRAY['In einer alten Flasche', 'Bei einem Piraten', 'Auf einem gesunkenen Schiff'], ARRAY['Zum Finden von Schätzen', 'Zum Starten von Abenteuern', 'Zum Entdecken geheimer Orte'], ARRAY['treasure map', 'gold chart', 'pirate scroll', 'hidden riches', 'X marks spot'], 0.9, 0.7, 0.7, 0.5, 0.4, 0.7, 0.4),

('artifact_080', 'Abenteuerkarte', 'Adventure Map', 'Eine Karte zu Abenteuern', 'A map to adventures', 'map', 'rare', 'Finden von Abenteuern', '🗺️⭐', ARRAY['Bei einem Abenteurer', 'Im Abenteuerclub', 'Nach einer ersten Quest'], ARRAY['Zum Finden neuer Abenteuer', 'Zum Entdecken spannender Orte', 'Zum Planen von Reisen'], ARRAY['adventure map', 'quest chart', 'journey guide', 'exploration scroll', 'discovery path'], 1.0, 0.8, 0.6, 0.6, 0.5, 0.8, 0.5),

('artifact_047', 'Kristallflöte', 'Crystal Flute', 'Eine Flöte, die Magie beschwört', 'A flute that summons magic', 'magic', 'rare', 'Beschwörung von Zaubersprüchen', '🎵✨', ARRAY['Bei einem Musikzauberer', 'Im Kristallpalast', 'Von einer singenden Fee'], ARRAY['Zum Beschwören magischer Effekte', 'Zum Rufen von Helfern', 'Zum Verzaubern von Wesen'], ARRAY['crystal flute', 'magic instrument', 'spell music', 'enchanted melody', 'summoning sound'], 0.6, 1.0, 0.6, 0.5, 0.5, 0.5, 0.6),

('artifact_057', 'Gedächtniskugel', 'Memory Orb', 'Eine Kugel, die Erinnerungen speichert', 'An orb that stores memories', 'magic', 'rare', 'Wiederherstellung von Erinnerungen', '🔮📸', ARRAY['Bei einem Gedächtnisbewahrer', 'Im Museum der Erinnerungen', 'Von einem alten Weisen'], ARRAY['Zum Speichern wichtiger Momente', 'Zum Wiederfinden verlorener Erinnerungen', 'Zum Teilen von Erlebnissen'], ARRAY['memory orb', 'recall sphere', 'past keeper', 'moment storage', 'experience globe'], 0.5, 0.8, 0.7, 0.3, 0.7, 0.4, 0.7),

('artifact_069', 'Kriegstrompete', 'War Trumpet', 'Eine Trompete, die zum Kampf ruft', 'A trumpet that calls to battle', 'weapon', 'common', 'Beschwörung von Helfern', '📯', ARRAY['In einer Militärkaserne', 'Bei einem Herolden', 'Nach einem Sieg'], ARRAY['Zum Rufen von Verbündeten', 'Zum Einschüchtern von Feinden', 'Zum Signalisieren von Gefahr'], ARRAY['war trumpet', 'battle horn', 'call instrument', 'rally sound', 'combat signal'], 0.8, 0.6, 0.4, 0.3, 0.5, 0.8, 0.3);
