// @ts-nocheck
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import path from "node:path";

const backendRoot = path.resolve(import.meta.dir, "..");

function source(relativePath: string): string {
  // Checked-out files may use CRLF; the assertions below expect LF.
  return readFileSync(path.join(backendRoot, relativePath), "utf8").split(String.fromCharCode(13, 10)).join(String.fromCharCode(10));
}

function routeOptions(relativePath: string, route: string): string {
  const line = source(relativePath)
    .split(String.fromCharCode(10))
    .find((candidate) => candidate.includes('path: "' + route + '"'));
  if (!line) throw new Error("Route not found: " + relativePath + " " + route);
  return line;
}

describe("security regression guards", () => {
  test("costly public endpoints require authentication", () => {
    const routes: Array<[string, string]> = [
      ["ai/avatar-generation.ts", "/ai/generate-avatar"],
      ["ai/analyze-avatar.ts", "/ai/analyze-avatar-image"],
      ["ai/analyze-personality.ts", "/ai/analyze-personality"],
      ["ai/generate-visual-profile.ts", "/ai/generate-visual-profile"],
      ["tavi/chat.ts", "/tavi/chat"],
      ["tts/tts.ts", "/tts/generate"],
      ["tts/tts.ts", "/tts/batch"],
      ["tts/tts.ts", "/tts/qwen/dialogue"],
      ["doku/audio-script.ts", "/doku/audio-script/topics"],
      ["doku/audio-script.ts", "/doku/audio-script/generate"],
      ["story/audio-cache.ts", "/story/pre-generate-audio"],
      ["doku/audio-doku.ts", "/audio-dokus/generate-cover"],
      ["avatar/cosmos-suggestions-api.ts", "/api/suggestions/refresh-one"],
    ];

    for (const [file, route] of routes) {
      expect(routeOptions(file, route)).toContain("auth: true");
    }
  });

  test("low-level bulk AI endpoints are internal only", () => {
    expect(routeOptions("ai/image-generation.ts", "/ai/generate-image")).toContain("expose: false");
    expect(routeOptions("ai/image-generation.ts", "/ai/generate-images-batch")).toContain("expose: false");
    expect(routeOptions("story/ai-generation.ts", "/ai/generate-story")).toContain("expose: false");
  });

  test("raw SQL and maintenance endpoints are not exposed", () => {
    const routes: Array<[string, string]> = [
      ["story/run-migration-sql.ts", "/story/run-migration-sql"],
      ["doku/run-migration-sql.ts", "/doku/run-migration-sql"],
      ["avatar/run-migration-sql.ts", "/avatar/run-migration-sql"],
      ["health/run-migrations.ts", "/health/run-migrations"],
      ["health/complete-fairy-tales-setup.ts", "/health/complete-fairy-tales-setup"],
      ["health/import-150-fairy-tales.ts", "/health/import-150-fairy-tales"],
    ];

    for (const [file, route] of routes) {
      expect(routeOptions(file, route)).toContain("expose: false");
    }
  });

  test("normal users cannot choose subscription or role", () => {
    const profile = source("user/profile.ts");
    const requestStart = profile.indexOf("interface CreateUserRequest");
    const requestEnd = profile.indexOf("interface GetUserParams", requestStart);
    const requestBlock = profile.slice(requestStart, requestEnd);
    expect(requestBlock).not.toContain("subscription");
    expect(requestBlock).not.toContain("role");
    expect(routeOptions("user/profile.ts", "/user")).toContain("auth: true");
    expect(routeOptions("user/profile.ts", "/user/:id")).toContain("auth: true");
    expect(profile).not.toContain("req.subscription");
    expect(profile).not.toContain("req.role");
  });

  test("secondary AI and diagnostic paths are guarded", () => {
    expect(source("avatar/cosmos-suggestions-api.ts")).toContain("claimMeteredUsage");
    // Audio doku covers are generated by admins only (see the audio test below).
    expect(source("doku/audio-doku.ts")).toContain("ensureAdmin()");
    expect(source("log/debug.ts")).toContain("ensureAdmin()");
    expect(source("story/analyze-phase-logs.ts")).toContain("ensureAdmin()");
  });

  test("all paid quotas remain finite and metered updates are atomic", () => {
    const catalog = source("helpers/plan-catalog.ts");
    expect(catalog).toContain("premium: { stories: 40, dokus: 40 }");
    expect(catalog).toContain("premium: { chat: 200, assist: 200, image: 100, tts: 1_500_000 }");
    const billing = source("helpers/billing.ts");
    expect(billing).toContain("AND units + ${units} <= ${limit}");
    // Story/doku coins are checked and written under a per-user advisory lock.
    expect(billing).toContain("pg_advisory_xact_lock($1, hashtext($2))");
  });

  test("plans come only from sources the browser cannot write", () => {
    const billing = source("helpers/billing.ts");
    expect(billing).not.toContain("extractPlanFromMetadataObject(user.unsafeMetadata)");
    const tokenParser = billing.slice(
      billing.indexOf("export function extractPlanClaimsFromToken"),
      billing.indexOf("export function extractPlanFromClerkToken")
    );
    expect(tokenParser).toContain("payload?.pla");
    expect(tokenParser).not.toMatch(/payload\?\.\w*metadata/i);
  });

  test("audio doku production, studio and dialogue TTS are admin only", () => {
    const audio = source("doku/audio-doku.ts");
    for (const route of ["/audio-dokus/upload-url", "/audio-dokus/generate-cover"]) {
      const after = audio.slice(audio.indexOf(`path: "${route}"`));
      expect(after.slice(0, 200)).toContain("ensureAdmin()");
    }
    const createBlock = audio.slice(audio.indexOf("export const createAudioDoku"), audio.indexOf("export const generateAudioCover"));
    expect(createBlock).toContain("ensureAdmin()");
    const updateBlock = audio.slice(audio.indexOf("export const updateAudioDoku"), audio.indexOf("export const deleteAudioDoku"));
    expect(updateBlock).toContain("ensureAdmin()");

    const studio = source("story/studio-api.ts");
    const studioRoutes = studio.split('path: "/story/studio/').length - 1;
    expect(studioRoutes).toBeGreaterThan(0);
    expect(studio.split("ensureAdmin();").length - 1).toBeGreaterThanOrEqual(studioRoutes);

    expect(source("doku/audio-script.ts").split("ensureAdmin();").length - 1).toBe(2);
    const tts = source("tts/tts.ts");
    const dialogue = tts.slice(tts.indexOf('path: "/tts/qwen/dialogue"'));
    expect(dialogue.slice(0, 200)).toContain("ensureAdmin()");
  });

  test("customers cannot pick models or engine settings for stories", () => {
    const generate = source("story/generate.ts");
    expect(generate).toContain('if (auth?.role !== "admin") {\n      req.config = stripAdminOnlyStoryOptions(req.config);');
    const strip = generate.slice(
      generate.indexOf("function stripAdminOnlyStoryOptions"),
      generate.indexOf("// Generates a new story based on the provided configuration.")
    );
    for (const forbidden of ["developerMode", "storybookEngine", "releaseCandidateCount", "maxStoryTokens", "criticModel", "contentType"]) {
      expect(strip).not.toContain(forbidden);
    }
  });

  test("failed generations give their coin back", () => {
    for (const file of ["story/generate.ts", "doku/generate.ts", "story/generate-from-fairytale.ts", "story/generation-capacity.ts", "doku/generation-capacity.ts"]) {
      expect(source(file)).toContain("refundGenerationUsage(");
    }
    for (const file of ["tavi/chat.ts", "tts/tts.ts", "ai/avatar-generation.ts", "ai/analyze-avatar.ts", "avatar/create.ts"]) {
      expect(source(file)).toMatch(/refundMeteredUsage\(|withMeteredUsage\(/);
    }
  });

  test("deleting a profile cannot reset spent coins", () => {
    const cleanup = source("helpers/content-cleanup.ts");
    expect(cleanup).not.toMatch(/DELETE FROM quota_ledger/);
  });

  test("free accounts cannot let Tavi create content", () => {
    const chat = source("tavi/chat.ts");
    expect(chat).toContain("TAVI_CREATION_TOOL_NAMES.has(tool.function.name)");
    expect(chat).toContain("!taviCanCreate && TAVI_CREATION_TOOL_NAMES.has(fnName)");
  });
});