import type { RoleSlot, SceneBeat, TaleDNA } from "./types";

export const FALLBACK_TALE_DNA: { tale: TaleDNA; roles: RoleSlot[]; scenes: SceneBeat[] } = {
  tale: {
    taleId: "grimm-026",
    title: "Rotkäppchen",
    language: "de",
    age: { min: 5, max: 9 },
    summary: "Ein Mädchen mit roter Kappe bringt ihrer Großmutter einen Korb, trifft den Wolf und wird gerettet.",
    moralLesson: "Sei achtsam und höre auf gute Ratschläge.",
    cultureRegion: "german",
    source: "grimm",
    themeTags: ["caution", "family", "courage"],
    coreConflict: "A cunning wolf threatens the journey to grandmother's house.",
    emotionalArc: ["warm", "curious", "tense", "relief", "joy"],
    chapterCountHint: 5,
    iconicBeats: [
      "The warning from mother",
      "Meeting the wolf on the path",
      "The distraction in the forest",
      "The tense scene at grandmother's house",
      "Rescue and lesson learned",
    ],
    fixedElements: ["red hood", "forest path", "grandmother's cottage", "the wolf"],
    flexibleElements: ["weather", "artifact twist", "rescuer's method"],
    toneBounds: {
      targetTone: "Warm, cautious, hopeful",
      contentRules: [
        "Keep suspense gentle",
        "No graphic violence",
        "Ensure a safe ending",
        "Use clear, simple sentences",
      ],
    },
  },
  roles: [
    {
      slotKey: "SLOT_PROTAGONIST_1",
      roleType: "PROTAGONIST",
      required: true,
      roleCount: 1,
      archetypePreference: ["innocent", "brave"],
      constraints: ["gender=female", "age=child"],
      visualHints: ["red hood", "basket"],
    },
    {
      slotKey: "SLOT_ANTAGONIST_1",
      roleType: "ANTAGONIST",
      required: true,
      roleCount: 1,
      archetypePreference: ["trickster", "wolf"],
      constraints: ["species=animal"],
      visualHints: ["wolf", "dark fur"],
    },
    {
      slotKey: "SLOT_GUARDIAN_1",
      roleType: "GUARDIAN",
      required: false,
      roleCount: 1,
      archetypePreference: ["elder"],
      constraints: ["age=elder"],
      visualHints: ["grandmother", "kind eyes"],
    },
    {
      slotKey: "SLOT_HELPER_1",
      roleType: "HELPER",
      required: false,
      roleCount: 1,
      archetypePreference: ["hunter"],
      constraints: ["age=adult"],
      visualHints: ["hunter", "cloak"],
    },
  ],
  scenes: [
    {
      sceneNumber: 1,
      beatType: "SETUP",
      sceneTitle: "Der Auftrag",
      setting: "village cottage",
      mood: "COZY",
      sceneDescription: "Rotkäppchen erhält den Korb und die Warnung, nicht vom Weg abzugehen.",
      mustIncludeSlots: ["SLOT_PROTAGONIST_1"],
    },
    {
      sceneNumber: 2,
      beatType: "INCITING",
      sceneTitle: "Begegnung im Wald",
      setting: "forest path",
      mood: "MYSTERIOUS",
      sceneDescription: "Der Wolf spricht freundlich mit Rotkäppchen und fragt nach dem Ziel.",
      mustIncludeSlots: ["SLOT_PROTAGONIST_1", "SLOT_ANTAGONIST_1"],
    },
    {
      sceneNumber: 3,
      beatType: "CONFLICT",
      sceneTitle: "Die Ablenkung",
      setting: "forest clearing",
      mood: "TENSE",
      sceneDescription: "Rotkäppchen pflückt Blumen, während der Wolf zur Hütte eilt.",
      mustIncludeSlots: ["SLOT_PROTAGONIST_1", "SLOT_ANTAGONIST_1"],
      artifactPolicy: {
        requiresArtifact: true,
        artifactSlotKey: "SLOT_ARTIFACT_1",
        artifactMustBeVisible: true,
      },
    },
    {
      sceneNumber: 4,
      beatType: "CLIMAX",
      sceneTitle: "Bei der Großmutter",
      setting: "grandmother cottage",
      mood: "TENSE",
      sceneDescription: "Rotkäppchen erkennt den Wolf im Bett und die Spannung steigt.",
      mustIncludeSlots: ["SLOT_PROTAGONIST_1", "SLOT_ANTAGONIST_1", "SLOT_GUARDIAN_1"],
      artifactPolicy: {
        requiresArtifact: true,
        artifactSlotKey: "SLOT_ARTIFACT_1",
        artifactMustBeVisible: true,
      },
    },
    {
      sceneNumber: 5,
      beatType: "RESOLUTION",
      sceneTitle: "Die Rettung",
      setting: "grandmother cottage",
      mood: "TRIUMPH",
      sceneDescription: "Der Jäger hilft, die Gefahr endet, alle feiern und lernen.",
      mustIncludeSlots: ["SLOT_PROTAGONIST_1", "SLOT_GUARDIAN_1", "SLOT_HELPER_1"],
    },
  ],
};
