// OpenAI function calling tool definitions for Tavi
// These define all capabilities Tavi can execute on behalf of the user.

export interface TaviTool {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: Record<string, any>;
  };
}

export const TAVI_TOOLS: TaviTool[] = [
  {
    type: "function",
    function: {
      name: "create_story",
      description:
        "Generate a new personalized story. Use when the user wants you to create/write/tell a story immediately. The story is generated by AI and takes a moment.",
      parameters: {
        type: "object",
        properties: {
          genre: {
            type: "string",
            enum: ["fairy_tales", "adventure", "magic", "animals", "scifi", "modern"],
            description: "Story genre",
          },
          setting: {
            type: "string",
            description: "Story setting (forest, space, ocean, castle, school, city, desert, mountains, island, jungle, fantasy, varied)",
          },
          ageGroup: { type: "string", enum: ["3-5", "6-8", "9-12", "13+"] },
          length: { type: "string", enum: ["short", "medium", "long"] },
          tone: {
            type: "string",
            enum: ["warm", "witty", "epic", "soothing", "mischievous", "wonder"],
          },
          avatarNames: {
            type: "array",
            items: { type: "string" },
            description: "Names of avatars to include in the story. Leave empty to use default avatars.",
          },
          customPrompt: {
            type: "string",
            description: "Custom story theme/wish from the user, in the user's language",
          },
          allowRhymes: { type: "boolean" },
          hasTwist: { type: "boolean" },
          suspenseLevel: { type: "number", minimum: 0, maximum: 3 },
          humorLevel: { type: "number", minimum: 0, maximum: 3 },
          pacing: { type: "string", enum: ["slow", "balanced", "fast"] },
        },
        required: [],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "create_doku",
      description:
        "Generate a knowledge document (Wissensdoku) about a topic. Use when the user wants to learn about something or create a knowledge article.",
      parameters: {
        type: "object",
        properties: {
          topic: { type: "string", description: "The topic to create a doku about" },
          ageGroup: { type: "string", enum: ["3-5", "6-8", "9-12", "13+"] },
          depth: { type: "string", enum: ["basic", "standard", "deep"] },
          perspective: {
            type: "string",
            enum: ["science", "history", "technology", "nature", "culture"],
          },
          tone: { type: "string", enum: ["fun", "neutral", "curious"] },
          length: { type: "string", enum: ["short", "medium", "long"] },
          includeInteractive: {
            type: "boolean",
            description: "Include quiz questions and activities",
          },
        },
        required: ["topic"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "create_avatar",
      description:
        "Create a new avatar character directly. Use when the user describes a character they want to create and you have enough information (at least a name and type).",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string", description: "Name of the avatar" },
          characterType: {
            type: "string",
            description: "Type: human, dog, cat, rabbit, fox, bear, unicorn, fairy, robot, alien, wizard, dragon",
          },
          appearance: {
            type: "string",
            description: "Physical appearance description in natural language",
          },
          gender: { type: "string", enum: ["male", "female", "neutral"] },
        },
        required: ["name", "characterType"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "open_story_wizard",
      description:
        "Open the story creation wizard with pre-filled settings. Use when the user wants more control over story settings or you want to let them fine-tune before generating.",
      parameters: {
        type: "object",
        properties: {
          genre: { type: "string" },
          ageGroup: { type: "string" },
          length: { type: "string" },
          tone: { type: "string" },
          avatarNames: { type: "array", items: { type: "string" } },
          customPrompt: { type: "string" },
          allowRhymes: { type: "boolean" },
          hasTwist: { type: "boolean" },
        },
        required: [],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "open_avatar_wizard",
      description:
        "Open the avatar creation wizard with pre-filled data. Use when the user wants to create an avatar with detailed customization or when you need more details from them.",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string" },
          characterType: { type: "string" },
          gender: { type: "string" },
          appearance: { type: "string" },
          mode: {
            type: "string",
            enum: ["child", "companion"],
            description: "child = Kinder-Avatar, companion = Begleiter",
          },
        },
        required: [],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "open_doku_wizard",
      description:
        "Open the doku creation wizard with pre-filled settings. Use when the user wants to customize doku parameters before generating.",
      parameters: {
        type: "object",
        properties: {
          topic: { type: "string" },
          domain: {
            type: "string",
            enum: ["space", "nature", "history", "tech", "body", "earth", "arts", "logic"],
          },
          ageGroup: { type: "string" },
          depth: { type: "string" },
          perspective: { type: "string" },
          tone: { type: "string" },
        },
        required: [],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "generate_image",
      description:
        "Generate an image/illustration and show it in the chat. Use when the user asks to draw, paint, create a picture, or wants to see something visualized. The image uses the Flux model.",
      parameters: {
        type: "object",
        properties: {
          prompt: {
            type: "string",
            description:
              "Detailed English image prompt. Always write in English for best results. Include style, colors, composition details.",
          },
          style: {
            type: "string",
            enum: ["disney", "realistic", "anime"],
            description: "Visual style (default: disney/watercolor children's book style)",
          },
        },
        required: ["prompt"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "list_content",
      description:
        "List the user's content (avatars, stories, or dokus). Use when the user asks about their avatars, stories, dokus, or wants to see what they have.",
      parameters: {
        type: "object",
        properties: {
          contentType: {
            type: "string",
            enum: ["avatars", "stories", "dokus"],
            description: "What type of content to list",
          },
          limit: {
            type: "number",
            description: "Max items to show (default 5)",
          },
        },
        required: ["contentType"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "navigate_to",
      description:
        "Navigate the user to a specific page in the app. Use when the user wants to go somewhere or open something specific.",
      parameters: {
        type: "object",
        properties: {
          destination: {
            type: "string",
            enum: [
              "home",
              "avatars",
              "stories",
              "dokus",
              "settings",
              "avatar_detail",
              "story_reader",
              "doku_reader",
              "avatar_create",
              "story_create",
              "doku_create",
              "fairy_tales",
            ],
          },
          id: {
            type: "string",
            description: "ID of specific item (for detail/reader pages)",
          },
          name: {
            type: "string",
            description: "Name of the item being navigated to (for display purposes)",
          },
        },
        required: ["destination"],
      },
    },
  },
];
