import { createHash } from "node:crypto";
import { APIError } from "encore.dev/api";
import { createClerkClient } from "@clerk/backend";
import { userDB } from "../user/db";
import {
  ensureProfileSchema,
  getProfileBudgetPolicy,
  getProfileLimitForPlan,
  resolveRequestedProfileId,
} from "./profiles";
import {
  AUDIO_BASIC_LIBRARY_MIN_AGE_DAYS,
  FREE_TRIAL_DAYS,
  FREE_TRIAL_METERED_QUOTAS,
  FREE_TRIAL_QUOTAS,
  PLAN_AUDIO_LIBRARY_ACCESS,
  PLAN_DAILY_LIMITS,
  PLAN_METERED_QUOTAS,
  PLAN_QUOTAS,
  PLAN_TAVI_CAN_CREATE,
  type AudioLibraryAccess,
  type MeteredUsageKind,
  type PlanQuota,
  type SubscriptionPlan,
} from "./plan-catalog";

export {
  AUDIO_BASIC_LIBRARY_MIN_AGE_DAYS,
  BASE_PROFILE_LIMITS,
  FREE_TRIAL_DAYS,
  FREE_TRIAL_METERED_QUOTAS,
  FREE_TRIAL_QUOTAS,
  PLAN_AUDIO_LIBRARY_ACCESS,
  PLAN_DAILY_LIMITS,
  PLAN_METERED_QUOTAS,
  PLAN_QUOTAS,
  PLAN_TAVI_CAN_CREATE,
} from "./plan-catalog";
export type {
  AudioLibraryAccess,
  MeteredPlanQuota,
  MeteredUsageKind,
  PlanQuota,
  SubscriptionPlan,
} from "./plan-catalog";

// Only stories and dokus are generated by users. Audio dokus are produced by
// admins and unlocked per plan (see PLAN_AUDIO_LIBRARY_ACCESS).
export type UsageKind = "story" | "doku";
type UserRole = "admin" | "user";

// Generations that failed and were refunded still count here, so a user
// cannot make the platform pay for endless failing attempts.
const MAX_REFUNDED_ATTEMPTS_PER_DAY = 5;
const BILLING_LOCK_NAMESPACE = 810_100;
// Timestamps in quota_ledger are written with the DB clock, so the day start
// is computed there as well (same session time zone on both sides).
const BERLIN_DAY_START_SQL =
  "(date_trunc('day', now() AT TIME ZONE 'Europe/Berlin') AT TIME ZONE 'Europe/Berlin')::timestamp";

const PLAN_PRIORITY: SubscriptionPlan[] = ["premium", "familie", "starter", "free"];
const PLAN_ALIASES: Record<SubscriptionPlan, string[]> = {
  free: ["free", "kostenlos"],
  starter: ["starter"],
  familie: ["familie", "family"],
  premium: ["premium"],
};

const DEFAULT_PLAN: SubscriptionPlan = "free";
const MS_PER_DAY = 24 * 60 * 60 * 1000;
const PLAN_SYNC_CACHE_TTL_MS = 30_000;

let cachedClerkClient: ReturnType<typeof createClerkClient> | null | undefined;
let cachedClerkClientPromise: Promise<ReturnType<typeof createClerkClient> | null> | null = null;

type CachedPlanResolution = {
  plan: SubscriptionPlan | null;
  expiresAt: number;
};

type CachedRoleResolution = {
  role: UserRole | null;
  expiresAt: number;
};

const clerkPlanCache = new Map<string, CachedPlanResolution>();
const clerkRoleCache = new Map<string, CachedRoleResolution>();

export type BillingCancellationResult = {
  attempted: boolean;
  scheduled: boolean;
  activeItems: number;
  canceledItems: number;
  source: "sdk" | "rest" | "none";
  note?: string;
};

function startOfMonthUTC(now: Date) {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
}

function addDaysUTC(date: Date, days: number) {
  return new Date(date.getTime() + days * MS_PER_DAY);
}

function remainingDaysUntil(now: Date, end: Date): number {
  if (now >= end) return 0;
  return Math.max(0, Math.ceil((end.getTime() - now.getTime()) / MS_PER_DAY));
}

async function loadClerkSecretKey(): Promise<string | null> {
  try {
    const config = await import("encore.dev/config");
    const value = (
      config.secret as (key: string, options?: { optional?: boolean }) => () => string | undefined
    )("ClerkSecretKey", { optional: true })();

    if (value && value.trim().length > 0) {
      return value.trim();
    }
  } catch {
    // Ignore and fall back to env.
  }

  const fromEnv = process.env.ClerkSecretKey?.trim() || process.env.CLERK_SECRET_KEY?.trim();
  return fromEnv && fromEnv.length > 0 ? fromEnv : null;
}

async function getClerkClient(): Promise<ReturnType<typeof createClerkClient> | null> {
  if (cachedClerkClient !== undefined) {
    return cachedClerkClient;
  }

  if (cachedClerkClientPromise) {
    return cachedClerkClientPromise;
  }

  cachedClerkClientPromise = (async () => {
    try {
      const key = await loadClerkSecretKey();
      if (!key) {
        cachedClerkClient = null;
        return null;
      }

      cachedClerkClient = createClerkClient({ secretKey: key });
      return cachedClerkClient;
    } catch {
      cachedClerkClient = null;
      return null;
    }
  })();

  const client = await cachedClerkClientPromise;
  cachedClerkClientPromise = null;
  return client;
}

function extractSubscriptionItems(raw: unknown): Array<{ id: string; status: string | null }> {
  if (!raw || typeof raw !== "object") {
    return [];
  }

  const payload = raw as Record<string, unknown>;
  const candidates: unknown[] = [
    payload.subscriptionItems,
    payload.subscription_items,
    payload.items,
    payload.data,
    (payload.data as Record<string, unknown> | undefined)?.subscriptionItems,
    (payload.data as Record<string, unknown> | undefined)?.subscription_items,
    (payload.data as Record<string, unknown> | undefined)?.items,
  ];

  for (const candidate of candidates) {
    if (!Array.isArray(candidate)) continue;
    const items = candidate
      .map((entry) => {
        if (!entry || typeof entry !== "object") return null;
        const row = entry as Record<string, unknown>;
        const id = typeof row.id === "string" ? row.id : "";
        if (!id) return null;
        const status = typeof row.status === "string" ? row.status : null;
        return { id, status };
      })
      .filter((entry): entry is { id: string; status: string | null } => entry !== null);

    if (items.length > 0) {
      return items;
    }
  }

  return [];
}

function isFinalSubscriptionStatus(status: string | null | undefined): boolean {
  if (!status) return false;
  const normalized = status.trim().toLowerCase();
  return normalized === "canceled" ||
    normalized === "cancelled" ||
    normalized === "expired" ||
    normalized === "terminated";
}

async function fetchBillingSubscriptionViaRest(userId: string, secretKey: string): Promise<unknown | null> {
  const endpoints = [
    `https://api.clerk.com/v1/users/${encodeURIComponent(userId)}/billing/subscription`,
    `https://api.clerk.com/v1/users/${encodeURIComponent(userId)}/commerce/subscription`,
  ];

  let lastError: string | null = null;

  for (const endpoint of endpoints) {
    const response = await fetch(endpoint, {
      method: "GET",
      headers: {
        Authorization: `Bearer ${secretKey}`,
        "Content-Type": "application/json",
      },
    });

    if (response.status === 404) {
      return null;
    }

    if (!response.ok) {
      lastError = `${response.status} ${response.statusText}`;
      continue;
    }

    return response.json();
  }

  throw new Error(`Could not fetch Clerk subscription (${lastError ?? "unknown error"})`);
}

async function cancelSubscriptionItemViaRest(itemId: string, secretKey: string): Promise<boolean> {
  const endpoints = [
    `https://api.clerk.com/v1/billing/subscription_items/${encodeURIComponent(itemId)}`,
    `https://api.clerk.com/v1/commerce/subscription_items/${encodeURIComponent(itemId)}`,
  ];

  let lastError: string | null = null;

  for (const endpoint of endpoints) {
    const response = await fetch(endpoint, {
      method: "DELETE",
      headers: {
        Authorization: `Bearer ${secretKey}`,
        "Content-Type": "application/json",
      },
    });

    if (response.ok || response.status === 404 || response.status === 409) {
      return true;
    }

    lastError = `${response.status} ${response.statusText}`;
  }

  throw new Error(`Could not cancel subscription item ${itemId} (${lastError ?? "unknown error"})`);
}

export async function cancelUserBillingAtPeriodEnd(userId: string): Promise<BillingCancellationResult> {
  const client = await getClerkClient();
  const sdkBilling = (client as any)?.billing;

  if (sdkBilling?.getUserBillingSubscription && sdkBilling?.cancelSubscriptionItem) {
    const subscription = await sdkBilling.getUserBillingSubscription(userId);
    const items = extractSubscriptionItems(subscription);
    const activeItems = items.filter((item) => !isFinalSubscriptionStatus(item.status));

    let canceledItems = 0;
    for (const item of activeItems) {
      await sdkBilling.cancelSubscriptionItem(item.id, { endNow: false });
      canceledItems += 1;
    }

    return {
      attempted: activeItems.length > 0,
      scheduled: canceledItems === activeItems.length,
      activeItems: activeItems.length,
      canceledItems,
      source: "sdk",
      note: activeItems.length === 0 ? "no_active_subscription_items" : undefined,
    };
  }

  const secretKey = await loadClerkSecretKey();
  if (!secretKey) {
    return {
      attempted: false,
      scheduled: false,
      activeItems: 0,
      canceledItems: 0,
      source: "none",
      note: "missing_clerk_secret",
    };
  }

  const subscription = await fetchBillingSubscriptionViaRest(userId, secretKey);
  if (!subscription) {
    return {
      attempted: false,
      scheduled: true,
      activeItems: 0,
      canceledItems: 0,
      source: "rest",
      note: "no_billing_subscription",
    };
  }

  const items = extractSubscriptionItems(subscription);
  const activeItems = items.filter((item) => !isFinalSubscriptionStatus(item.status));
  if (activeItems.length === 0) {
    return {
      attempted: false,
      scheduled: true,
      activeItems: 0,
      canceledItems: 0,
      source: "rest",
      note: "no_active_subscription_items",
    };
  }

  let canceledItems = 0;
  for (const item of activeItems) {
    await cancelSubscriptionItemViaRest(item.id, secretKey);
    canceledItems += 1;
  }

  return {
    attempted: true,
    scheduled: canceledItems === activeItems.length,
    activeItems: activeItems.length,
    canceledItems,
    source: "rest",
  };
}

function parsePlanClaim(raw: unknown): string[] {
  if (typeof raw === "string") {
    return raw
      .split(",")
      .map((entry) => entry.trim())
      .filter(Boolean);
  }

  if (Array.isArray(raw)) {
    return raw
      .map((entry) => (typeof entry === "string" ? entry.trim() : ""))
      .filter(Boolean);
  }

  return collectStringValues(raw).map((entry) => entry.trim()).filter(Boolean);
}

function uniquePreserveOrder(entries: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const entry of entries) {
    const normalized = entry.trim();
    if (!normalized) continue;
    if (seen.has(normalized)) continue;
    seen.add(normalized);
    result.push(normalized);
  }

  return result;
}

function normalizePlanCandidate(raw: string): SubscriptionPlan | null {
  const lowered = raw.toLowerCase().trim();
  const normalized = lowered
    .replace(/[\s_-]+/g, "")
    .split(":")
    .pop() ?? "";

  for (const plan of PLAN_PRIORITY) {
    const aliases = PLAN_ALIASES[plan].map((alias) => alias.replace(/[\s_-]+/g, ""));
    if (aliases.includes(normalized) || aliases.some((alias) => lowered === alias)) {
      return plan;
    }

    for (const aliasRaw of PLAN_ALIASES[plan]) {
      const alias = aliasRaw.toLowerCase();
      const tokenRegex = new RegExp(`(^|[^a-z])${alias}([^a-z]|$)`, "i");
      if (tokenRegex.test(lowered)) {
        return plan;
      }
    }
  }

  return null;
}

function extractPlanFromEntries(entries: string[]): SubscriptionPlan | null {
  let bestPlan: SubscriptionPlan | null = null;

  for (const entry of entries) {
    const plan = normalizePlanCandidate(entry);
    if (!plan) {
      continue;
    }

    if (!bestPlan) {
      bestPlan = plan;
      continue;
    }

    const currentRank = PLAN_PRIORITY.indexOf(plan);
    const bestRank = PLAN_PRIORITY.indexOf(bestPlan);
    if (currentRank >= 0 && bestRank >= 0 && currentRank < bestRank) {
      bestPlan = plan;
    }
  }

  return bestPlan;
}

function collectStringValues(value: unknown, depth = 0): string[] {
  if (depth > 5 || value == null) {
    return [];
  }

  if (typeof value === "string") {
    return [value];
  }

  if (Array.isArray(value)) {
    return value.flatMap((entry) => collectStringValues(entry, depth + 1));
  }

  if (typeof value === "object") {
    return Object.values(value as Record<string, unknown>).flatMap((entry) =>
      collectStringValues(entry, depth + 1)
    );
  }

  return [];
}

function normalizeRoleCandidate(raw: string): UserRole | null {
  const lowered = raw.toLowerCase().trim();
  const normalized = lowered.replace(/[\s_-]+/g, "").split(":").pop() ?? "";

  if (normalized === "admin" || normalized === "administrator") {
    return "admin";
  }

  if (normalized === "user" || normalized === "member") {
    return "user";
  }

  if (/(^|[^a-z])(admin|administrator)([^a-z]|$)/i.test(lowered)) {
    return "admin";
  }

  if (/(^|[^a-z])(user|member)([^a-z]|$)/i.test(lowered)) {
    return "user";
  }

  return null;
}

function extractRoleFromEntries(entries: string[]): UserRole | null {
  let bestRole: UserRole | null = null;

  for (const entry of entries) {
    const role = normalizeRoleCandidate(entry);
    if (!role) {
      continue;
    }

    if (role === "admin") {
      return "admin";
    }

    if (!bestRole) {
      bestRole = role;
    }
  }

  return bestRole;
}

function extractRoleFromMetadataValue(raw: unknown): UserRole | null {
  const strings = collectStringValues(raw);
  return extractRoleFromEntries(strings);
}

function extractRoleFromMetadataObject(metadata: unknown): UserRole | null {
  if (!metadata || typeof metadata !== "object") {
    return null;
  }

  const record = metadata as Record<string, unknown>;
  const preferredKeys = [
    "role",
    "roles",
    "app_role",
    "appRole",
    "user_role",
    "userRole",
    "talea_role",
    "taleaRole",
  ];

  for (const key of preferredKeys) {
    if (key in record) {
      const role = extractRoleFromMetadataValue(record[key]);
      if (role) {
        return role;
      }
    }
  }

  return null;
}

async function extractRoleFromClerkProfile(userId: string): Promise<UserRole | null> {
  const now = Date.now();
  const cached = clerkRoleCache.get(userId);
  if (cached && cached.expiresAt > now) {
    return cached.role;
  }

  const client = await getClerkClient();
  if (!client) {
    clerkRoleCache.set(userId, {
      role: null,
      expiresAt: now + PLAN_SYNC_CACHE_TTL_MS,
    });
    return null;
  }

  try {
    const user = await client.users.getUser(userId);
    const fromPrivate = extractRoleFromMetadataObject(user.privateMetadata);
    const fromPublic = extractRoleFromMetadataObject(user.publicMetadata);
    const resolved = fromPrivate ?? fromPublic ?? null;

    clerkRoleCache.set(userId, {
      role: resolved,
      expiresAt: now + PLAN_SYNC_CACHE_TTL_MS,
    });

    return resolved;
  } catch (error) {
    console.warn("[billing.extractRoleFromClerkProfile] Failed to fetch Clerk profile role", {
      userId,
      error: error instanceof Error ? error.message : String(error),
    });

    clerkRoleCache.set(userId, {
      role: null,
      expiresAt: now + PLAN_SYNC_CACHE_TTL_MS,
    });

    return null;
  }
}

function extractPlanFromMetadataValue(raw: unknown): SubscriptionPlan | null {
  const strings = collectStringValues(raw);
  return extractPlanFromEntries(strings);
}

function extractPlanFromMetadataObject(metadata: unknown): SubscriptionPlan | null {
  if (!metadata || typeof metadata !== "object") {
    return null;
  }

  const record = metadata as Record<string, unknown>;
  const preferredKeys = [
    "subscription",
    "subscription_plan",
    "subscriptionPlan",
    "plan",
    "plan_name",
    "planName",
    "tier",
    "package_name",
    "packageName",
    "billing_plan",
    "billingPlan",
    "product_plan",
    "productPlan",
    "package",
    "price_id",
    "priceId",
  ];

  for (const key of preferredKeys) {
    if (key in record) {
      const plan = extractPlanFromMetadataValue(record[key]);
      if (plan) {
        return plan;
      }
    }
  }

  return extractPlanFromMetadataValue(record);
}

async function extractPlanFromClerkProfile(userId: string): Promise<SubscriptionPlan | null> {
  const now = Date.now();
  const cached = clerkPlanCache.get(userId);
  if (cached && cached.expiresAt > now) {
    return cached.plan;
  }

  const client = await getClerkClient();
  if (!client) {
    clerkPlanCache.set(userId, {
      plan: null,
      expiresAt: now + PLAN_SYNC_CACHE_TTL_MS,
    });
    return null;
  }

  try {
    const user = await client.users.getUser(userId);
    // unsafeMetadata is writable from the browser and must never grant a plan.
    // Only metadata that can be set with the Clerk secret key is trusted.
    const fromPublic = extractPlanFromMetadataObject(user.publicMetadata);
    const fromPrivate = extractPlanFromMetadataObject(user.privateMetadata);
    const resolved = fromPublic ?? fromPrivate ?? null;

    clerkPlanCache.set(userId, {
      plan: resolved,
      expiresAt: now + PLAN_SYNC_CACHE_TTL_MS,
    });

    return resolved;
  } catch (error) {
    console.warn("[billing.extractPlanFromClerkProfile] Failed to fetch Clerk profile plan", {
      userId,
      error: error instanceof Error ? error.message : String(error),
    });

    clerkPlanCache.set(userId, {
      plan: null,
      expiresAt: now + PLAN_SYNC_CACHE_TTL_MS,
    });

    return null;
  }
}

async function persistPlanIfChanged(userId: string, plan: SubscriptionPlan): Promise<void> {
  const now = new Date();
  await userDB.exec`
    UPDATE users
    SET subscription = ${plan}, updated_at = ${now}
    WHERE id = ${userId} AND subscription <> ${plan}
  `;
}

async function persistRoleIfChanged(userId: string, role: UserRole): Promise<void> {
  const now = new Date();
  try {
    await userDB.exec`
      UPDATE users
      SET role = ${role}, updated_at = ${now}
      WHERE id = ${userId} AND COALESCE(role, 'user') <> ${role}
    `;
  } catch (error) {
    console.warn("[billing.persistRoleIfChanged] Failed to persist role", {
      userId,
      role,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

function pickAuthoritativePlan(
  tokenPlan: SubscriptionPlan | null,
  profilePlan: SubscriptionPlan | null
): SubscriptionPlan | null {
  if (tokenPlan && profilePlan) {
    if (tokenPlan === profilePlan) {
      return profilePlan;
    }

    const tokenRank = PLAN_PRIORITY.indexOf(tokenPlan);
    const profileRank = PLAN_PRIORITY.indexOf(profilePlan);

    if (tokenRank >= 0 && profileRank >= 0) {
      // Prefer the higher-tier plan while sources are out-of-sync.
      return tokenRank < profileRank ? tokenPlan : profilePlan;
    }
  }

  return profilePlan ?? tokenPlan;
}

export function extractPlanClaimsFromToken(token?: string | null): string[] {
  if (!token) return [];

  try {
    const parts = token.split(".");
    if (parts.length !== 3) return [];

    const payload = JSON.parse(Buffer.from(parts[1], "base64url").toString("utf-8"));

    // Only `pla` is set by Clerk Billing itself. Custom session claims may be
    // templated from unsafe_metadata, which the browser can write, so they
    // are never read here. Metadata-based plans come from the Clerk API instead.
    return uniquePreserveOrder(parsePlanClaim(payload?.pla));
  } catch {
    return [];
  }
}

export function extractPlanFromClerkToken(token?: string | null): SubscriptionPlan | null {
  const entries = extractPlanClaimsFromToken(token);
  if (entries.length === 0) return null;
  return extractPlanFromEntries(entries);
}

export async function resolvePlanForUser(userId: string, clerkToken?: string | null): Promise<SubscriptionPlan> {
  const tokenPlan = extractPlanFromClerkToken(clerkToken);
  const profilePlan = await extractPlanFromClerkProfile(userId);
  const authoritativePlan = pickAuthoritativePlan(tokenPlan, profilePlan);

  if (authoritativePlan) {
    if (tokenPlan && profilePlan && tokenPlan !== profilePlan) {
      console.warn("[billing.resolvePlanForUser] Token plan differs from Clerk profile plan. Using profile plan.", {
        userId,
        tokenPlan,
        profilePlan,
      });
    }

    await persistPlanIfChanged(userId, authoritativePlan);
    return authoritativePlan;
  }

  const row = await userDB.queryRow<{ subscription: SubscriptionPlan }>`
    SELECT subscription FROM users WHERE id = ${userId}
  `;

  return row?.subscription ?? DEFAULT_PLAN;
}

// Backward-compatible legacy parser retained for callers that import this symbol directly.
export function extractPlanFromLegacyStringClaim(raw: unknown): string[] {
  if (typeof raw !== "string") return [];
  return raw
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);
}

// ---------------------------------------------------------------------------
// Schema (idempotent, also mirrored in user/migrations/12_billing_v2)
// ---------------------------------------------------------------------------

let billingSchemaPromise: Promise<void> | null = null;

const BILLING_SCHEMA_STATEMENTS = [
  `ALTER TABLE quota_ledger ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMP`,
  `ALTER TABLE quota_ledger ADD COLUMN IF NOT EXISTS used_family_reserve BOOLEAN NOT NULL DEFAULT FALSE`,
  `CREATE INDEX IF NOT EXISTS idx_quota_ledger_user_kind_created ON quota_ledger(user_id, kind, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_quota_ledger_user_kind_ref ON quota_ledger(user_id, kind, content_ref)`,
  `DO $$
  BEGIN
    IF EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'metered_usage_kind_check'
        AND pg_get_constraintdef(oid) NOT LIKE '%assist%'
    ) THEN
      ALTER TABLE metered_usage DROP CONSTRAINT metered_usage_kind_check;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'metered_usage_kind_check') THEN
      ALTER TABLE metered_usage ADD CONSTRAINT metered_usage_kind_check
        CHECK (kind IN ('chat', 'assist', 'image', 'tts'));
    END IF;
  END $$`,
  `CREATE TABLE IF NOT EXISTS billing_trial_history (
    email_hash TEXT PRIMARY KEY,
    first_trial_started_at TIMESTAMP NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
];

export async function ensureBillingSchema(): Promise<void> {
  if (!billingSchemaPromise) {
    billingSchemaPromise = (async () => {
      await ensureProfileSchema();
      for (const statement of BILLING_SCHEMA_STATEMENTS) {
        try {
          await userDB.rawExec(statement);
        } catch (error) {
          // Another instance may run the same DDL concurrently; the next
          // statement or the numbered migration covers it.
          console.warn("[billing.ensureBillingSchema] statement skipped", {
            error: error instanceof Error ? error.message : String(error),
          });
        }
      }
    })().catch((error) => {
      billingSchemaPromise = null;
      throw error;
    });
  }
  await billingSchemaPromise;
}

// ---------------------------------------------------------------------------
// Plan policy
// ---------------------------------------------------------------------------

type PlanPolicy = {
  plan: SubscriptionPlan;
  isAdmin: boolean;
  limits: PlanQuota;
  dailyLimits: PlanQuota;
  meteredLimits: Record<MeteredUsageKind, number | null>;
  // "trial" counts generations since sign-up, "month" per calendar month.
  usageWindow: "trial" | "month";
  freeTrialActive: boolean;
  freeTrialEndsAt: Date | null;
  freeTrialDaysRemaining: number;
  audioLibraryAccess: AudioLibraryAccess;
  taviCanCreate: boolean;
};

type UserPlanContext = {
  plan: SubscriptionPlan;
  createdAt: Date;
  role: UserRole;
  isAdmin: boolean;
  trialAlreadyUsed: boolean;
};

async function resolveRoleForUser(userId: string, dbRole: UserRole): Promise<UserRole> {
  if (dbRole === "admin") {
    return "admin";
  }

  const profileRole = await extractRoleFromClerkProfile(userId);
  if (profileRole !== "admin") {
    return dbRole;
  }

  await persistRoleIfChanged(userId, profileRole);
  return profileRole;
}

function normalizeEmailForTrial(email: string): string | null {
  const trimmed = email.trim().toLowerCase();
  const at = trimmed.lastIndexOf("@");
  if (at <= 0 || trimmed.endsWith("@local.talea")) return null;
  let local = trimmed.slice(0, at).split("+")[0];
  const domain = trimmed.slice(at + 1);
  if (domain === "gmail.com" || domain === "googlemail.com") {
    local = local.replace(/\./g, "");
  }
  return `${local}@${domain}`;
}

function hashEmailForTrial(email: string | null | undefined): string | null {
  if (!email) return null;
  const normalized = normalizeEmailForTrial(email);
  if (!normalized) return null;
  return createHash("sha256").update(normalized).digest("hex");
}

async function readTrialAlreadyUsed(email: string | null): Promise<boolean> {
  const emailHash = hashEmailForTrial(email);
  if (!emailHash) return false;
  try {
    const row = await userDB.queryRow<{ email_hash: string }>`
      SELECT email_hash FROM billing_trial_history WHERE email_hash = ${emailHash}
    `;
    return Boolean(row);
  } catch {
    return false;
  }
}

async function resolveUserPlanContext(userId: string, clerkToken?: string | null): Promise<UserPlanContext> {
  await ensureBillingSchema();
  const plan = await resolvePlanForUser(userId, clerkToken);

  let row: { created_at: Date | null; role: UserRole | null; email: string | null } | null = null;
  let hasRoleColumn = true;
  try {
    row = await userDB.queryRow<{ created_at: Date | null; role: UserRole | null; email: string | null }>`
      SELECT created_at, COALESCE(role, 'user') as role, email FROM users WHERE id = ${userId}
    `;
  } catch {
    // Defensive fallback for environments that have not applied role migration yet.
    hasRoleColumn = false;
    const fallback = await userDB.queryRow<{ created_at: Date | null; email: string | null }>`
      SELECT created_at, email FROM users WHERE id = ${userId}
    `;
    row = fallback ? { created_at: fallback.created_at, role: "user", email: fallback.email } : null;
  }

  if (!row) {
    throw APIError.notFound("User not found");
  }

  const dbRole: UserRole = row.role === "admin" ? "admin" : "user";
  const role: UserRole = hasRoleColumn ? await resolveRoleForUser(userId, dbRole) : dbRole;
  const trialAlreadyUsed = plan === "free" && role !== "admin"
    ? await readTrialAlreadyUsed(row.email)
    : false;
  return {
    plan,
    createdAt: row.created_at ?? new Date(),
    role,
    isAdmin: role === "admin",
    trialAlreadyUsed,
  };
}

function computePlanPolicy(context: UserPlanContext, now: Date): PlanPolicy {
  const { plan } = context;

  if (context.isAdmin) {
    return {
      plan,
      isAdmin: true,
      limits: { stories: null, dokus: null },
      dailyLimits: { stories: null, dokus: null },
      meteredLimits: { chat: null, assist: null, image: null, tts: null },
      usageWindow: "month",
      freeTrialActive: false,
      freeTrialEndsAt: null,
      freeTrialDaysRemaining: 0,
      audioLibraryAccess: "full",
      taviCanCreate: true,
    };
  }

  const freeTrialEndsAt = plan === "free" ? addDaysUTC(context.createdAt, FREE_TRIAL_DAYS) : null;
  const freeTrialActive = Boolean(
    freeTrialEndsAt && !context.trialAlreadyUsed && now < freeTrialEndsAt
  );

  return {
    plan,
    isAdmin: false,
    limits: freeTrialActive ? FREE_TRIAL_QUOTAS : PLAN_QUOTAS[plan],
    dailyLimits: PLAN_DAILY_LIMITS[plan],
    meteredLimits: freeTrialActive ? FREE_TRIAL_METERED_QUOTAS : PLAN_METERED_QUOTAS[plan],
    usageWindow: freeTrialActive ? "trial" : "month",
    freeTrialActive,
    freeTrialEndsAt,
    freeTrialDaysRemaining: freeTrialActive && freeTrialEndsAt ? remainingDaysUntil(now, freeTrialEndsAt) : 0,
    audioLibraryAccess: PLAN_AUDIO_LIBRARY_ACCESS[plan],
    taviCanCreate: PLAN_TAVI_CAN_CREATE[plan],
  };
}

async function loadPlanPolicy(userId: string, clerkToken?: string | null): Promise<PlanPolicy> {
  const context = await resolveUserPlanContext(userId, clerkToken);
  return computePlanPolicy(context, new Date());
}

function limitForKind(limits: PlanQuota, kind: UsageKind): number | null {
  return kind === "story" ? limits.stories : limits.dokus;
}

function getLimitLabel(kind: UsageKind) {
  return kind === "story" ? "Story-Münzen" : "Doku-Münzen";
}

// ---------------------------------------------------------------------------
// Usage reads
// ---------------------------------------------------------------------------

// SQLDatabase and Transaction share these methods, so both satisfy it.
type Queryable = Pick<Awaited<ReturnType<typeof userDB.begin>>, "queryRow" | "queryAll" | "rawQueryRow">;

// Counts coins that were spent and not refunded, in the policy's usage window.
async function readUsedCoins(
  db: Queryable,
  userId: string,
  kind: UsageKind,
  periodStart: Date,
  policy: PlanPolicy
): Promise<number> {
  if (policy.usageWindow === "trial") {
    const row = await db.queryRow<{ used: number }>`
      SELECT COALESCE(SUM(units), 0)::int AS used
      FROM quota_ledger
      WHERE user_id = ${userId}
        AND kind = ${kind}
        AND refunded_at IS NULL
        AND created_at >= (SELECT created_at FROM users WHERE id = ${userId})
    `;
    return row?.used ?? 0;
  }

  const ledger = await db.queryRow<{ used: number }>`
    SELECT COALESCE(SUM(units), 0)::int AS used
    FROM quota_ledger
    WHERE user_id = ${userId}
      AND kind = ${kind}
      AND period_start = ${periodStart}
      AND refunded_at IS NULL
  `;
  const counter = await db.queryRow<{ story_count: number; doku_count: number }>`
    SELECT story_count, doku_count
    FROM generation_usage
    WHERE user_id = ${userId} AND period_start = ${periodStart}
  `;
  const counted = kind === "story" ? counter?.story_count ?? 0 : counter?.doku_count ?? 0;
  // Older ledger rows could be missing (profile deletion used to remove them),
  // so the larger of both sources wins.
  return Math.max(ledger?.used ?? 0, counted);
}

async function readDailyAttempts(
  db: Queryable,
  userId: string,
  kind: UsageKind
): Promise<{ active: number; refunded: number }> {
  const row = await db.rawQueryRow<{ active: number; refunded: number }>(
    `SELECT
       COUNT(*) FILTER (WHERE refunded_at IS NULL)::int AS active,
       COUNT(*) FILTER (WHERE refunded_at IS NOT NULL)::int AS refunded
     FROM quota_ledger
     WHERE user_id = $1
       AND kind = $2
       AND created_at >= ${BERLIN_DAY_START_SQL}`,
    userId,
    kind
  );
  return { active: row?.active ?? 0, refunded: row?.refunded ?? 0 };
}

async function readMeteredUsageCounts(
  userId: string,
  periodStart: Date
): Promise<Record<MeteredUsageKind, number>> {
  const rows = await userDB.queryAll<{ kind: MeteredUsageKind; units: number }>`
    SELECT kind, units::int AS units
    FROM metered_usage
    WHERE user_id = ${userId} AND period_start = ${periodStart}
  `;

  const counts: Record<MeteredUsageKind, number> = { chat: 0, assist: 0, image: 0, tts: 0 };
  for (const row of rows) {
    if (row.kind in counts) {
      counts[row.kind] = row.units;
    }
  }
  return counts;
}

type UsageBucket = {
  limit: number | null;
  used: number;
  remaining: number | null;
  costPerGeneration: 1;
};

function buildUsageBucket(limit: number | null, used: number): UsageBucket {
  return {
    limit,
    used,
    remaining: limit === null ? null : Math.max(0, limit - used),
    costPerGeneration: 1,
  };
}

export type BillingOverview = {
  plan: SubscriptionPlan;
  periodStart: Date;
  storyCredits: UsageBucket;
  dokuCredits: UsageBucket;
  dailyStoryCredits: UsageBucket;
  dailyDokuCredits: UsageBucket;
  chatCredits: UsageBucket;
  assistCredits: UsageBucket;
  imageCredits: UsageBucket;
  ttsCharacterCredits: UsageBucket;
  audioLibrary: {
    access: AudioLibraryAccess;
    basicMinAgeDays: number;
  };
  permissions: {
    canReadCommunityDokus: boolean;
    canUseAudioDokus: boolean;
    taviCanCreate: boolean;
    freeTrialActive: boolean;
    freeTrialEndsAt: Date | null;
    freeTrialDaysRemaining: number;
  };
};

export async function getBillingOverview(params: {
  userId: string;
  clerkToken?: string | null;
}): Promise<BillingOverview> {
  const now = new Date();
  const periodStart = startOfMonthUTC(now);
  const policy = await loadPlanPolicy(params.userId, params.clerkToken);

  let storyUsed = 0;
  let dokuUsed = 0;
  let storyToday = 0;
  let dokuToday = 0;
  let metered: Record<MeteredUsageKind, number> = { chat: 0, assist: 0, image: 0, tts: 0 };

  try {
    [storyUsed, dokuUsed] = await Promise.all([
      readUsedCoins(userDB, params.userId, "story", periodStart, policy),
      readUsedCoins(userDB, params.userId, "doku", periodStart, policy),
    ]);
    const [storyDaily, dokuDaily] = await Promise.all([
      readDailyAttempts(userDB, params.userId, "story"),
      readDailyAttempts(userDB, params.userId, "doku"),
    ]);
    storyToday = storyDaily.active;
    dokuToday = dokuDaily.active;
  } catch (error) {
    console.warn("[billing.getBillingOverview] Failed to read usage counters, falling back to zero usage.", {
      userId: params.userId,
      error,
    });
  }

  try {
    metered = await readMeteredUsageCounts(params.userId, periodStart);
  } catch (error) {
    console.warn("[billing.getBillingOverview] Failed to read metered usage counters.", {
      userId: params.userId,
      error,
    });
  }

  return {
    plan: policy.plan,
    periodStart,
    storyCredits: buildUsageBucket(policy.limits.stories, storyUsed),
    dokuCredits: buildUsageBucket(policy.limits.dokus, dokuUsed),
    dailyStoryCredits: buildUsageBucket(policy.dailyLimits.stories, storyToday),
    dailyDokuCredits: buildUsageBucket(policy.dailyLimits.dokus, dokuToday),
    chatCredits: buildUsageBucket(policy.meteredLimits.chat, metered.chat),
    assistCredits: buildUsageBucket(policy.meteredLimits.assist, metered.assist),
    imageCredits: buildUsageBucket(policy.meteredLimits.image, metered.image),
    ttsCharacterCredits: buildUsageBucket(policy.meteredLimits.tts, metered.tts),
    audioLibrary: {
      access: policy.audioLibraryAccess,
      basicMinAgeDays: AUDIO_BASIC_LIBRARY_MIN_AGE_DAYS,
    },
    permissions: {
      canReadCommunityDokus: true,
      canUseAudioDokus: true,
      taviCanCreate: policy.taviCanCreate,
      freeTrialActive: policy.freeTrialActive,
      freeTrialEndsAt: policy.freeTrialEndsAt,
      freeTrialDaysRemaining: policy.freeTrialDaysRemaining,
    },
  };
}

export async function getPlanCapabilities(params: {
  userId: string;
  clerkToken?: string | null;
}): Promise<{
  plan: SubscriptionPlan;
  isAdmin: boolean;
  taviCanCreate: boolean;
  audioLibraryAccess: AudioLibraryAccess;
  freeTrialActive: boolean;
}> {
  const policy = await loadPlanPolicy(params.userId, params.clerkToken);
  return {
    plan: policy.plan,
    isAdmin: policy.isAdmin,
    taviCanCreate: policy.taviCanCreate,
    audioLibraryAccess: policy.audioLibraryAccess,
    freeTrialActive: policy.freeTrialActive,
  };
}

// ---------------------------------------------------------------------------
// Story / doku coins: reserve before generating, refund when it fails
// ---------------------------------------------------------------------------

type ProfileBudgetSnapshot = {
  softCap: number | null;
  hardCap: number | null;
  allowFamilyReserve: boolean;
};

function budgetForKind(
  kind: UsageKind,
  budget: Awaited<ReturnType<typeof getProfileBudgetPolicy>> | null
): ProfileBudgetSnapshot {
  if (!budget) {
    return { softCap: null, hardCap: null, allowFamilyReserve: false };
  }
  if (kind === "story") {
    return {
      softCap: budget.storySoftCap,
      hardCap: budget.storyHardCap,
      allowFamilyReserve: budget.allowFamilyReserve,
    };
  }
  return {
    softCap: budget.dokuSoftCap,
    hardCap: budget.dokuHardCap,
    allowFamilyReserve: budget.allowFamilyReserve,
  };
}

type BillingTx = Awaited<ReturnType<typeof userDB.begin>>;

async function lockUserBilling(tx: BillingTx, userId: string): Promise<void> {
  await tx.rawQueryRow(
    "SELECT pg_advisory_xact_lock($1, hashtext($2)) IS NOT NULL AS locked",
    BILLING_LOCK_NAMESPACE,
    userId
  );
}

// A downgrade keeps existing profiles, but only the first N (default first,
// then oldest) may spend coins. Otherwise a one-month Premium upgrade would
// leave ten usable profiles on Starter.
async function assertProfileWithinPlan(
  tx: BillingTx,
  userId: string,
  profileId: string,
  plan: SubscriptionPlan
): Promise<void> {
  const addonsRow = await tx.queryRow<{ addons: number }>`
    SELECT COALESCE(extra_profile_addons, 0)::int AS addons FROM users WHERE id = ${userId}
  `;
  const limit = getProfileLimitForPlan(plan, addonsRow?.addons ?? 0);
  const allowed = await tx.queryAll<{ id: string }>`
    SELECT id
    FROM child_profiles
    WHERE user_id = ${userId}
      AND is_archived = FALSE
    ORDER BY is_default DESC, created_at ASC, id ASC
    LIMIT ${limit}
  `;
  if (!allowed.some((row) => row.id === profileId)) {
    throw APIError.permissionDenied(
      `Abo-Limit erreicht: Dein Abo umfasst ${limit} Kinderprofil${limit === 1 ? "" : "e"}. Dieses Profil ist gesperrt, bis du upgradest oder ein anderes Profil auswählst.`
    );
  }
}

export type UsageClaim = {
  plan: SubscriptionPlan;
  kind: UsageKind;
  ledgerId: string;
  limit: number | null;
  used: number;
  remaining: number | null;
  profileId: string;
  usedByProfile: number;
  softCapReached: boolean;
  usedFamilyReserve: boolean;
  periodStart: Date;
};

/**
 * Reserves one story/doku coin before a generation starts.
 *
 * Limits are checked and the coin is written inside one transaction that
 * holds a per-user advisory lock, so parallel requests cannot overspend.
 * Call refundGenerationUsage with the same contentRef when the generation
 * fails; the coin is then returned and only successful generations cost.
 */
export async function claimGenerationUsage(params: {
  userId: string;
  kind: UsageKind;
  profileId?: string | null;
  contentRef: string;
  clerkToken?: string | null;
}): Promise<UsageClaim> {
  const now = new Date();
  const periodStart = startOfMonthUTC(now);
  const policy = await loadPlanPolicy(params.userId, params.clerkToken);
  const profileId = await resolveRequestedProfileId({
    userId: params.userId,
    requestedProfileId: params.profileId,
  });
  const budgetSnapshot = budgetForKind(
    params.kind,
    await getProfileBudgetPolicy({ userId: params.userId, profileId })
  );
  const limit = limitForKind(policy.limits, params.kind);
  const dailyLimit = limitForKind(policy.dailyLimits, params.kind);
  const label = getLimitLabel(params.kind);

  await using tx = await userDB.begin();
  await lockUserBilling(tx, params.userId);

  const existing = await tx.queryRow<{ id: string }>`
    SELECT id FROM quota_ledger
    WHERE user_id = ${params.userId}
      AND kind = ${params.kind}
      AND content_ref = ${params.contentRef}
      AND refunded_at IS NULL
    LIMIT 1
  `;
  if (existing) {
    throw APIError.alreadyExists("Für diesen Inhalt wurde bereits eine Münze reserviert.");
  }

  const usedByProfileRow = await tx.queryRow<{ used: number }>`
    SELECT COALESCE(SUM(units), 0)::int AS used
    FROM quota_ledger
    WHERE user_id = ${params.userId}
      AND profile_id = ${profileId}
      AND period_start = ${periodStart}
      AND kind = ${params.kind}
      AND refunded_at IS NULL
  `;
  const usedByProfileBefore = usedByProfileRow?.used ?? 0;
  const softCapReached =
    budgetSnapshot.softCap !== null && usedByProfileBefore >= budgetSnapshot.softCap;
  const hardCapReached =
    budgetSnapshot.hardCap !== null && usedByProfileBefore >= budgetSnapshot.hardCap;

  let usedBefore = 0;
  let usedFamilyReserve = false;

  if (!policy.isAdmin) {
    await assertProfileWithinPlan(tx, params.userId, profileId, policy.plan);

    if (limit !== null && limit <= 0) {
      throw APIError.permissionDenied(`Abo-Limit erreicht: Dein Abo enthält keine ${label}.`);
    }

    const daily = await readDailyAttempts(tx, params.userId, params.kind);
    if (daily.refunded >= MAX_REFUNDED_ATTEMPTS_PER_DAY) {
      throw APIError.resourceExhausted(
        "Heute sind zu viele Erstellungen fehlgeschlagen. Bitte versuche es morgen wieder."
      );
    }
    if (dailyLimit !== null && daily.active >= dailyLimit) {
      // The "Abo-Limit erreicht" prefix makes the wizards show the upgrade dialog.
      throw APIError.permissionDenied(
        `Abo-Limit erreicht: Tageslimit von ${dailyLimit} ${label} für heute ist verbraucht. Morgen geht es weiter.`
      );
    }

    usedBefore = await readUsedCoins(tx, params.userId, params.kind, periodStart, policy);
    if (limit !== null && usedBefore >= limit) {
      throw APIError.permissionDenied(
        policy.usageWindow === "trial"
          ? `Abo-Limit erreicht: Die ${limit} ${label} deiner Testphase sind verbraucht. Upgrade auf Starter, Familie oder Premium.`
          : policy.plan === "free"
            ? `Abo-Limit erreicht: ${limit} ${label} pro Monat im kostenlosen Plan. Upgrade auf Starter, Familie oder Premium.`
            : `Abo-Limit erreicht: ${limit} ${label} pro Monat. Bitte Abo upgraden.`
      );
    }

    if (hardCapReached) {
      if (!budgetSnapshot.allowFamilyReserve) {
        throw APIError.permissionDenied(
          `Profil-Limit erreicht: ${budgetSnapshot.hardCap} ${label} für dieses Profil.`
        );
      }
      const reserveRow = params.kind === "story"
        ? await tx.queryRow<{ id: string }>`
            UPDATE users
            SET family_reserve_story_used = family_reserve_story_used + 1,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ${params.userId}
              AND family_reserve_story_used < family_reserve_story
            RETURNING id
          `
        : await tx.queryRow<{ id: string }>`
            UPDATE users
            SET family_reserve_doku_used = family_reserve_doku_used + 1,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ${params.userId}
              AND family_reserve_doku_used < family_reserve_doku
            RETURNING id
          `;
      if (!reserveRow) {
        throw APIError.permissionDenied(
          `Profil-Limit erreicht und die Familien-Reserve für ${label} ist aufgebraucht.`
        );
      }
      usedFamilyReserve = true;
    }
  }

  const ledgerId = crypto.randomUUID();
  await tx.exec`
    INSERT INTO quota_ledger (
      id, user_id, profile_id, period_start, kind, units, content_ref, used_family_reserve, created_at
    )
    VALUES (
      ${ledgerId}, ${params.userId}, ${profileId}, ${periodStart}, ${params.kind}, 1,
      ${params.contentRef}, ${usedFamilyReserve}, CURRENT_TIMESTAMP
    )
  `;
  await tx.exec`
    INSERT INTO generation_usage (user_id, period_start, story_count, doku_count, updated_at)
    VALUES (
      ${params.userId}, ${periodStart},
      ${params.kind === "story" ? 1 : 0}, ${params.kind === "doku" ? 1 : 0}, ${now}
    )
    ON CONFLICT (user_id, period_start) DO UPDATE
    SET story_count = generation_usage.story_count + ${params.kind === "story" ? 1 : 0},
        doku_count = generation_usage.doku_count + ${params.kind === "doku" ? 1 : 0},
        updated_at = ${now}
  `;
  await tx.commit();

  const used = usedBefore + 1;
  return {
    plan: policy.plan,
    kind: params.kind,
    ledgerId,
    limit,
    used,
    remaining: limit === null ? null : Math.max(0, limit - used),
    profileId,
    usedByProfile: usedByProfileBefore + 1,
    softCapReached,
    usedFamilyReserve,
    periodStart,
  };
}

/**
 * Returns the coin reserved for contentRef. Idempotent: a second call finds
 * no open reservation and does nothing. Never throws, so it is safe to call
 * from error handlers.
 */
export async function refundGenerationUsage(params: {
  userId: string;
  kind: UsageKind;
  contentRef: string;
  reason?: string;
}): Promise<boolean> {
  try {
    await ensureBillingSchema();
    await using tx = await userDB.begin();
    await lockUserBilling(tx, params.userId);

    const row = await tx.queryRow<{
      id: string;
      period_start: Date;
      units: number;
      used_family_reserve: boolean;
    }>`
      UPDATE quota_ledger
      SET refunded_at = CURRENT_TIMESTAMP
      WHERE id = (
        SELECT id FROM quota_ledger
        WHERE user_id = ${params.userId}
          AND kind = ${params.kind}
          AND content_ref = ${params.contentRef}
          AND refunded_at IS NULL
        ORDER BY created_at DESC
        LIMIT 1
      )
      RETURNING id, period_start, units, used_family_reserve
    `;
    if (!row) {
      await tx.commit();
      return false;
    }

    if (params.kind === "story") {
      await tx.exec`
        UPDATE generation_usage
        SET story_count = GREATEST(story_count - ${row.units}, 0), updated_at = CURRENT_TIMESTAMP
        WHERE user_id = ${params.userId} AND period_start = ${row.period_start}
      `;
    } else {
      await tx.exec`
        UPDATE generation_usage
        SET doku_count = GREATEST(doku_count - ${row.units}, 0), updated_at = CURRENT_TIMESTAMP
        WHERE user_id = ${params.userId} AND period_start = ${row.period_start}
      `;
    }

    if (row.used_family_reserve) {
      if (params.kind === "story") {
        await tx.exec`
          UPDATE users
          SET family_reserve_story_used = GREATEST(family_reserve_story_used - 1, 0),
              updated_at = CURRENT_TIMESTAMP
          WHERE id = ${params.userId}
        `;
      } else {
        await tx.exec`
          UPDATE users
          SET family_reserve_doku_used = GREATEST(family_reserve_doku_used - 1, 0),
              updated_at = CURRENT_TIMESTAMP
          WHERE id = ${params.userId}
        `;
      }
    }

    await tx.commit();
    console.info("[billing.refundGenerationUsage] Coin refunded", {
      userId: params.userId,
      kind: params.kind,
      contentRef: params.contentRef,
      reason: params.reason,
    });
    return true;
  } catch (error) {
    console.error("[billing.refundGenerationUsage] Refund failed", {
      userId: params.userId,
      kind: params.kind,
      contentRef: params.contentRef,
      error: error instanceof Error ? error.message : String(error),
    });
    return false;
  }
}

// ---------------------------------------------------------------------------
// Metered usage (Tavi chat, assist, images, TTS)
// ---------------------------------------------------------------------------

export type MeteredUsageClaim = {
  userId: string;
  plan: SubscriptionPlan;
  kind: MeteredUsageKind;
  units: number;
  used: number;
  limit: number | null;
  remaining: number | null;
  periodStart: Date;
  refundedUnits: number;
};

function meteredLimitLabel(kind: MeteredUsageKind): string {
  if (kind === "chat") return "Tavi-Nachrichten";
  if (kind === "assist") return "KI-Hilfen (Avatar & Vorschläge)";
  if (kind === "image") return "KI-Bilder";
  return "Zeichen für die Vorlesefunktion";
}

export async function claimMeteredUsage(params: {
  userId: string;
  kind: MeteredUsageKind;
  units?: number;
  clerkToken?: string | null;
}): Promise<MeteredUsageClaim> {
  const units = Math.floor(params.units ?? 1);
  if (!Number.isFinite(units) || units < 1 || units > 5_000_000) {
    throw APIError.invalidArgument("Invalid metered usage amount");
  }

  const now = new Date();
  const periodStart = startOfMonthUTC(now);
  const policy = await loadPlanPolicy(params.userId, params.clerkToken);
  const limit = policy.meteredLimits[params.kind];

  if (limit !== null && (limit <= 0 || units > limit)) {
    throw APIError.permissionDenied(
      `Abo-Limit erreicht: ${limit} ${meteredLimitLabel(params.kind)} pro Monat.`
    );
  }

  try {
    await userDB.exec`
      INSERT INTO metered_usage (user_id, period_start, kind, units, updated_at)
      VALUES (${params.userId}, ${periodStart}, ${params.kind}, 0, ${now})
      ON CONFLICT (user_id, period_start, kind) DO NOTHING
    `;
  } catch {
    throw APIError.failedPrecondition(
      "Billing-Datenbank nicht bereit. Bitte User-Migration 12_billing_v2 ausführen."
    );
  }

  // The limit check and the increment are one atomic statement.
  const row = limit === null
    ? await userDB.queryRow<{ units: number }>`
        UPDATE metered_usage
        SET units = units + ${units}, updated_at = ${now}
        WHERE user_id = ${params.userId}
          AND period_start = ${periodStart}
          AND kind = ${params.kind}
        RETURNING units::int AS units
      `
    : await userDB.queryRow<{ units: number }>`
        UPDATE metered_usage
        SET units = units + ${units}, updated_at = ${now}
        WHERE user_id = ${params.userId}
          AND period_start = ${periodStart}
          AND kind = ${params.kind}
          AND units + ${units} <= ${limit}
        RETURNING units::int AS units
      `;

  if (!row) {
    throw APIError.permissionDenied(
      policy.plan === "free"
        ? `Abo-Limit erreicht: ${limit} ${meteredLimitLabel(params.kind)} pro Monat im kostenlosen Plan. Upgrade für mehr.`
        : `Abo-Limit erreicht: ${limit} ${meteredLimitLabel(params.kind)} pro Monat. Bitte Abo upgraden.`
    );
  }

  return {
    userId: params.userId,
    plan: policy.plan,
    kind: params.kind,
    units,
    used: row.units,
    limit,
    remaining: limit === null ? null : Math.max(0, limit - row.units),
    periodStart,
    refundedUnits: 0,
  };
}

/**
 * Gives back units of a claim whose work failed. Refunds are capped at the
 * claimed amount, so a claim can never be refunded twice. Never throws.
 */
export async function refundMeteredUsage(
  claim: MeteredUsageClaim | null | undefined,
  units?: number
): Promise<void> {
  if (!claim) return;
  const requested = Math.floor(units ?? claim.units);
  const refundable = Math.min(requested, claim.units - claim.refundedUnits);
  if (!Number.isFinite(refundable) || refundable <= 0) return;
  claim.refundedUnits += refundable;

  try {
    await userDB.exec`
      UPDATE metered_usage
      SET units = GREATEST(units - ${refundable}, 0), updated_at = CURRENT_TIMESTAMP
      WHERE user_id = ${claim.userId}
        AND period_start = ${claim.periodStart}
        AND kind = ${claim.kind}
    `;
  } catch (error) {
    console.error("[billing.refundMeteredUsage] Refund failed", {
      userId: claim.userId,
      kind: claim.kind,
      units: refundable,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

/**
 * Claims metered units, runs the work and refunds the units if the work
 * throws or `isSuccess` rejects the result.
 */
export async function withMeteredUsage<T>(
  params: {
    userId: string;
    kind: MeteredUsageKind;
    units?: number;
    clerkToken?: string | null;
  },
  work: () => Promise<T>,
  isSuccess?: (result: T) => boolean
): Promise<T> {
  const claim = await claimMeteredUsage(params);
  let result: T;
  try {
    result = await work();
  } catch (error) {
    await refundMeteredUsage(claim);
    throw error;
  }
  if (isSuccess && !isSuccess(result)) {
    await refundMeteredUsage(claim);
  }
  return result;
}

// ---------------------------------------------------------------------------
// Access checks
// ---------------------------------------------------------------------------

export async function assertCommunityDokuAccess(params: {
  userId: string;
  clerkToken?: string | null;
}): Promise<BillingOverview> {
  return getBillingOverview(params);
}

export async function getAudioLibraryAccess(params: {
  userId: string;
  clerkToken?: string | null;
}): Promise<AudioLibraryAccess> {
  const policy = await loadPlanPolicy(params.userId, params.clerkToken);
  return policy.audioLibraryAccess;
}

/**
 * Remembers a deleted account's e-mail (hashed) so a new sign-up with the
 * same address does not receive a second free trial.
 */
export async function recordTrialHistoryForDeletedUser(userId: string): Promise<void> {
  try {
    await ensureBillingSchema();
    const row = await userDB.queryRow<{ email: string | null; created_at: Date | null }>`
      SELECT email, created_at FROM users WHERE id = ${userId}
    `;
    const emailHash = hashEmailForTrial(row?.email);
    if (!emailHash) return;
    await userDB.exec`
      INSERT INTO billing_trial_history (email_hash, first_trial_started_at)
      VALUES (${emailHash}, ${row?.created_at ?? new Date()})
      ON CONFLICT (email_hash) DO NOTHING
    `;
  } catch (error) {
    console.warn("[billing.recordTrialHistoryForDeletedUser] skipped", {
      userId,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}
