// TypeScript types for character pool and 4-phase story generation system

export interface CharacterTemplate {
  id: string;
  name: string;
  role: string; // guide, companion, obstacle, discovery, support, special
  archetype: string; // helpful_elder, loyal_animal, etc.

  // Emotional Profile
  emotionalNature: {
    dominant: string;
    secondary: string[];
    triggers?: string[];
  };

  // Visual Profile
  visualProfile: {
    description: string;
    imagePrompt?: string;
    species: string;
    colorPalette: string[];
  };
  imageUrl?: string;

  // NEW: Enhanced Matching Attributes (Migration 7)
  gender?: string; // male, female, neutral, any
  age_category?: string; // child, teenager, young_adult, adult, elder, ageless, any
  species_category?: string; // human, humanoid, animal, magical_creature, mythical, elemental, any
  profession_tags?: string[]; // ['royalty', 'craftsman', 'warrior', etc.]
  size_category?: string; // tiny, small, medium, large, giant, any
  social_class?: string; // royalty, nobility, merchant, craftsman, commoner, outcast, any
  personality_keywords?: string[]; // ['brave', 'cunning', 'kind', etc.]
  physical_description?: string;
  backstory?: string;

  // Screen Time & Availability
  maxScreenTime: number; // 0-100 percentage
  availableChapters: number[]; // [1,2,3,4,5]
  canonSettings?: string[]; // Where this character fits

  // Tracking
  recentUsageCount?: number;
  totalUsageCount?: number;
  lastUsedAt?: Date;

  // Metadata
  createdAt?: Date;
  updatedAt?: Date;
  isActive?: boolean;
}

export interface CharacterRequirement {
  placeholder: string; // e.g., "{{WISE_ELDER}}"
  role: string;
  archetype: string;
  emotionalNature: string;
  requiredTraits: string[];
  visualHints?: string; // NEW: Visual description hints (animal type, profession, appearance)
  importance: "high" | "medium" | "low";
  inChapters: number[];
}

export interface ChapterSkeleton {
  order: number;
  content: string; // Story with {{PLACEHOLDERS}}
  characterRolesNeeded: {
    placeholder: string;
    role: string;
    archetype: string;
    emotionalNature: string;
    visualHints?: string; // NEW: Visual description hints
    importance: "high" | "medium" | "low";
    inChapters: number[];
  }[];
}

export interface StorySkeleton {
  title: string;
  chapters: ChapterSkeleton[];
  supportingCharacterRequirements: CharacterRequirement[];
  supportingCharacters?: Array<{
    placeholder: string;
    role: string;
    description?: string;
  }>;
  // NEW: Artifact requirement for Phase 2 matching
  artifactRequirement?: ArtifactRequirement;
}

export interface FinalChapter {
  order: number;
  title: string;
  content: string;
  imageDescription: string; // English description for image generation
}

export interface AvatarDevelopment {
  avatarName: string;
  updates: Array<{
    trait: string; // e.g., "knowledge", "knowledge.history", "creativity", "courage"
    change: number; // Positive number for growth
    description: string; // Why this trait developed
  }>;
}

/**
 * Artifact generated by the AI at the end of a story
 * The avatar receives this as a reward/loot item
 * @deprecated Use ArtifactTemplate from artifact_pool instead
 */
export interface NewArtifact {
  name: string;                      // Name in user's language
  description: string;               // Description in user's language
  type: 'TOOL' | 'WEAPON' | 'KNOWLEDGE' | 'COMPANION';
  storyEffect: string;               // What the artifact can do in future stories (user's language)
  visualDescriptorKeywords: string[]; // English keywords for image generation
}

// ============================================================
// ARTIFACT POOL SYSTEM (Analog to Character Pool)
// ============================================================

/**
 * Artifact categories matching the artifact_pool table
 */
export type ArtifactCategory =
  | 'weapon'
  | 'clothing'
  | 'magic'
  | 'book'
  | 'tool'
  | 'tech'
  | 'nature'
  | 'potion'
  | 'jewelry'
  | 'armor'
  | 'map';

export type ArtifactRarity = 'common' | 'uncommon' | 'rare' | 'legendary';

/**
 * Template for predefined artifacts in the artifact_pool
 * Analog to CharacterTemplate for characters
 */
export interface ArtifactTemplate {
  id: string;

  // Bilingual names and descriptions
  name: { de: string; en: string };
  description: { de: string; en: string };

  // Categorization
  category: ArtifactCategory;
  rarity: ArtifactRarity;

  // Story integration
  storyRole: string;                  // How the artifact helps in a story
  discoveryScenarios: string[];       // Where/how it can be found
  usageScenarios: string[];           // How it can be used

  // Visual
  emoji?: string;                     // Fallback emoji representation
  visualKeywords: string[];           // For image generation
  imageUrl?: string;                  // Optional generated image

  // Genre affinity (0.0 - 1.0 for matching)
  genreAffinity: {
    adventure: number;
    fantasy: number;
    mystery: number;
    nature: number;
    friendship: number;
    courage: number;
    learning: number;
  };

  // Usage tracking
  recentUsageCount: number;
  totalUsageCount: number;
  lastUsedAt?: Date;
  lastUsedInStoryId?: string;

  // Metadata
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Artifact requirement defined by Phase 1 (Skeleton)
 * Analog to CharacterRequirement for characters
 */
export interface ArtifactRequirement {
  placeholder: string;                // Always "{{ARTIFACT_REWARD}}"
  preferredCategory?: ArtifactCategory; // "weapon", "magic", etc.
  requiredAbility?: string;           // "navigation", "protection", "healing", etc.
  contextHint: string;                // Why this type of artifact fits the story
  discoveryChapter: number;           // Chapter where artifact should be found (1-5)
  usageChapter: number;               // Chapter where artifact should be used (> discoveryChapter)
  importance: 'high' | 'medium';      // How central is the artifact to the story
}

/**
 * Pending artifact stored in story metadata before unlock
 */
export interface PendingArtifact {
  id: string;
  name: string;                       // In user's language (de or en)
  nameEn?: string;                    // English name for reference
  description: string;                // In user's language
  category: ArtifactCategory;
  rarity: ArtifactRarity;
  storyRole: string;
  visualKeywords: string[];
  imageUrl?: string;
  discoveryChapter: number;
  usageChapter: number;
  locked: boolean;                    // True until user reads the story
  unlockedAt?: string;                // ISO timestamp when unlocked
}

export interface FinalizedStory {
  title: string;
  description: string;
  chapters: FinalChapter[];
  avatarDevelopments?: AvatarDevelopment[];
  newArtifact?: NewArtifact;         // 🎁 NEW: Loot item awarded at story end
}

export interface CharacterAssignment {
  placeholder: string;
  character: CharacterTemplate;
}

export interface GeneratedImage {
  chapterOrder: number;
  imageUrl: string;
  generatedAt: Date;
  prompt: string;
}
