name: Build and Deploy Talea Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'Dockerfile.backend'
      - '.github/workflows/deploy-backend.yml'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Encore CLI
        run: |
          curl -L https://encore.dev/install.sh | bash

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install backend dependencies
        working-directory: backend
        run: |
          bun install

      - name: Build frontend
        working-directory: frontend
        run: |
          bun install
          bun run build

      - name: Copy frontend build to backend
        run: |
          cp -r frontend/dist backend/frontend/dist

      - name: Build Docker image with Encore
        working-directory: backend
        run: |
          $HOME/.encore/bin/encore build docker --config=./infra.config.railway.json talea-backend:latest

      - name: Tag Docker image for GitHub Container Registry
        run: |
          docker tag talea-backend:latest ghcr.io/${{ github.repository_owner }}/talea-backend:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/talea-backend:latest

      - name: Trigger Railway deployment
        if: github.event_name == 'push'
        run: |
          curl -X POST https://api.railway.app/graphql/v2 \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query":"mutation { serviceInstanceRedeploy(serviceId: \"${{ secrets.RAILWAY_SERVICE_ID }}\") }"}'

